/*!
* Nethereum.Generators.DuoCode, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
*
* Generated by DuoCode Compiler 3.0.1654.0 [Trial]
*/
(function Nethereum_Generators_DuoCode() {
"use strict";
var $asm = {
    fullName: "Nethereum.Generators.DuoCode",
    anonymousTypes: [],
    types: [],
    getAttrs: function() { return [new DuoCode.Runtime.CompilerAttribute.ctor("3.0.1654.0")]; }
};
var $g = (typeof(global) !== "undefined" ? global : (typeof(window) !== "undefined" ? window : self));
var Nethereum = $g.Nethereum = $g.Nethereum || {};
Nethereum.Generators = Nethereum.Generators || {};
Nethereum.Generators.Core = Nethereum.Generators.Core || {};
Nethereum.Generators.CQS = Nethereum.Generators.CQS || {};
Nethereum.Generators.DTOs = Nethereum.Generators.DTOs || {};
Nethereum.Generators.Model = Nethereum.Generators.Model || {};
Nethereum.Generators.Service = Nethereum.Generators.Service || {};
var $d = DuoCode.Runtime;
$d.$assemblies["Nethereum.Generators.DuoCode"] = $asm;
Nethereum.Generators.Core.ABIServiceBase = $d.declare("Nethereum.Generators.Core.ABIServiceBase", 0, 
    $asm);
Nethereum.Generators.Core.ABITypeToCSharpType = $d.declare("Nethereum.Generators.Core.ABITypeToCSharpType", 
    0, $asm);
Nethereum.Generators.Core.CommonGenerators = $d.declare("Nethereum.Generators.Core.CommonGenerators", 
    0, $asm);
Nethereum.Generators.Core.FunctionABIModel = $d.declare("Nethereum.Generators.Core.FunctionABIModel", 
    0, $asm);
Nethereum.Generators.Core.ParameterABIModel = $d.declare("Nethereum.Generators.Core.ParameterABIModel", 
    0, $asm);
Nethereum.Generators.Core.SpaceUtils = $d.declare("Nethereum.Generators.Core.SpaceUtils", 0, $asm);
Nethereum.Generators.Core.Utils = $d.declare("Nethereum.Generators.Core.Utils", 0, $asm);
Nethereum.Generators.CQS.ContractDeploymentCQSMessageGenerator = $d.declare("Nethereum.Generators.CQS.ContractDeploymentCQSMessageGenerator", 
    0, $asm);
Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel = $d.declare("Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel", 
    0, $asm);
Nethereum.Generators.CQS.ContractDeploymentCQSMessageTemplate = $d.declare("Nethereum.Generators.CQS.ContractDeploymentCQSMessageTemplate", 
    0, $asm);
Nethereum.Generators.CQS.FunctionCQSMessageGenerator = $d.declare("Nethereum.Generators.CQS.FunctionCQSMessageGenerator", 
    0, $asm);
Nethereum.Generators.CQS.FunctionCQSMessageModel = $d.declare("Nethereum.Generators.CQS.FunctionCQSMessageModel", 
    0, $asm);
Nethereum.Generators.CQS.FunctionCQSMessageTemplate = $d.declare("Nethereum.Generators.CQS.FunctionCQSMessageTemplate", 
    0, $asm);
Nethereum.Generators.DTOs.EventDTOGenerator = $d.declare("Nethereum.Generators.DTOs.EventDTOGenerator", 
    0, $asm);
Nethereum.Generators.DTOs.EventDTOModel = $d.declare("Nethereum.Generators.DTOs.EventDTOModel", 0, $asm);
Nethereum.Generators.DTOs.EventDTOTemplate = $d.declare("Nethereum.Generators.DTOs.EventDTOTemplate", 
    0, $asm);
Nethereum.Generators.DTOs.FunctionOutputDTOGenerator = $d.declare("Nethereum.Generators.DTOs.FunctionOutputDTOGenerator", 
    0, $asm);
Nethereum.Generators.DTOs.FunctionOutputDTOModel = $d.declare("Nethereum.Generators.DTOs.FunctionOutputDTOModel", 
    0, $asm);
Nethereum.Generators.DTOs.FunctionOutputDTOTemplate = $d.declare("Nethereum.Generators.DTOs.FunctionOutputDTOTemplate", 
    0, $asm);
Nethereum.Generators.DTOs.ParameterABIEventDTOTemplate = $d.declare("Nethereum.Generators.DTOs.ParameterABIEventDTOTemplate", 
    0, $asm);
Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate = $d.declare("Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate", 
    0, $asm);
Nethereum.Generators.Model.ConstructorABI = $d.declare("Nethereum.Generators.Model.ConstructorABI", 0, 
    $asm);
Nethereum.Generators.Model.ContractABI = $d.declare("Nethereum.Generators.Model.ContractABI", 0, $asm);
Nethereum.Generators.Model.EventABI = $d.declare("Nethereum.Generators.Model.EventABI", 0, $asm);
Nethereum.Generators.Model.FunctionABI = $d.declare("Nethereum.Generators.Model.FunctionABI", 0, $asm);
Nethereum.Generators.Model.Parameter = $d.declare("Nethereum.Generators.Model.Parameter", 0, $asm);
Nethereum.Generators.Service.ContractDeploymentServiceMethodsTemplate = $d.declare("Nethereum.Generators.Service.ContractDeploymentServiceMethodsTemplate", 
    0, $asm);
Nethereum.Generators.Service.FunctionServiceMethodTemplate = $d.declare("Nethereum.Generators.Service.FunctionServiceMethodTemplate", 
    0, $asm);
$d.define(Nethereum.Generators.Core.ABIServiceBase, null, function($t, $p) {
    $t.ctor = function ABIServiceBase() {
        $t.$baseType.ctor.call(this);
    };
    $t.GetFirstFunction = function ABIServiceBase_GetFirstFunction(abi) {
        var contract = $t.GetContract(abi);
        return contract.get_Functions()[0];
    };
    $t.GetFirstEvent = function ABIServiceBase_GetFirstEvent(abi) {
        var contract = $t.GetContract(abi);
        return contract.get_Events()[0];
    };
    $t.GetConstructorABI = function ABIServiceBase_GetConstructorABI(abi) {
        var contract = $t.GetContract(abi);
        return contract.get_Constructor();
    };
    $t.GetContract = function ABIServiceBase_GetContract(abi) {
        //  var des = new ABIDeserialiser();
        // var contract = des.DeserialiseContract(abi);
        // return contract;
        return null;
    };
});
$d.define(Nethereum.Generators.Core.ABITypeToCSharpType, null, function($t, $p) {
    $t.ctor = function ABITypeToCSharpType() {
        $t.$baseType.ctor.call(this);
    };
    $p.GetTypeMap = function ABITypeToCSharpType_GetTypeMap(typeName, outputMapType) {
        var indexFirstBracket = typeName.indexOf("[");
        if (indexFirstBracket > -1) {
            var elementTypeName = typeName.Substring$1(0, indexFirstBracket);
            if (outputMapType) {
                return "List<" + this.GetTypeMap(elementTypeName, true) + ">";
            }
            else {
                return this.GetTypeMap(elementTypeName, false) + "[]";
            }
        }
        if ("bool" == typeName) {
            return typeName;
        }
        if (typeName.StartsWith("int")) {
            //default
            if (typeName.length == 3) {
                return "BigInteger";
            }
            var length = System.Int32.Parse(typeName.Substring(3));

            if (length > 64) {
                return "BigInteger";
            }
            if (length <= 64 && length > 32) {
                return "long";
            }
            //ints are in 8 bits
            if (length == 32) {
                return "int";
            }
            if (length == 16) {
                return "short";
            }
            if (length == 8) {
                return "sbyte";
            }
        }
        if (typeName.StartsWith("uint")) {

            if (typeName.length == 4) {
                return "BigInteger";
            }
            var length = System.Int32.Parse(typeName.Substring(4));

            if (length > 64) {
                return "BigInteger";
            }
            if (length <= 64 && length > 32) {
                return "ulong";
            }
            //uints are in 8 bits steps
            if (length == 32) {
                return "int";
            }
            if (length == 16) {
                return "short";
            }
            if (length == 8) {
                return "byte";
            }
        }
        if (typeName == "address") {
            return "string";
        }
        if (typeName == "string") {
            return "string";
        }
        if (typeName == "bytes") {
            return "byte[]";
        }
        if (typeName.StartsWith("bytes")) {
            return "byte[]";
        }
        return null;
    };
});
$d.define(Nethereum.Generators.Core.CommonGenerators, null, function($t, $p) {
    $t.$ator = function() {
        this.utils = null;
    };
    $t.ctor = function CommonGenerators() {
        $t.$baseType.ctor.call(this);
        this.utils = new Nethereum.Generators.Core.Utils.ctor();
    };
    $p.GenerateVariableName = function CommonGenerators_GenerateVariableName(value) {
        return this.utils.LowerCaseFirstCharAndRemoveUnderscorePrefix(value);
    };
    $p.GeneratePropertyName = function CommonGenerators_GeneratePropertyName(value) {
        return this.utils.CapitaliseFirstCharAndRemoveUnderscorePrefix(value);
    };
    $p.GenerateClassName = function CommonGenerators_GenerateClassName(value) {
        return this.utils.CapitaliseFirstCharAndRemoveUnderscorePrefix(value);
    };
});
$d.define(Nethereum.Generators.Core.FunctionABIModel, null, function($t, $p) {
    $t.$ator = function() {
        this.abiTypeToCSharpType = null;
    };
    $t.ctor = function FunctionABIModel() {
        $t.$baseType.ctor.call(this);
        this.abiTypeToCSharpType = new Nethereum.Generators.Core.ABITypeToCSharpType.ctor();
    };
    $p.GetSingleOutputGenericReturnType = function FunctionABIModel_GetSingleOutputGenericReturnType(item) {
        if (item == null)
            return String.Empty;
        return String.Format("<{0}>", [this.GetSingleOutputReturnType(item)]);
    };
    $p.GetSingleOutputReturnType = function FunctionABIModel_GetSingleOutputReturnType(functionABI) {
        if (functionABI.get_OutputParameters() != null && functionABI.get_OutputParameters().length == 1) {
            return this.abiTypeToCSharpType.GetTypeMap(functionABI.get_OutputParameters()[0].get_Type(), 
                true);
        }
        return null;
    };
    $p.GetSingleAbiReturnType = function FunctionABIModel_GetSingleAbiReturnType(functionABI) {
        if (functionABI.get_OutputParameters() != null && functionABI.get_OutputParameters().length == 1) {
            return functionABI.get_OutputParameters()[0].get_Type();
        }
        return null;
    };
    $p.IsMultipleOutput = function FunctionABIModel_IsMultipleOutput(functionAbi) {
        return functionAbi.get_OutputParameters() != null && functionAbi.get_OutputParameters().length > 1;
    };
    $p.IsSingleOutput = function FunctionABIModel_IsSingleOutput(functionAbi) {
        return functionAbi.get_OutputParameters() != null && functionAbi.get_OutputParameters().length == 1;
    };
    $p.HasNoReturn = function FunctionABIModel_HasNoReturn(functionAbi) {
        return functionAbi.get_OutputParameters() == null || functionAbi.get_OutputParameters().length == 0;
    };
});
$d.define(Nethereum.Generators.Core.ParameterABIModel, null, function($t, $p) {
    $t.$ator = function() {
        this.commonGenerators = null;
        this.abiTypeToCSharpType = null;
    };
    $t.ctor = function ParameterABIModel() {
        $t.$baseType.ctor.call(this);
        this.commonGenerators = new Nethereum.Generators.Core.CommonGenerators.ctor();
        this.abiTypeToCSharpType = new Nethereum.Generators.Core.ABITypeToCSharpType.ctor();
    };
    $p.GetParameterVariableName$1 = function ParameterABIModel_GetParameterVariableName(name, order) {
        return this.commonGenerators.GenerateVariableName(this.GetParameterName(name, order));
    };
    $p.GetParameterPropertyName = function ParameterABIModel_GetParameterPropertyName(parameter) {
        return this.GetParameterPropertyName$1(parameter.get_Name(), parameter.get_Order());
    };
    $p.GetParameterVariableName = function ParameterABIModel_GetParameterVariableName(parameter) {
        return this.GetParameterVariableName$1(parameter.get_Name(), parameter.get_Order());
    };
    $p.GetParameterPropertyName$1 = function ParameterABIModel_GetParameterPropertyName(name, order) {
        return this.commonGenerators.GeneratePropertyName(this.GetParameterName(name, order));
    };
    $p.GetParameterCSharpOutputMapType = function ParameterABIModel_GetParameterCSharpOutputMapType(parameter) {
        return this.abiTypeToCSharpType.GetTypeMap(parameter.get_Type(), true);
    };
    $p.GetParameterCSharpInputMapType = function ParameterABIModel_GetParameterCSharpInputMapType(parameter) {
        return this.abiTypeToCSharpType.GetTypeMap(parameter.get_Type(), false);
    };
    $p.GetParameterName = function ParameterABIModel_GetParameterName(name, order) {
        if (name != "")
            return name;
        switch (order) {
            case 0:
                return "a";
            case 1:
                return "b";
            case 2:
                return "c";
            case 3:
                return "d";
            case 4:
                return "e";
            case 5:
                return "f";
            case 6:
                return "g";
        }
        return "h";
    };
});
$d.define(Nethereum.Generators.Core.SpaceUtils, null, function($t, $p) {
    $t.cctor = function() {
        $t.OneTab = "    ";
        $t.TwoTabs = $t().OneTab + $t().OneTab;
        $t.ThreeTabs = $t().OneTab + $t().OneTab + $t().OneTab;
    };
    $t.ctor = function SpaceUtils() {
        $t.$baseType.ctor.call(this);
    };
});
$d.define(Nethereum.Generators.Core.Utils, null, function($t, $p) {
    $t.ctor = function Utils() {
        $t.$baseType.ctor.call(this);
    };
    $p.RemoveUnderscorePrefix = function Utils_RemoveUnderscorePrefix(value) {
        return value.TrimStart($d.array(System.Char, [95 /*'_'*/]));
    };
    $p.LowerCaseFirstCharAndRemoveUnderscorePrefix = function Utils_LowerCaseFirstCharAndRemoveUnderscorePrefix(value) {
        value = this.RemoveUnderscorePrefix(value);
        return this.LowerCaseFirstChar(value);
    };
    $p.CapitaliseFirstCharAndRemoveUnderscorePrefix = function Utils_CapitaliseFirstCharAndRemoveUnderscorePrefix(value) {
        value = this.RemoveUnderscorePrefix(value);
        return this.CapitaliseFirstChar(value);
    };
    $p.LowerCaseFirstChar = function Utils_LowerCaseFirstChar(value) {
        return value.Substring$1(0, 1).toLowerCase() + value.Substring(1);
    };
    $p.CapitaliseFirstChar = function Utils_CapitaliseFirstChar(value) {
        return value.Substring$1(0, 1).toUpperCase() + value.Substring(1);
    };
    $p.GetBooleanAsString = function Utils_GetBooleanAsString(value) {
        if (value)
            return "true";
        return "false";
    };
});
$d.define(Nethereum.Generators.CQS.ContractDeploymentCQSMessageGenerator, Nethereum.Generators.Core.ABIServiceBase, function($t, $p) {
    $t.$ator = function() {
        this.template = null;
    };
    $t.ctor = function ContractDeploymentCQSMessageGenerator() {
        $t.$baseType.ctor.call(this);
        this.template = new Nethereum.Generators.CQS.ContractDeploymentCQSMessageTemplate.ctor();
    };
    $p.GenerateFullClass = function ContractDeploymentCQSMessageGenerator_GenerateFullClass(abi, namespaceName, byteCode, contractName) {
        return this.template.GenerateFullClass(abi, namespaceName, byteCode, contractName);
    };
    $p.GenerateFullClass$1 = function ContractDeploymentCQSMessageGenerator_GenerateFullClass(abi, namespaceName, byteCode, contractName) {
        return this.template.GenerateFullClass(Nethereum.Generators.Core.ABIServiceBase.GetConstructorABI(abi), 
            namespaceName, byteCode, contractName);
    };
    $p.GenerateClass = function ContractDeploymentCQSMessageGenerator_GenerateClass(abi, byteCode, contractName) {
        return this.template.GenerateClass(abi, byteCode, contractName);
    };
    $p.GenerateClass$1 = function ContractDeploymentCQSMessageGenerator_GenerateClass(abi, byteCode, contractName) {
        return this.GenerateClass(Nethereum.Generators.Core.ABIServiceBase.GetConstructorABI(abi), byteCode, 
            contractName);
    };
});
$d.define(Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel, null, function($t, $p) {
    $t.$ator = function() {
        this.commonGenerators = null;
    };
    $t.ctor = function ContractDeploymentCQSMessageModel() {
        $t.$baseType.ctor.call(this);
        this.commonGenerators = new Nethereum.Generators.Core.CommonGenerators.ctor();
    };
    $p.GetContractDeploymentMessageTypeName = function ContractDeploymentCQSMessageModel_GetContractDeploymentMessageTypeName(contractName) {
        return String.Format("{0}Deployment", [this.commonGenerators.GenerateClassName(contractName)]);
    };
    $p.GetContractDeploymentMessageVariableName = function ContractDeploymentCQSMessageModel_GetContractDeploymentMessageVariableName(contractName) {
        return String.Format("{0}Deployment", [this.commonGenerators.GenerateVariableName(contractName)]);
    };
});
$d.define(Nethereum.Generators.CQS.ContractDeploymentCQSMessageTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this._parameterABIFunctionDTOTemplate = null;
        this._contractDeploymentCQSMessageModel = null;
    };
    $t.ctor = function ContractDeploymentCQSMessageTemplate() {
        $t.$baseType.ctor.call(this);
        this._parameterABIFunctionDTOTemplate = new Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate.ctor();
        this._contractDeploymentCQSMessageModel = new Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel.ctor();
    };
    $p.GenerateFullClass = function ContractDeploymentCQSMessageTemplate_GenerateFullClass(constructorABI, namespaceName, byteCode, contractName) {
        return String.Format("using System;\r\nusing System.Threading.Tasks;\r\nusing System.Numerics;\r\nusing Nethereum.Hex.HexTypes;\r\nusing Nethereum.ABI.FunctionEncoding.Attributes;\r\nnamespace {0}\r\n{{\r\n{1}\r\n}}\r\n", 
            [namespaceName, this.GenerateClass(constructorABI, byteCode, contractName)]);
    };
    $p.GenerateClass = function ContractDeploymentCQSMessageTemplate_GenerateClass(constructorABI, byteCode, contractName) {
        var typeName = this._contractDeploymentCQSMessageModel.GetContractDeploymentMessageTypeName(contractName);
        return String.Format("{0}public class {1}:ContractDeploymentMessage\r\n{2}{{\r\n{3}\r\n{4}public static string BYTECODE = \"{5}\";\r\n{6}\r\n{7}public {8}():base(BYTECODE)\r\n{9}{{\r\n{10}}}\r\n{11}\r\n{12}public {13}(string byteCode):base(byteCode)\r\n{14}{{\r\n{15}}}\r\n{16}\r\n{17}\r\n{18}}}", 
            [Nethereum.Generators.Core.SpaceUtils().OneTab, typeName, Nethereum.Generators.Core.SpaceUtils().OneTab, 
                Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                byteCode, Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                typeName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                typeName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().TwoTabs, this._parameterABIFunctionDTOTemplate.GenerateAllProperties(constructorABI.get_InputParameters()), 
                Nethereum.Generators.Core.SpaceUtils().OneTab]);
    };
});
$d.define(Nethereum.Generators.CQS.FunctionCQSMessageGenerator, Nethereum.Generators.Core.ABIServiceBase, function($t, $p) {
    $t.$ator = function() {
        this.template = null;
    };
    $t.ctor = function FunctionCQSMessageGenerator() {
        $t.$baseType.ctor.call(this);
        this.template = new Nethereum.Generators.CQS.FunctionCQSMessageTemplate.ctor();
    };
    $p.GenerateFullClass = function FunctionCQSMessageGenerator_GenerateFullClass(abi, namespaceName, namespaceFunctionOutput) {
        return this.template.GenerateFullClass(abi, namespaceName, namespaceFunctionOutput);
    };
    $p.GenerateFullClass$1 = function FunctionCQSMessageGenerator_GenerateFullClass(abi, namespaceName, namespaceFunctionOutput) {
        return this.template.GenerateFullClass(Nethereum.Generators.Core.ABIServiceBase.GetFirstFunction(abi), 
            namespaceName, namespaceFunctionOutput);
    };
    $p.GenerateClass = function FunctionCQSMessageGenerator_GenerateClass(abi) {
        return this.template.GenerateClass(abi);
    };
    $p.GenerateClass$1 = function FunctionCQSMessageGenerator_GenerateClass(abi) {
        return this.GenerateClass(Nethereum.Generators.Core.ABIServiceBase.GetFirstFunction(abi));
    };
});
$d.define(Nethereum.Generators.CQS.FunctionCQSMessageModel, null, function($t, $p) {
    $t.$ator = function() {
        this.commonGenerators = null;
    };
    $t.ctor = function FunctionCQSMessageModel() {
        $t.$baseType.ctor.call(this);
        this.commonGenerators = new Nethereum.Generators.Core.CommonGenerators.ctor();
    };
    $p.GetFunctionMessageTypeName = function FunctionCQSMessageModel_GetFunctionMessageTypeName(functionABI) {
        return this.GetFunctionMessageTypeName$1(functionABI.get_Name());
    };
    $p.GetFunctionMessageTypeName$1 = function FunctionCQSMessageModel_GetFunctionMessageTypeName(functionName) {
        return String.Format("{0}Function", [this.commonGenerators.GenerateClassName(functionName)]);
    };
    $p.GetFunctionMessageVariableName = function FunctionCQSMessageModel_GetFunctionMessageVariableName(functionABI) {
        return this.GetFunctionMessageVariableName$1(functionABI.get_Name());
    };
    $p.GetFunctionMessageVariableName$1 = function FunctionCQSMessageModel_GetFunctionMessageVariableName(functionName) {
        return String.Format("{0}Function", [this.commonGenerators.GenerateVariableName(functionName)]);
    };
});
$d.define(Nethereum.Generators.CQS.FunctionCQSMessageTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this._parameterABIFunctionDTOTemplate = null;
        this._functionOutputDTOModel = null;
        this._functionCQSMessageModel = null;
        this._functionABIModel = null;
    };
    $t.ctor = function FunctionCQSMessageTemplate() {
        $t.$baseType.ctor.call(this);
        this._parameterABIFunctionDTOTemplate = new Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate.ctor();
        this._functionOutputDTOModel = new Nethereum.Generators.DTOs.FunctionOutputDTOModel.ctor();
        this._functionCQSMessageModel = new Nethereum.Generators.CQS.FunctionCQSMessageModel.ctor();
        this._functionABIModel = new Nethereum.Generators.Core.FunctionABIModel.ctor();
    };
    $p.GenerateFullClass = function FunctionCQSMessageTemplate_GenerateFullClass(functionABI, namespaceName, namespaceFunctionOutput) {
        return String.Format("using System;\r\nusing System.Threading.Tasks;\r\nusing System.Numerics;\r\nusing Nethereum.Hex.HexTypes;\r\nusing Nethereum.ABI.FunctionEncoding.Attributes;\r\nusing {0};\r\nnamespace {1}\r\n{{\r\n{2}\r\n}}\r\n", 
            [namespaceFunctionOutput, namespaceName, this.GenerateClass(functionABI)]);
    };
    $p.GenerateClass = function FunctionCQSMessageTemplate_GenerateClass(functionABI) {
        var header = "";
        if (this._functionABIModel.IsMultipleOutput(functionABI)) {
            header = String.Format("{0}[Function(\"{1}\", typeof({2}))]", [Nethereum.Generators.Core.SpaceUtils().OneTab, 
                functionABI.get_Name(), this._functionOutputDTOModel.GetFunctionOutputTypeName(functionABI)]);
        }

        if (this._functionABIModel.IsSingleOutput(functionABI)) {
            header = String.Format("{0}[Function(\"{1}\", \"{2}\"))]", [Nethereum.Generators.Core.SpaceUtils().OneTab, 
                functionABI.get_Name(), this._functionABIModel.GetSingleAbiReturnType(functionABI)]);
        }

        if (this._functionABIModel.HasNoReturn(functionABI)) {
            header = String.Format("{0}[Function(\"{1}\"]", [Nethereum.Generators.Core.SpaceUtils().OneTab, 
                functionABI.get_Name()]);
        }

        return String.Format("{0}\r\n{1}public class {2}:ContractMessage\r\n{3}{{\r\n{4}\r\n{5}}}", [header, 
            Nethereum.Generators.Core.SpaceUtils().OneTab, this._functionCQSMessageModel.GetFunctionMessageTypeName(functionABI), 
            Nethereum.Generators.Core.SpaceUtils().OneTab, this._parameterABIFunctionDTOTemplate.GenerateAllProperties(functionABI.get_InputParameters()), 
            Nethereum.Generators.Core.SpaceUtils().OneTab]);
    };
});
$d.define(Nethereum.Generators.DTOs.EventDTOGenerator, Nethereum.Generators.Core.ABIServiceBase, function($t, $p) {
    $t.$ator = function() {
        this.template = null;
    };
    $t.ctor = function EventDTOGenerator() {
        $t.$baseType.ctor.call(this);
        this.template = new Nethereum.Generators.DTOs.EventDTOTemplate.ctor();
    };
    $p.GenerateFullClass = function EventDTOGenerator_GenerateFullClass(abi, namespaceName) {
        return this.template.GenerateFullClass(abi, namespaceName);
    };
    $p.GenerateFullClass$1 = function EventDTOGenerator_GenerateFullClass(abi, namespaceName) {
        return this.template.GenerateFullClass(Nethereum.Generators.Core.ABIServiceBase.GetFirstEvent(abi), 
            namespaceName);
    };
    $p.GenerateClass = function EventDTOGenerator_GenerateClass(abi) {
        return this.template.GenerateClass(abi);
    };
    $p.GenerateClass$1 = function EventDTOGenerator_GenerateClass(abi) {
        return this.GenerateClass(Nethereum.Generators.Core.ABIServiceBase.GetFirstEvent(abi));
    };
});
$d.define(Nethereum.Generators.DTOs.EventDTOModel, null, function($t, $p) {
    $t.$ator = function() {
        this.commonGenerators = null;
    };
    $t.ctor = function EventDTOModel() {
        $t.$baseType.ctor.call(this);
        this.commonGenerators = new Nethereum.Generators.Core.CommonGenerators.ctor();
    };
    $p.GetEventABIOutputTypeName = function EventDTOModel_GetEventABIOutputTypeName(eventABI) {
        return this.GetEventABIOutputTypeName$1(eventABI.get_Name());
    };
    $p.GetEventABIOutputTypeName$1 = function EventDTOModel_GetEventABIOutputTypeName(eventName) {
        return String.Format("{0}EventDTO", [this.commonGenerators.GenerateClassName(eventName)]);
    };
    $p.CanGenerateOutputDTO = function EventDTOModel_CanGenerateOutputDTO(eventABI) {
        return eventABI.get_InputParameters() != null && eventABI.get_InputParameters().length > 0;
    };
});
$d.define(Nethereum.Generators.DTOs.EventDTOTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this._parameterABIEventDTOTemplate = null;
        this._eventDTOModel = null;
    };
    $t.ctor = function EventDTOTemplate() {
        $t.$baseType.ctor.call(this);
        this._parameterABIEventDTOTemplate = new Nethereum.Generators.DTOs.ParameterABIEventDTOTemplate.ctor();
        this._eventDTOModel = new Nethereum.Generators.DTOs.EventDTOModel.ctor();
    };
    $p.GenerateFullClass = function EventDTOTemplate_GenerateFullClass(eventABI, namespaceName) {
        return String.Format("using System;\r\nusing System.Threading.Tasks;\r\nusing System.Numerics;\r\nusing Nethereum.Hex.HexTypes;\r\nusing Nethereum.ABI.FunctionEncoding.Attributes;\r\nnamespace {0}\r\n{{\r\n{1}\r\n}}\r\n", 
            [namespaceName, this.GenerateClass(eventABI)]);
    };
    $p.GenerateClass = function EventDTOTemplate_GenerateClass(eventABI) {
        if (this._eventDTOModel.CanGenerateOutputDTO(eventABI)) {
            return String.Format("{0}[Event(\"{1}\")]\r\n{2}public class {3}\r\n{4}{{\r\n{5}\r\n{6}}}", 
                [Nethereum.Generators.Core.SpaceUtils().OneTab, eventABI.get_Name(), Nethereum.Generators.Core.SpaceUtils().OneTab, 
                    this._eventDTOModel.GetEventABIOutputTypeName(eventABI), Nethereum.Generators.Core.SpaceUtils().OneTab, 
                    this._parameterABIEventDTOTemplate.GenerateAllProperties(eventABI.get_InputParameters()), 
                    Nethereum.Generators.Core.SpaceUtils().OneTab]);
        }
        return null;
    };
});
$d.define(Nethereum.Generators.DTOs.FunctionOutputDTOGenerator, Nethereum.Generators.Core.ABIServiceBase, function($t, $p) {
    $t.$ator = function() {
        this.template = null;
    };
    $t.ctor = function FunctionOutputDTOGenerator() {
        $t.$baseType.ctor.call(this);
        this.template = new Nethereum.Generators.DTOs.FunctionOutputDTOTemplate.ctor();
    };
    $p.GenerateFullClass = function FunctionOutputDTOGenerator_GenerateFullClass(abi, namespaceName) {
        return this.template.GenerateFullClass(abi, namespaceName);
    };
    $p.GenerateFullClass$1 = function FunctionOutputDTOGenerator_GenerateFullClass(abi, namespaceName) {
        return this.template.GenerateFullClass(Nethereum.Generators.Core.ABIServiceBase.GetFirstFunction(abi), 
            namespaceName);
    };
    $p.GenerateClass = function FunctionOutputDTOGenerator_GenerateClass(abi) {
        return this.template.GenerateClass(abi);
    };
    $p.GenerateClass$1 = function FunctionOutputDTOGenerator_GenerateClass(abi) {
        return this.GenerateClass(Nethereum.Generators.Core.ABIServiceBase.GetFirstFunction(abi));
    };
});
$d.define(Nethereum.Generators.DTOs.FunctionOutputDTOModel, null, function($t, $p) {
    $t.$ator = function() {
        this.commonGenerators = null;
    };
    $t.ctor = function FunctionOutputDTOModel() {
        $t.$baseType.ctor.call(this);
        this.commonGenerators = new Nethereum.Generators.Core.CommonGenerators.ctor();
    };
    $p.GetFunctionOutputTypeName = function FunctionOutputDTOModel_GetFunctionOutputTypeName(functionABI) {
        return this.GetFunctionOutputTypeName$1(functionABI.get_Name());
    };
    $p.GetFunctionOutputTypeName$1 = function FunctionOutputDTOModel_GetFunctionOutputTypeName(functionName) {
        return String.Format("{0}OutputDTO", [this.commonGenerators.GenerateClassName(functionName)]);
    };
    $p.CanGenerateOutputDTO = function FunctionOutputDTOModel_CanGenerateOutputDTO(functionABI) {
        return functionABI.get_OutputParameters() != null && functionABI.get_OutputParameters().length > 0 && functionABI.get_Constant();
    };
});
$d.define(Nethereum.Generators.DTOs.FunctionOutputDTOTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this._parameterABIFunctionDTOTemplate = null;
        this._functionOutputDTOModel = null;
    };
    $t.ctor = function FunctionOutputDTOTemplate() {
        $t.$baseType.ctor.call(this);
        this._parameterABIFunctionDTOTemplate = new Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate.ctor();
        this._functionOutputDTOModel = new Nethereum.Generators.DTOs.FunctionOutputDTOModel.ctor();
    };
    $p.GenerateFullClass = function FunctionOutputDTOTemplate_GenerateFullClass(functionABI, namespaceName) {
        return String.Format("using System;\r\nusing System.Threading.Tasks;\r\nusing System.Numerics;\r\nusing Nethereum.Hex.HexTypes;\r\nusing Nethereum.ABI.FunctionEncoding.Attributes;\r\nnamespace {0}\r\n{{\r\n{1}\r\n}}\r\n", 
            [namespaceName, this.GenerateClass(functionABI)]);
    };
    $p.GenerateClass = function FunctionOutputDTOTemplate_GenerateClass(functionABI) {
        if (this._functionOutputDTOModel.CanGenerateOutputDTO(functionABI)) {
            return String.Format("{0}[FunctionOutput]\r\n{1}public class {2}\r\n{3}{{\r\n{4}\r\n{5}}}", 
                [Nethereum.Generators.Core.SpaceUtils().OneTab, Nethereum.Generators.Core.SpaceUtils().OneTab, 
                    this._functionOutputDTOModel.GetFunctionOutputTypeName(functionABI), Nethereum.Generators.Core.SpaceUtils().OneTab, 
                    this._parameterABIFunctionDTOTemplate.GenerateAllProperties(functionABI.get_OutputParameters()), 
                    Nethereum.Generators.Core.SpaceUtils().OneTab]);
        }
        return null;
    };
});
$d.define(Nethereum.Generators.DTOs.ParameterABIEventDTOTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this.parameterModel = null;
        this.utils = null;
    };
    $t.ctor = function ParameterABIEventDTOTemplate() {
        $t.$baseType.ctor.call(this);
        this.parameterModel = new Nethereum.Generators.Core.ParameterABIModel.ctor();
        this.utils = new Nethereum.Generators.Core.Utils.ctor();
    };
    $p.GenerateAllProperties = function ParameterABIEventDTOTemplate_GenerateAllProperties(parameters) {
        return String.Join$1(String, System.Environment().NewLine, System.Linq.Enumerable.Select(Nethereum.Generators.Model.Parameter, 
            String, parameters, $d.delegate(this.GenerateProperty, this)));
    };
    $p.GenerateProperty = function ParameterABIEventDTOTemplate_GenerateProperty(parameter) {
        return String.Format("{0}[Parameter(\"{1}\", \"{2}\", {3}, {4} )]\r\n{5}public {6} {7} {{get; set;}}", 
            [Nethereum.Generators.Core.SpaceUtils().TwoTabs, parameter.get_Type(), parameter.get_Name(), 
                parameter.get_Order(), this.utils.GetBooleanAsString(parameter.get_Indexed()), Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                this.parameterModel.GetParameterCSharpOutputMapType(parameter), this.parameterModel.GetParameterPropertyName(parameter)]);
    };
});
$d.define(Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this.parameterModel = null;
    };
    $t.ctor = function ParameterABIFunctionDTOTemplate() {
        $t.$baseType.ctor.call(this);
        this.parameterModel = new Nethereum.Generators.Core.ParameterABIModel.ctor();
    };
    $p.GenerateAllProperties = function ParameterABIFunctionDTOTemplate_GenerateAllProperties(parameters) {
        return String.Join$1(String, System.Environment().NewLine, System.Linq.Enumerable.Select(Nethereum.Generators.Model.Parameter, 
            String, parameters, $d.delegate(this.GenerateProperty, this)));
    };
    $p.GenerateProperty = function ParameterABIFunctionDTOTemplate_GenerateProperty(parameter) {
        return String.Format("{0}[Parameter(\"{1}\", \"{2}\", {3})]\r\n{4}public {5} {6} {{get; set;}}", 
            [Nethereum.Generators.Core.SpaceUtils().TwoTabs, parameter.get_Type(), parameter.get_Name(), 
                parameter.get_Order(), Nethereum.Generators.Core.SpaceUtils().TwoTabs, this.parameterModel.GetParameterCSharpOutputMapType(parameter), 
                this.parameterModel.GetParameterPropertyName(parameter)]);
    };
});
$d.define(Nethereum.Generators.Model.ConstructorABI, null, function($t, $p) {
    $t.$ator = function() {
        this.InputParameters = null;
    };
    $t.ctor = function ConstructorABI() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_InputParameters = function ConstructorABI_get_InputParameters() { return this.InputParameters; };
    $p.set_InputParameters = function ConstructorABI_set_InputParameters(value) { this.InputParameters = value;return value; };
});
$d.define(Nethereum.Generators.Model.ContractABI, null, function($t, $p) {
    $t.$ator = function() {
        this.Functions = null;
        this.Constructor = null;
        this.Events = null;
    };
    $t.ctor = function ContractABI() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_Functions = function ContractABI_get_Functions() { return this.Functions; };
    $p.set_Functions = function ContractABI_set_Functions(value) { this.Functions = value;return value; };
    $p.get_Constructor = function ContractABI_get_Constructor() { return this.Constructor; };
    $p.set_Constructor = function ContractABI_set_Constructor(value) { this.Constructor = value;return value; };
    $p.get_Events = function ContractABI_get_Events() { return this.Events; };
    $p.set_Events = function ContractABI_set_Events(value) { this.Events = value;return value; };
});
$d.define(Nethereum.Generators.Model.EventABI, null, function($t, $p) {
    $t.$ator = function() {
        this.Name = null;
        this.InputParameters = null;
    };
    $t.ctor = function EventABI(name) {
        $t.$baseType.ctor.call(this);
        this.Name = name;
    };
    $p.get_Name = function EventABI_get_Name() { return this.Name; };
    $p.get_InputParameters = function EventABI_get_InputParameters() { return this.InputParameters; };
    $p.set_InputParameters = function EventABI_set_InputParameters(value) { this.InputParameters = value;return value; };
});
$d.define(Nethereum.Generators.Model.FunctionABI, null, function($t, $p) {
    $t.$ator = function() {
        this.Serpent = false;
        this.Constant = false;
        this.Name = null;
        this.InputParameters = null;
        this.OutputParameters = null;
    };
    $t.ctor = function FunctionABI(name, constant, serpent) {
        $t.$baseType.ctor.call(this);
        this.Name = name;
        this.set_Serpent(serpent);
        this.set_Constant(constant);
    };
    $p.get_Serpent = function FunctionABI_get_Serpent() { return this.Serpent; };
    $p.set_Serpent = function FunctionABI_set_Serpent(value) { this.Serpent = value;return value; };
    $p.get_Constant = function FunctionABI_get_Constant() { return this.Constant; };
    $p.set_Constant = function FunctionABI_set_Constant(value) { this.Constant = value;return value; };
    $p.get_Name = function FunctionABI_get_Name() { return this.Name; };
    $p.get_InputParameters = function FunctionABI_get_InputParameters() { return this.InputParameters; };
    $p.set_InputParameters = function FunctionABI_set_InputParameters(value) { this.InputParameters = value;return value; };
    $p.get_OutputParameters = function FunctionABI_get_OutputParameters() { return this.OutputParameters; };
    $p.set_OutputParameters = function FunctionABI_set_OutputParameters(value) { this.OutputParameters = value;return value; };
});
$d.define(Nethereum.Generators.Model.Parameter, null, function($t, $p) {
    $t.$ator = function() {
        this.Name = null;
        this.Type = null;
        this.Order = 0;
        this.Indexed = false;
        this.SerpentSignature = null;
    };
    $t.ctor$1 = function Parameter(type, name, order, serpentSignature) {
        $t.$baseType.ctor.call(this);
        this.set_Name(name);
        this.set_Type(type);
        this.set_Order(order);
        this.set_SerpentSignature(serpentSignature);
    };
    $t.ctor = function Parameter(type, order) {
        $t.ctor$1.call(this, type, null, order, null);
    };
    $p.get_Name = function Parameter_get_Name() { return this.Name; };
    $p.set_Name = function Parameter_set_Name(value) { this.Name = value;return value; };
    $p.get_Type = function Parameter_get_Type() { return this.Type; };
    $p.set_Type = function Parameter_set_Type(value) { this.Type = value;return value; };
    $p.get_Order = function Parameter_get_Order() { return this.Order; };
    $p.set_Order = function Parameter_set_Order(value) { this.Order = value;return value; };
    $p.get_Indexed = function Parameter_get_Indexed() { return this.Indexed; };
    $p.set_Indexed = function Parameter_set_Indexed(value) { this.Indexed = value;return value; };
    $p.get_SerpentSignature = function Parameter_get_SerpentSignature() { return this.SerpentSignature; };
    $p.set_SerpentSignature = function Parameter_set_SerpentSignature(value) { this.SerpentSignature = value;return value; };
});
$d.define(Nethereum.Generators.Service.ContractDeploymentServiceMethodsTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this._contractDeploymentCQSMessageModel = null;
        this._commonGenerators = null;
    };
    $t.ctor = function ContractDeploymentServiceMethodsTemplate() {
        $t.$baseType.ctor.call(this);
        this._contractDeploymentCQSMessageModel = new Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel.ctor();
        this._commonGenerators = new Nethereum.Generators.Core.CommonGenerators.ctor();
    };
    $p.GenerateMethods = function ContractDeploymentServiceMethodsTemplate_GenerateMethods(contractName, constructor) {
        var messageType = this._contractDeploymentCQSMessageModel.GetContractDeploymentMessageTypeName(contractName);
        var messageVariableName = this._contractDeploymentCQSMessageModel.GetContractDeploymentMessageVariableName(contractName);

        var sendRequestReceipt = String.Format("{0}public Task<TransactionReceipt> DeployContractAndWaitForReceiptAsync(Web3 web3, {1} {2}, CancellationTokenSource cancellationTokenSource = null)\r\n{3}{{\r\n{4} web3.Eth.GetContractDeploymentHandler<{5}>().SendRequestAndWaitForReceiptAsync({6}, cancellationTokenSource);\r\n{7}}}", 
            [Nethereum.Generators.Core.SpaceUtils().TwoTabs, messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().ThreeTabs, messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);


        var sendRequest = String.Format("{0}public Task<string> DeployContractAsync(Web3 web3, {1} {2})\r\n{3}{{\r\n{4} web3.Eth.GetContractDeploymentHandler<{5}>().SendRequestAsync({6});\r\n{7}}}", 
            [Nethereum.Generators.Core.SpaceUtils().TwoTabs, messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().ThreeTabs, messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);

        var sendRequestContract = String.Format("{0}public Task<string> DeployContractAndGetServiceAsyc(Web3 web3, {1} {2}, CancellationTokenSource cancellationTokenSource = null)\r\n{3}{{\r\n{4} web3.Eth.GetContractDeploymentHandler<{5}>().SendRequestAsync({6});\r\n{7}}}", 
            [Nethereum.Generators.Core.SpaceUtils().TwoTabs, messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().ThreeTabs, messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);

        return null;
    };
});
$d.define(Nethereum.Generators.Service.FunctionServiceMethodTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this._functionOutputDTOModel = null;
        this._functionCQSMessageModel = null;
        this._commonGenerators = null;
        this._abiTypeToCSharpType = null;
    };
    $t.ctor = function FunctionServiceMethodTemplate() {
        $t.$baseType.ctor.call(this);
        this._functionOutputDTOModel = new Nethereum.Generators.DTOs.FunctionOutputDTOModel.ctor();
        this._commonGenerators = new Nethereum.Generators.Core.CommonGenerators.ctor();
        this._functionCQSMessageModel = new Nethereum.Generators.CQS.FunctionCQSMessageModel.ctor();
        this._abiTypeToCSharpType = new Nethereum.Generators.Core.ABITypeToCSharpType.ctor();
    };
    $p.GenerateMethod = function FunctionServiceMethodTemplate_GenerateMethod(functionABI) {
        var messageType = this._functionCQSMessageModel.GetFunctionMessageTypeName(functionABI);
        var messageVariableName = this._functionCQSMessageModel.GetFunctionMessageVariableName(functionABI);

        if (this._functionOutputDTOModel.CanGenerateOutputDTO(functionABI)) {

            var functionOutputDTOType = this._functionOutputDTOModel.GetFunctionOutputTypeName(functionABI);
            return String.Format("{0}public Task<{1}> {2}QueryAsync({3} {4}, BlockParameter blockParameter = null)\r\n{5}{{\r\n{6}return ContractHandler.QueryDeserializingToObjectAsync<{7}, {8}>({9}, blockParameter);\r\n{10}}}", 
                [Nethereum.Generators.Core.SpaceUtils().TwoTabs, functionOutputDTOType, this._commonGenerators.GenerateClassName(functionABI.get_Name()), 
                    messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                    Nethereum.Generators.Core.SpaceUtils().ThreeTabs, messageType, functionOutputDTOType, 
                    messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);
        }

        if (functionABI.get_OutputParameters() != null && functionABI.get_OutputParameters().length == 1 && functionABI.get_Constant()) {
            var type = this._abiTypeToCSharpType.GetTypeMap(functionABI.get_OutputParameters()[0].get_Type(), 
                false);

            return String.Format("{0}public Task<{1}> {2}QueryAsync({3} {4}, BlockParameter blockParameter = null)\r\n{5}{{\r\n{6}return ContractHandler.QueryAsync<{7}, {8}>({9}, blockParameter);\r\n{10}}}", 
                [Nethereum.Generators.Core.SpaceUtils().TwoTabs, type, this._commonGenerators.GenerateClassName(functionABI.get_Name()), 
                    messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                    Nethereum.Generators.Core.SpaceUtils().ThreeTabs, messageType, type, messageVariableName, 
                    Nethereum.Generators.Core.SpaceUtils().TwoTabs]);
        }

        if (functionABI.get_Constant() == false || (functionABI.get_OutputParameters() == null || functionABI.get_OutputParameters().length == 0)) {

            var transactionRequest = String.Format("{0}public Task<string> {1}RequestAsync({2} {3})\r\n{4}{{\r\n{5} return ContractHandler.SendRequestAsync({6});\r\n{7}}}", 
                [Nethereum.Generators.Core.SpaceUtils().TwoTabs, this._commonGenerators.GenerateClassName(functionABI.get_Name()), 
                    messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                    Nethereum.Generators.Core.SpaceUtils().ThreeTabs, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);

            var transactionRequestAndReceipt = String.Format("{0}public Task<TransactionReceipt> {1}RequestAndWaitForReceiptAsync({2} {3}, CancellationTokenSource cancellationToken = null)\r\n{4}{{\r\n{5} return ContractHandler.SendRequestAndWaitForReceiptAsync({6}, cancellationToken);\r\n{7}}}", 
                [Nethereum.Generators.Core.SpaceUtils().TwoTabs, this._commonGenerators.GenerateClassName(functionABI.get_Name()), 
                    messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                    Nethereum.Generators.Core.SpaceUtils().ThreeTabs, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);

            return transactionRequest + System.Environment().NewLine + transactionRequestAndReceipt;
        }

        return null;
    };
});
return $asm;
})();
//# sourceMappingURL=Nethereum.Generators.DuoCode.js.map
