/*!
* Nethereum.Generators.DuoCode, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
*
* Generated by DuoCode Compiler 3.0.1654.0 [Trial]
*/
var mscorlib = require("./mscorlib");
module.exports = (function Nethereum_Generators_DuoCode(mscorlib) {
"use strict";
var $asm = {
    fullName: "Nethereum.Generators.DuoCode",
    anonymousTypes: [],
    types: [],
    getAttrs: function() { return [new DuoCode.Runtime.CompilerAttribute.ctor("3.0.1654.0")]; }
};
var $g = (typeof(global) !== "undefined" ? global : (typeof(window) !== "undefined" ? window : self));
var Nethereum = $g.Nethereum = $g.Nethereum || {};
Nethereum.Generators = Nethereum.Generators || {};
Nethereum.Generators.Core = Nethereum.Generators.Core || {};
Nethereum.Generators.CQS = Nethereum.Generators.CQS || {};
Nethereum.Generators.DTOs = Nethereum.Generators.DTOs || {};
Nethereum.Generators.Model = Nethereum.Generators.Model || {};
Nethereum.Generators.Service = Nethereum.Generators.Service || {};
var $d = DuoCode.Runtime;
$d.$assemblies["Nethereum.Generators.DuoCode"] = $asm;
Nethereum.Generators.ContractProjectGenerator = $d.declare("Nethereum.Generators.ContractProjectGenerator", 
    0, $asm);
Nethereum.Generators.CsharpLibraryGenerator = $d.declare("Nethereum.Generators.CsharpLibraryGenerator", 
    0, $asm);
Nethereum.Generators.Core.ABITypeToCSharpType = $d.declare("Nethereum.Generators.Core.ABITypeToCSharpType", 
    0, $asm);
Nethereum.Generators.Core.ClassGeneratorBase$2 = $d.declare("Nethereum.Generators.Core.ClassGeneratorBase`2", 
    256, $asm);
Nethereum.Generators.Core.CommonGenerators = $d.declare("Nethereum.Generators.Core.CommonGenerators", 
    0, $asm);
Nethereum.Generators.Core.FunctionABIModel = $d.declare("Nethereum.Generators.Core.FunctionABIModel", 
    0, $asm);
Nethereum.Generators.Core.GeneratedFile = $d.declare("Nethereum.Generators.Core.GeneratedFile", 0, $asm);
Nethereum.Generators.Core.ParameterABIModel = $d.declare("Nethereum.Generators.Core.ParameterABIModel", 
    0, $asm);
Nethereum.Generators.Core.SpaceUtils = $d.declare("Nethereum.Generators.Core.SpaceUtils", 0, $asm);
Nethereum.Generators.Core.TypeMessageModel = $d.declare("Nethereum.Generators.Core.TypeMessageModel", 
    0, $asm);
Nethereum.Generators.Core.Utils = $d.declare("Nethereum.Generators.Core.Utils", 0, $asm);
Nethereum.Generators.CQS.ContractDeploymentCQSMessageGenerator = $d.declare("Nethereum.Generators.CQS.ContractDeploymentCQSMessageGenerator", 
    0, $asm);
Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel = $d.declare("Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel", 
    0, $asm);
Nethereum.Generators.CQS.ContractDeploymentCQSMessageTemplate = $d.declare("Nethereum.Generators.CQS.ContractDeploymentCQSMessageTemplate", 
    0, $asm);
Nethereum.Generators.CQS.FunctionCQSMessageGenerator = $d.declare("Nethereum.Generators.CQS.FunctionCQSMessageGenerator", 
    0, $asm);
Nethereum.Generators.CQS.FunctionCQSMessageModel = $d.declare("Nethereum.Generators.CQS.FunctionCQSMessageModel", 
    0, $asm);
Nethereum.Generators.CQS.FunctionCQSMessageTemplate = $d.declare("Nethereum.Generators.CQS.FunctionCQSMessageTemplate", 
    0, $asm);
Nethereum.Generators.DTOs.EventDTOGenerator = $d.declare("Nethereum.Generators.DTOs.EventDTOGenerator", 
    0, $asm);
Nethereum.Generators.DTOs.EventDTOModel = $d.declare("Nethereum.Generators.DTOs.EventDTOModel", 0, $asm);
Nethereum.Generators.DTOs.EventDTOTemplate = $d.declare("Nethereum.Generators.DTOs.EventDTOTemplate", 
    0, $asm);
Nethereum.Generators.DTOs.FunctionOutputDTOGenerator = $d.declare("Nethereum.Generators.DTOs.FunctionOutputDTOGenerator", 
    0, $asm);
Nethereum.Generators.DTOs.FunctionOutputDTOModel = $d.declare("Nethereum.Generators.DTOs.FunctionOutputDTOModel", 
    0, $asm);
Nethereum.Generators.DTOs.FunctionOutputDTOTemplate = $d.declare("Nethereum.Generators.DTOs.FunctionOutputDTOTemplate", 
    0, $asm);
Nethereum.Generators.DTOs.ParameterABIEventDTOTemplate = $d.declare("Nethereum.Generators.DTOs.ParameterABIEventDTOTemplate", 
    0, $asm);
Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate = $d.declare("Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate", 
    0, $asm);
Nethereum.Generators.Model.ConstructorABI = $d.declare("Nethereum.Generators.Model.ConstructorABI", 0, 
    $asm);
Nethereum.Generators.Model.ContractABI = $d.declare("Nethereum.Generators.Model.ContractABI", 0, $asm);
Nethereum.Generators.Model.EventABI = $d.declare("Nethereum.Generators.Model.EventABI", 0, $asm);
Nethereum.Generators.Model.FunctionABI = $d.declare("Nethereum.Generators.Model.FunctionABI", 0, $asm);
Nethereum.Generators.Model.Parameter = $d.declare("Nethereum.Generators.Model.Parameter", 0, $asm);
Nethereum.Generators.Service.ContractDeploymentServiceMethodsTemplate = $d.declare("Nethereum.Generators.Service.ContractDeploymentServiceMethodsTemplate", 
    0, $asm);
Nethereum.Generators.Service.FunctionServiceMethodTemplate = $d.declare("Nethereum.Generators.Service.FunctionServiceMethodTemplate", 
    0, $asm);
Nethereum.Generators.Service.ServiceGenerator = $d.declare("Nethereum.Generators.Service.ServiceGenerator", 
    0, $asm);
Nethereum.Generators.Service.ServiceModel = $d.declare("Nethereum.Generators.Service.ServiceModel", 0, 
    $asm);
Nethereum.Generators.Service.ServiceTemplate = $d.declare("Nethereum.Generators.Service.ServiceTemplate", 
    0, $asm);
$d.define(Nethereum.Generators.ContractProjectGenerator, null, function($t, $p) {
    $t.$ator = function() {
        this.ContractABI = null;
        this.ContractName = null;
        this.ByteCode = null;
        this.BaseNamespace = null;
        this.ServiceNamespace = null;
        this.CQSNamespace = null;
        this.DTONamespace = null;
        this.BaseOutputPath = null;
        this.PathDelimiter = null;
    };
    $p.get_ContractABI = function ContractProjectGenerator_get_ContractABI() { return this.ContractABI; };
    $p.get_ContractName = function ContractProjectGenerator_get_ContractName() { return this.ContractName; };
    $p.get_ByteCode = function ContractProjectGenerator_get_ByteCode() { return this.ByteCode; };
    $p.get_BaseNamespace = function ContractProjectGenerator_get_BaseNamespace() { return this.BaseNamespace; };
    $p.get_ServiceNamespace = function ContractProjectGenerator_get_ServiceNamespace() { return this.ServiceNamespace; };
    $p.get_CQSNamespace = function ContractProjectGenerator_get_CQSNamespace() { return this.CQSNamespace; };
    $p.get_DTONamespace = function ContractProjectGenerator_get_DTONamespace() { return this.DTONamespace; };
    $p.get_BaseOutputPath = function ContractProjectGenerator_get_BaseOutputPath() { return this.BaseOutputPath; };
    $p.get_PathDelimiter = function ContractProjectGenerator_get_PathDelimiter() { return this.PathDelimiter; };
    $t.ctor = function ContractProjectGenerator(contractABI, contractName, byteCode, baseNamespace, serviceNamespace, cqsNamespace, dtoNamespace, baseOutputPath, pathDelimiter) {
        $t.$baseType.ctor.call(this);
        this.ContractABI = contractABI;
        this.ContractName = contractName;
        this.ByteCode = byteCode;
        this.BaseNamespace = baseNamespace;
        this.ServiceNamespace = serviceNamespace;
        this.CQSNamespace = cqsNamespace;
        this.DTONamespace = dtoNamespace;
        this.BaseOutputPath = baseOutputPath;
        this.PathDelimiter = pathDelimiter;
    };
    $p.GenerateAll = function ContractProjectGenerator_GenerateAll() {
        var generated = new (System.Collections.Generic.List$1(Nethereum.Generators.Core.GeneratedFile, 
            64040).ctor)();
        generated.AddRange(this.GenerateAllCQSMessages());
        generated.AddRange(this.GenerateAllEventDTOs());
        generated.AddRange(this.GenerateAllFunctionDTOs());
        generated.Add(this.GenerateService());
        return generated.ToArray();
    };
    $p.GenerateService = function ContractProjectGenerator_GenerateService() {
        var dtoFullNamespace = this.GetFullNamespace(this.get_DTONamespace());
        var cqsFullNamespace = this.GetFullNamespace(this.get_CQSNamespace());
        var serviceFullNamespace = this.GetFullNamespace(this.get_ServiceNamespace());
        var serviceFullPath = this.GetFullPath(this.get_ServiceNamespace());
        var serviceGenerator = new Nethereum.Generators.Service.ServiceGenerator.ctor(this.get_ContractABI(), 
            this.get_ContractName(), this.get_ByteCode(), serviceFullNamespace, cqsFullNamespace, dtoFullNamespace);
        return serviceGenerator.GenerateFileContent$1(serviceFullPath);
    };
    $p.GenerateAllCQSMessages = function ContractProjectGenerator_GenerateAllCQSMessages() {
        var generated = new (System.Collections.Generic.List$1(Nethereum.Generators.Core.GeneratedFile, 
            64040).ctor)();
        generated.Add(this.GeneratCQSMessageDeployment());
        generated.AddRange(this.GeneratCQSFunctionMessages());
        return generated;
    };
    $p.GenerateAllFunctionDTOs = function ContractProjectGenerator_GenerateAllFunctionDTOs() {
        var dtoFullNamespace = this.GetFullNamespace(this.get_DTONamespace());
        var dtoFullPath = this.GetFullPath(this.get_DTONamespace());
        var generated = new (System.Collections.Generic.List$1(Nethereum.Generators.Core.GeneratedFile, 
            64040).ctor)();
        for (var $i = 0, $a = this.get_ContractABI().get_Functions(), $length = $a.length; $i < $length; $i++) {
            var functionABI = $a[$i];
            var functionOutputDTOGenerator = new Nethereum.Generators.DTOs.FunctionOutputDTOGenerator.ctor(functionABI, 
                dtoFullNamespace);
            generated.Add(functionOutputDTOGenerator.GenerateFileContent$1(dtoFullPath));
        }
        return generated;
    };
    $p.GenerateAllEventDTOs = function ContractProjectGenerator_GenerateAllEventDTOs() {
        var dtoFullNamespace = this.GetFullNamespace(this.get_DTONamespace());
        var dtoFullPath = this.GetFullPath(this.get_DTONamespace());
        var generated = new (System.Collections.Generic.List$1(Nethereum.Generators.Core.GeneratedFile, 
            64040).ctor)();
        for (var $i = 0, $a = this.get_ContractABI().get_Events(), $length = $a.length; $i < $length; $i++) {
            var eventABI = $a[$i];
            var cqsGenerator = new Nethereum.Generators.DTOs.EventDTOGenerator.ctor(eventABI, dtoFullNamespace);
            generated.Add(cqsGenerator.GenerateFileContent$1(dtoFullPath));
        }
        return generated;
    };
    $p.GeneratCQSFunctionMessages = function ContractProjectGenerator_GeneratCQSFunctionMessages() {
        var cqsFullNamespace = this.GetFullNamespace(this.get_CQSNamespace());
        var cqsFullPath = this.GetFullPath(this.get_CQSNamespace());
        var dtoFullNamespace = this.GetFullNamespace(this.get_DTONamespace());
        var generated = new (System.Collections.Generic.List$1(Nethereum.Generators.Core.GeneratedFile, 
            64040).ctor)();
        for (var $i = 0, $a = this.get_ContractABI().get_Functions(), $length = $a.length; $i < $length; $i++) {
            var functionAbi = $a[$i];
            var cqsGenerator = new Nethereum.Generators.CQS.FunctionCQSMessageGenerator.ctor(functionAbi, 
                cqsFullNamespace, dtoFullNamespace);
            generated.Add(cqsGenerator.GenerateFileContent$1(cqsFullPath));
        }
        return generated;
    };
    $p.GeneratCQSMessageDeployment = function ContractProjectGenerator_GeneratCQSMessageDeployment() {
        var cqsGenerator = new Nethereum.Generators.CQS.ContractDeploymentCQSMessageGenerator.ctor(this.get_ContractABI().get_Constructor(), 
            this.GetFullNamespace(this.get_CQSNamespace()), this.get_ByteCode(), this.get_ContractName());
        return cqsGenerator.GenerateFileContent$1(this.GetFullPath(this.get_CQSNamespace()));
    };
    $p.GetFullNamespace = function ContractProjectGenerator_GetFullNamespace(namespace) {
        return this.get_BaseNamespace() + "." + namespace;
    };
    $p.GetFullPath = function ContractProjectGenerator_GetFullPath(namespace) {
        return this.get_BaseOutputPath() + this.get_PathDelimiter() + namespace.Replace$1(".", this.get_PathDelimiter());
    };
});
$d.define(Nethereum.Generators.CsharpLibraryGenerator, null, function($t, $p) {
    $t.$ator = function() {
        this.template = String.Format("{0}<Project Sdk=\"Microsoft.NET.Sdk\">\r\n{1}\r\n{2}<PropertyGroup>\r\n{3}<TargetFramework>netstandard2.0</TargetFramework>\r\n{4}</PropertyGroup>\r\n{5}\r\n{6}<ItemGroup>\r\n{7}<PackageReference Include = \"Nethereum.Web3\" Version=\"2.4.0\" />\r\n{8}</ItemGroup>\r\n{9}\r\n{10}</Project>", 
            [Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().OneTab, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().OneTab, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().OneTab, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().OneTab, Nethereum.Generators.Core.SpaceUtils().OneTab, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs]);
        this.ProjectFileName = null;
    };
    $p.get_ProjectFileName = function CsharpLibraryGenerator_get_ProjectFileName() { return this.ProjectFileName; };
    $t.ctor = function CsharpLibraryGenerator(projectFileName) {
        $t.$baseType.ctor.call(this);
        this.ProjectFileName = projectFileName;
    };
    $p.GenerateFileContent = function CsharpLibraryGenerator_GenerateFileContent(outputPath) {
        return new Nethereum.Generators.Core.GeneratedFile.ctor(this.template, this.get_ProjectFileName(), 
            outputPath);
    };
});
$d.define(Nethereum.Generators.Core.ABITypeToCSharpType, null, function($t, $p) {
    $t.ctor = function ABITypeToCSharpType() {
        $t.$baseType.ctor.call(this);
    };
    $p.GetTypeMap = function ABITypeToCSharpType_GetTypeMap(typeName, outputMapType) {
        var indexFirstBracket = typeName.indexOf("[");
        if (indexFirstBracket > -1) {
            var elementTypeName = typeName.Substring$1(0, indexFirstBracket);
            if (outputMapType) {
                return "List<" + this.GetTypeMap(elementTypeName, true) + ">";
            }
            else {
                return this.GetTypeMap(elementTypeName, false) + "[]";
            }
        }
        if ("bool" == typeName) {
            return typeName;
        }
        if (typeName.StartsWith("int")) {
            //default
            if (typeName.length == 3) {
                return "BigInteger";
            }
            var length = System.Int32.Parse(typeName.Substring(3));

            if (length > 64) {
                return "BigInteger";
            }
            if (length <= 64 && length > 32) {
                return "long";
            }
            //ints are in 8 bits
            if (length == 32) {
                return "int";
            }
            if (length == 16) {
                return "short";
            }
            if (length == 8) {
                return "sbyte";
            }
        }
        if (typeName.StartsWith("uint")) {

            if (typeName.length == 4) {
                return "BigInteger";
            }
            var length = System.Int32.Parse(typeName.Substring(4));

            if (length > 64) {
                return "BigInteger";
            }
            if (length <= 64 && length > 32) {
                return "ulong";
            }
            //uints are in 8 bits steps
            if (length == 32) {
                return "uint";
            }
            if (length == 16) {
                return "ushort";
            }
            if (length == 8) {
                return "byte";
            }
        }
        if (typeName == "address") {
            return "string";
        }
        if (typeName == "string") {
            return "string";
        }
        if (typeName == "bytes") {
            return "byte[]";
        }
        if (typeName.StartsWith("bytes")) {
            return "byte[]";
        }
        return null;
    };
});
Nethereum.Generators.Core.IClassTemplate = $d.type("Nethereum.Generators.Core.IClassTemplate", 66, $asm, function($t, $p) {
});
Nethereum.Generators.Core.IClassModel = $d.type("Nethereum.Generators.Core.IClassModel", 66, $asm, function($t, $p) {
});
$d.define(Nethereum.Generators.Core.TypeMessageModel, null, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassModel];
    $t.$ator = function() {
        this.CommonGenerators = null;
        this.Namespace = null;
    };
    $p.get_CommonGenerators = function TypeMessageModel_get_CommonGenerators() { return this.CommonGenerators; };
    $p.set_CommonGenerators = function TypeMessageModel_set_CommonGenerators(value) { this.CommonGenerators = value;return value; };
    $p.get_Namespace = function TypeMessageModel_get_Namespace() { return this.Namespace; };
    $t.ctor = function TypeMessageModel(namespace) {
        $t.$baseType.ctor.call(this);
        this.Namespace = namespace;
        this.set_CommonGenerators(new Nethereum.Generators.Core.CommonGenerators.ctor());
    };
    $p.GetTypeName$1 = function TypeMessageModel_GetTypeName(name) {
        return String.Format("{0}{1}", [this.get_CommonGenerators().GenerateClassName(name), this.GetClassNameSuffix()]);
    };
    $p.GetFileName$1 = function TypeMessageModel_GetFileName(name) {
        return this.GetTypeName$1(name) + ".cs";
    };
    $p.GetVariableName$1 = function TypeMessageModel_GetVariableName(name) {
        return String.Format("{0}{1}", [this.get_CommonGenerators().GenerateVariableName(name), this.GetClassNameSuffix()]);
    };
    $p.GetTypeName = function TypeMessageModel_GetTypeName() {
        return this.GetTypeName$1(this.GetBaseName());
    };
    $p.GetFileName = function TypeMessageModel_GetFileName() {
        return this.GetFileName$1(this.GetBaseName());
    };
    $p.GetVariableName = function TypeMessageModel_GetVariableName() {
        return this.GetVariableName$1(this.GetBaseName());
    };
    $p.Nethereum$Generators$Core$IClassModel$GetTypeName = $p.GetTypeName;
    $p.Nethereum$Generators$Core$IClassModel$GetFileName = $p.GetFileName;
    $p.Nethereum$Generators$Core$IClassModel$GetVariableName = $p.GetVariableName;
    $p.Nethereum$Generators$Core$IClassModel$get_Namespace = $p.get_Namespace;
});
Nethereum.Generators.Core.IGenerator = $d.type("Nethereum.Generators.Core.IGenerator", 66, $asm, function($t, $p) {
});
Nethereum.Generators.Core.IFileGenerator = $d.type("Nethereum.Generators.Core.IFileGenerator", 66, $asm, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IGenerator];
});
$d.define(Nethereum.Generators.Core.ClassGeneratorBase$2, null, function($t, $p, TClassTemplate, TClassModel) {
    $t.$intfs = [Nethereum.Generators.Core.IFileGenerator, Nethereum.Generators.Core.IGenerator];
    $t.$ator = function() {
        this.ClassTemplate = $d.defaultOf(TClassTemplate);
        this.ClassModel = $d.defaultOf(TClassModel);
    };
    $t.ctor = function ClassGeneratorBase$2() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_ClassTemplate = function ClassGeneratorBase$2_get_ClassTemplate() { return this.ClassTemplate; };
    $p.set_ClassTemplate = function ClassGeneratorBase$2_set_ClassTemplate(value) { this.ClassTemplate = value;return value; };
    $p.get_ClassModel = function ClassGeneratorBase$2_get_ClassModel() { return this.ClassModel; };
    $p.set_ClassModel = function ClassGeneratorBase$2_set_ClassModel(value) { this.ClassModel = value;return value; };
    $p.GenerateFileContent$1 = function ClassGeneratorBase$2_GenerateFileContent(outputPath) {
        return new Nethereum.Generators.Core.GeneratedFile.ctor(this.GenerateFileContent(), this.GetFileName(), 
            outputPath);
    };
    $p.GenerateFileContent = function ClassGeneratorBase$2_GenerateFileContent() {
        return this.get_ClassTemplate().Nethereum$Generators$Core$IClassTemplate$GenerateFullClass();
    };
    $p.GetFileName = function ClassGeneratorBase$2_GetFileName() {
        return this.get_ClassModel().GetFileName();
    };
    $p.GenerateClass = function ClassGeneratorBase$2_GenerateClass() {
        return this.get_ClassTemplate().Nethereum$Generators$Core$IClassTemplate$GenerateClass();
    };
    $p.Nethereum$Generators$Core$IFileGenerator$GenerateFileContent$1 = $p.GenerateFileContent$1;
    $p.Nethereum$Generators$Core$IFileGenerator$GenerateFileContent = $p.GenerateFileContent;
    $p.Nethereum$Generators$Core$IFileGenerator$GetFileName = $p.GetFileName;
    $p.Nethereum$Generators$Core$IGenerator$GenerateClass = $p.GenerateClass;
}, [$d.typeParam("TClassTemplate"), $d.typeParam("TClassModel", Nethereum.Generators.Core.TypeMessageModel)]);
$d.define(Nethereum.Generators.Core.CommonGenerators, null, function($t, $p) {
    $t.$ator = function() {
        this.utils = null;
    };
    $t.ctor = function CommonGenerators() {
        $t.$baseType.ctor.call(this);
        this.utils = new Nethereum.Generators.Core.Utils.ctor();
    };
    $p.GenerateVariableName = function CommonGenerators_GenerateVariableName(value) {
        return this.utils.LowerCaseFirstCharAndRemoveUnderscorePrefix(value);
    };
    $p.GeneratePropertyName = function CommonGenerators_GeneratePropertyName(value) {
        return this.utils.CapitaliseFirstCharAndRemoveUnderscorePrefix(value);
    };
    $p.GenerateClassName = function CommonGenerators_GenerateClassName(value) {
        return this.utils.CapitaliseFirstCharAndRemoveUnderscorePrefix(value);
    };
});
$d.define(Nethereum.Generators.Core.FunctionABIModel, null, function($t, $p) {
    $t.$ator = function() {
        this.abiTypeToCSharpType = null;
        this.FunctionABI = null;
    };
    $p.get_FunctionABI = function FunctionABIModel_get_FunctionABI() { return this.FunctionABI; };
    $t.ctor = function FunctionABIModel(functionABI) {
        $t.$baseType.ctor.call(this);
        this.FunctionABI = functionABI;
        this.abiTypeToCSharpType = new Nethereum.Generators.Core.ABITypeToCSharpType.ctor();
    };
    $p.GetSingleOutputGenericReturnType = function FunctionABIModel_GetSingleOutputGenericReturnType() {
        if (this.get_FunctionABI() == null)
            return String.Empty;
        return String.Format("<{0}>", [this.GetSingleOutputReturnType()]);
    };
    $p.GetSingleOutputReturnType = function FunctionABIModel_GetSingleOutputReturnType() {
        if (this.get_FunctionABI().get_OutputParameters() != null && this.get_FunctionABI().get_OutputParameters().length == 1) {
            return this.abiTypeToCSharpType.GetTypeMap(this.get_FunctionABI().get_OutputParameters()[0].get_Type(), 
                true);
        }
        return null;
    };
    $p.GetSingleAbiReturnType = function FunctionABIModel_GetSingleAbiReturnType() {
        if (this.get_FunctionABI().get_OutputParameters() != null && this.get_FunctionABI().get_OutputParameters().length == 1) {
            return this.get_FunctionABI().get_OutputParameters()[0].get_Type();
        }
        return null;
    };
    $p.IsMultipleOutput = function FunctionABIModel_IsMultipleOutput() {
        return this.get_FunctionABI().get_OutputParameters() != null && this.get_FunctionABI().get_OutputParameters().length > 1;
    };
    $p.IsSingleOutput = function FunctionABIModel_IsSingleOutput() {
        return this.get_FunctionABI().get_OutputParameters() != null && this.get_FunctionABI().get_OutputParameters().length == 1;
    };
    $p.HasNoReturn = function FunctionABIModel_HasNoReturn() {
        return this.get_FunctionABI().get_OutputParameters() == null || this.get_FunctionABI().get_OutputParameters().length == 0;
    };
    $p.IsTransaction = function FunctionABIModel_IsTransaction() {
        return this.get_FunctionABI().get_Constant() == false;
    };
});
$d.define(Nethereum.Generators.Core.GeneratedFile, null, function($t, $p) {
    $t.$ator = function() {
        this.GeneratedCode = null;
        this.FileName = null;
        this.OutputFolder = null;
    };
    $p.get_GeneratedCode = function GeneratedFile_get_GeneratedCode() { return this.GeneratedCode; };
    $p.get_FileName = function GeneratedFile_get_FileName() { return this.FileName; };
    $p.get_OutputFolder = function GeneratedFile_get_OutputFolder() { return this.OutputFolder; };
    $t.ctor = function GeneratedFile(generatedCode, fileName, outputFolder) {
        $t.$baseType.ctor.call(this);
        this.GeneratedCode = generatedCode;
        this.FileName = fileName;
        this.OutputFolder = outputFolder;
    };
});
$d.define(Nethereum.Generators.Core.ParameterABIModel, null, function($t, $p) {
    $t.$ator = function() {
        this.commonGenerators = null;
        this.abiTypeToCSharpType = null;
    };
    $t.ctor = function ParameterABIModel() {
        $t.$baseType.ctor.call(this);
        this.commonGenerators = new Nethereum.Generators.Core.CommonGenerators.ctor();
        this.abiTypeToCSharpType = new Nethereum.Generators.Core.ABITypeToCSharpType.ctor();
    };
    $p.GetParameterVariableName$1 = function ParameterABIModel_GetParameterVariableName(name, order) {
        return this.commonGenerators.GenerateVariableName(this.GetParameterName(name, order));
    };
    $p.GetParameterPropertyName = function ParameterABIModel_GetParameterPropertyName(parameter) {
        return this.GetParameterPropertyName$1(parameter.get_Name(), parameter.get_Order());
    };
    $p.GetParameterVariableName = function ParameterABIModel_GetParameterVariableName(parameter) {
        return this.GetParameterVariableName$1(parameter.get_Name(), parameter.get_Order());
    };
    $p.GetParameterPropertyName$1 = function ParameterABIModel_GetParameterPropertyName(name, order) {
        return this.commonGenerators.GeneratePropertyName(this.GetParameterName(name, order));
    };
    $p.GetParameterCSharpOutputMapType = function ParameterABIModel_GetParameterCSharpOutputMapType(parameter) {
        return this.abiTypeToCSharpType.GetTypeMap(parameter.get_Type(), true);
    };
    $p.GetParameterCSharpInputMapType = function ParameterABIModel_GetParameterCSharpInputMapType(parameter) {
        return this.abiTypeToCSharpType.GetTypeMap(parameter.get_Type(), false);
    };
    $p.GetParameterName = function ParameterABIModel_GetParameterName(name, order) {
        if (name != "")
            return name;
        switch (order) {
            case 0:
                return "a";
            case 1:
                return "b";
            case 2:
                return "c";
            case 3:
                return "d";
            case 4:
                return "e";
            case 5:
                return "f";
            case 6:
                return "g";
        }
        return "h";
    };
});
$d.define(Nethereum.Generators.Core.SpaceUtils, null, function($t, $p) {
    $t.cctor = function() {
        $t.NoTabs = "";
        $t.OneTab = "    ";
        $t.TwoTabs = $t().OneTab + $t().OneTab;
        $t.ThreeTabs = $t().OneTab + $t().OneTab + $t().OneTab;
    };
    $t.ctor = function SpaceUtils() {
        $t.$baseType.ctor.call(this);
    };
});
$d.define(Nethereum.Generators.Core.Utils, null, function($t, $p) {
    $t.ctor = function Utils() {
        $t.$baseType.ctor.call(this);
    };
    $p.RemoveUnderscorePrefix = function Utils_RemoveUnderscorePrefix(value) {
        return value.TrimStart($d.array(System.Char, [95 /*'_'*/]));
    };
    $p.LowerCaseFirstCharAndRemoveUnderscorePrefix = function Utils_LowerCaseFirstCharAndRemoveUnderscorePrefix(value) {
        value = this.RemoveUnderscorePrefix(value);
        return this.LowerCaseFirstChar(value);
    };
    $p.CapitaliseFirstCharAndRemoveUnderscorePrefix = function Utils_CapitaliseFirstCharAndRemoveUnderscorePrefix(value) {
        value = this.RemoveUnderscorePrefix(value);
        return this.CapitaliseFirstChar(value);
    };
    $p.LowerCaseFirstChar = function Utils_LowerCaseFirstChar(value) {
        return value.Substring$1(0, 1).toLowerCase() + value.Substring(1);
    };
    $p.CapitaliseFirstChar = function Utils_CapitaliseFirstChar(value) {
        return value.Substring$1(0, 1).toUpperCase() + value.Substring(1);
    };
    $p.GetBooleanAsString = function Utils_GetBooleanAsString(value) {
        if (value)
            return "true";
        return "false";
    };
});
$d.define(Nethereum.Generators.CQS.ContractDeploymentCQSMessageGenerator, Nethereum.Generators.Core.ClassGeneratorBase$2(Nethereum.Generators.CQS.ContractDeploymentCQSMessageTemplate, 
    Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel, 63560), function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IFileGenerator, Nethereum.Generators.Core.IGenerator];
    $t.ctor = function ContractDeploymentCQSMessageGenerator(abi, namespaceName, byteCode, contractName) {
        $t.$baseType.ctor.call(this);
        this.set_ClassModel(new Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel.ctor(abi, 
            namespaceName, byteCode, contractName));
        this.set_ClassTemplate(new Nethereum.Generators.CQS.ContractDeploymentCQSMessageTemplate.ctor(this.get_ClassModel()));
    };
});
$d.define(Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel, Nethereum.Generators.Core.TypeMessageModel, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassModel];
    $t.cctor = function() {
        $t.CLASSNAME_SUFFIX = "Deployment";
    };
    $t.$ator = function() {
        this.ConstructorABI = null;
        this.ByteCode = null;
        this.ContractName = null;
    };
    $p.get_ConstructorABI = function ContractDeploymentCQSMessageModel_get_ConstructorABI() { return this.ConstructorABI; };
    $p.get_ByteCode = function ContractDeploymentCQSMessageModel_get_ByteCode() { return this.ByteCode; };
    $p.get_ContractName = function ContractDeploymentCQSMessageModel_get_ContractName() { return this.ContractName; };
    $t.ctor = function ContractDeploymentCQSMessageModel(constructorABI, namespace, byteCode, contractName) {
        $t.$baseType.ctor.call(this, namespace);
        this.ConstructorABI = constructorABI;
        this.ByteCode = byteCode;
        this.ContractName = contractName;
    };
    $p.GetClassNameSuffix = function ContractDeploymentCQSMessageModel_GetClassNameSuffix() {
        return $t.CLASSNAME_SUFFIX;
    };
    $p.GetBaseName = function ContractDeploymentCQSMessageModel_GetBaseName() {
        return this.get_ContractName();
    };
});
$d.define(Nethereum.Generators.CQS.ContractDeploymentCQSMessageTemplate, null, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassTemplate];
    $t.$ator = function() {
        this._parameterABIFunctionDTOTemplate = null;
        this._model = null;
    };
    $t.ctor = function ContractDeploymentCQSMessageTemplate(model) {
        $t.$baseType.ctor.call(this);
        this._parameterABIFunctionDTOTemplate = new Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate.ctor();
        this._model = model;
    };
    $p.GenerateFullClass = function ContractDeploymentCQSMessageTemplate_GenerateFullClass() {
        return String.Format("{0}using System;\r\n{1}using System.Threading.Tasks;\r\n{2}using System.Numerics;\r\n{3}using Nethereum.Hex.HexTypes;\r\n{4}using Nethereum.Contracts.CQS;\r\n{5}using Nethereum.ABI.FunctionEncoding.Attributes;\r\n{6}namespace {7}\r\n{8}{{\r\n{9}{10}\r\n{11}}}\r\n", 
            [Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, this._model.get_Namespace(), Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, this.GenerateClass(), Nethereum.Generators.Core.SpaceUtils().NoTabs]);
    };
    $p.GenerateClass = function ContractDeploymentCQSMessageTemplate_GenerateClass() {
        var typeName = this._model.GetTypeName();
        return String.Format("{0}public class {1}:ContractDeploymentMessage\r\n{2}{{\r\n{3}\r\n{4}public static string BYTECODE = \"{5}\";\r\n{6}\r\n{7}public {8}():base(BYTECODE)\r\n{9}{{\r\n{10}}}\r\n{11}\r\n{12}public {13}(string byteCode):base(byteCode)\r\n{14}{{\r\n{15}}}\r\n{16}\r\n{17}\r\n{18}}}", 
            [Nethereum.Generators.Core.SpaceUtils().OneTab, typeName, Nethereum.Generators.Core.SpaceUtils().OneTab, 
                Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                this._model.get_ByteCode(), Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                typeName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                typeName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().TwoTabs, this._parameterABIFunctionDTOTemplate.GenerateAllProperties(this._model.get_ConstructorABI().get_InputParameters()), 
                Nethereum.Generators.Core.SpaceUtils().OneTab]);
    };
    $p.Nethereum$Generators$Core$IClassTemplate$GenerateClass = $p.GenerateClass;
    $p.Nethereum$Generators$Core$IClassTemplate$GenerateFullClass = $p.GenerateFullClass;
});
$d.define(Nethereum.Generators.CQS.FunctionCQSMessageGenerator, Nethereum.Generators.Core.ClassGeneratorBase$2(Nethereum.Generators.CQS.FunctionCQSMessageTemplate, 
    Nethereum.Generators.CQS.FunctionCQSMessageModel, 21098), function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IFileGenerator, Nethereum.Generators.Core.IGenerator];
    $t.$ator = function() {
        this.FunctionABI = null;
    };
    $p.get_FunctionABI = function FunctionCQSMessageGenerator_get_FunctionABI() { return this.FunctionABI; };
    $t.ctor = function FunctionCQSMessageGenerator(functionABI, namespace, namespaceFunctionOutput) {
        $t.$baseType.ctor.call(this);
        this.FunctionABI = functionABI;
        this.set_ClassModel(new Nethereum.Generators.CQS.FunctionCQSMessageModel.ctor(this.get_FunctionABI(), 
            namespace));
        var functionOutputDTOModel = new Nethereum.Generators.DTOs.FunctionOutputDTOModel.ctor(functionABI, 
            namespaceFunctionOutput);
        var functionABIModel = new Nethereum.Generators.Core.FunctionABIModel.ctor(this.get_ClassModel().get_FunctionABI());
        this.set_ClassTemplate(new Nethereum.Generators.CQS.FunctionCQSMessageTemplate.ctor(this.get_ClassModel(), 
            functionOutputDTOModel, functionABIModel));
    };
});
$d.define(Nethereum.Generators.CQS.FunctionCQSMessageModel, Nethereum.Generators.Core.TypeMessageModel, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassModel];
    $t.$ator = function() {
        this.CLASSNAME_SUFFIX = "Function";
        this.FunctionABI = null;
    };
    $p.get_FunctionABI = function FunctionCQSMessageModel_get_FunctionABI() { return this.FunctionABI; };
    $t.ctor = function FunctionCQSMessageModel(functionABI, namespace) {
        $t.$baseType.ctor.call(this, namespace);
        this.FunctionABI = functionABI;
    };
    $p.GetClassNameSuffix = function FunctionCQSMessageModel_GetClassNameSuffix() {
        return this.CLASSNAME_SUFFIX;
    };
    $p.GetBaseName = function FunctionCQSMessageModel_GetBaseName() {
        return this.get_FunctionABI().get_Name();
    };
});
$d.define(Nethereum.Generators.CQS.FunctionCQSMessageTemplate, null, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassTemplate];
    $t.$ator = function() {
        this._parameterABIFunctionDTOTemplate = null;
        this._functionOutputDTOModel = null;
        this._functionCQSMessageModel = null;
        this._functionABIModel = null;
    };
    $t.ctor = function FunctionCQSMessageTemplate(model, functionOutputDTOModel, functionABIModel) {
        $t.$baseType.ctor.call(this);
        this._parameterABIFunctionDTOTemplate = new Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate.ctor();
        this._functionOutputDTOModel = functionOutputDTOModel;
        this._functionCQSMessageModel = model;
        this._functionABIModel = functionABIModel;
    };
    $p.GenerateFullClass = function FunctionCQSMessageTemplate_GenerateFullClass() {
        return String.Format("{0}using System;\r\n{1}using System.Threading.Tasks;\r\n{2}using System.Numerics;\r\n{3}using Nethereum.Hex.HexTypes;\r\n{4}using Nethereum.ABI.FunctionEncoding.Attributes;\r\n{5}using Nethereum.Contracts.CQS;\r\n{6}using {7};\r\n{8}namespace {9}\r\n{10}{{\r\n{11}{12}\r\n{13}}}\r\n", 
            [Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, this._functionOutputDTOModel.get_Namespace(), 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, this._functionCQSMessageModel.get_Namespace(), 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                this.GenerateClass(), Nethereum.Generators.Core.SpaceUtils().NoTabs]);
    };
    $p.GenerateClass = function FunctionCQSMessageTemplate_GenerateClass() {
        var functionABI = this._functionCQSMessageModel.get_FunctionABI();
        var header = "";
        if (this._functionABIModel.IsMultipleOutput()) {
            header = String.Format("{0}[Function(\"{1}\", typeof({2}))]", [Nethereum.Generators.Core.SpaceUtils().OneTab, 
                functionABI.get_Name(), this._functionOutputDTOModel.GetTypeName()]);
        }

        if (this._functionABIModel.IsSingleOutput()) {
            header = String.Format("{0}[Function(\"{1}\", \"{2}\")]", [Nethereum.Generators.Core.SpaceUtils().OneTab, 
                functionABI.get_Name(), this._functionABIModel.GetSingleAbiReturnType()]);
        }

        if (this._functionABIModel.HasNoReturn()) {
            header = String.Format("{0}[Function(\"{1}\"]", [Nethereum.Generators.Core.SpaceUtils().OneTab, 
                functionABI.get_Name()]);
        }

        return String.Format("{0}\r\n{1}public class {2}:ContractMessage\r\n{3}{{\r\n{4}\r\n{5}}}", [header, 
            Nethereum.Generators.Core.SpaceUtils().OneTab, this._functionCQSMessageModel.GetTypeName(), 
            Nethereum.Generators.Core.SpaceUtils().OneTab, this._parameterABIFunctionDTOTemplate.GenerateAllProperties(functionABI.get_InputParameters()), 
            Nethereum.Generators.Core.SpaceUtils().OneTab]);
    };
    $p.Nethereum$Generators$Core$IClassTemplate$GenerateClass = $p.GenerateClass;
    $p.Nethereum$Generators$Core$IClassTemplate$GenerateFullClass = $p.GenerateFullClass;
});
$d.define(Nethereum.Generators.DTOs.EventDTOGenerator, Nethereum.Generators.Core.ClassGeneratorBase$2(Nethereum.Generators.DTOs.EventDTOTemplate, 
    Nethereum.Generators.DTOs.EventDTOModel, 13285), function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IFileGenerator, Nethereum.Generators.Core.IGenerator];
    $t.ctor = function EventDTOGenerator(abi, namespace) {
        $t.$baseType.ctor.call(this);
        this.set_ClassModel(new Nethereum.Generators.DTOs.EventDTOModel.ctor(abi, namespace));
        this.set_ClassTemplate(new Nethereum.Generators.DTOs.EventDTOTemplate.ctor(this.get_ClassModel()));
    };
});
$d.define(Nethereum.Generators.DTOs.EventDTOModel, Nethereum.Generators.Core.TypeMessageModel, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassModel];
    $t.cctor = function() {
        $t.SUFFIX_NAME = "EventDTO";
    };
    $t.$ator = function() {
        this.EventABI = null;
    };
    $p.get_EventABI = function EventDTOModel_get_EventABI() { return this.EventABI; };
    $t.ctor = function EventDTOModel(eventABI, namespace) {
        $t.$baseType.ctor.call(this, namespace);
        this.EventABI = eventABI;
    };
    $p.CanGenerateOutputDTO = function EventDTOModel_CanGenerateOutputDTO() {
        return this.get_EventABI().get_InputParameters() != null && this.get_EventABI().get_InputParameters().length > 0;
    };
    $p.GetClassNameSuffix = function EventDTOModel_GetClassNameSuffix() {
        return $t.SUFFIX_NAME;
    };
    $p.GetBaseName = function EventDTOModel_GetBaseName() {
        return this.get_EventABI().get_Name();
    };
});
$d.define(Nethereum.Generators.DTOs.EventDTOTemplate, null, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassTemplate];
    $t.$ator = function() {
        this._parameterABIEventDTOTemplate = null;
        this._eventDTOModel = null;
    };
    $t.ctor = function EventDTOTemplate(eventDTOModel) {
        $t.$baseType.ctor.call(this);
        this._parameterABIEventDTOTemplate = new Nethereum.Generators.DTOs.ParameterABIEventDTOTemplate.ctor();
        this._eventDTOModel = eventDTOModel;
    };
    $p.GenerateFullClass = function EventDTOTemplate_GenerateFullClass() {
        return String.Format("{0}using System;\r\n{1}using System.Threading.Tasks;\r\n{2}using System.Numerics;\r\n{3}using Nethereum.Hex.HexTypes;\r\n{4}using Nethereum.ABI.FunctionEncoding.Attributes;\r\n{5}namespace {6}\r\n{7}{{\r\n{8}{9}\r\n{10}}}\r\n", 
            [Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                this._eventDTOModel.get_Namespace(), Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                this.GenerateClass(), Nethereum.Generators.Core.SpaceUtils().NoTabs]);
    };
    $p.GenerateClass = function EventDTOTemplate_GenerateClass() {
        if (this._eventDTOModel.CanGenerateOutputDTO()) {
            return String.Format("{0}[Event(\"{1}\")]\r\n{2}public class {3}\r\n{4}{{\r\n{5}\r\n{6}}}", 
                [Nethereum.Generators.Core.SpaceUtils().OneTab, this._eventDTOModel.get_EventABI().get_Name(), 
                    Nethereum.Generators.Core.SpaceUtils().OneTab, this._eventDTOModel.GetTypeName(), 
                    Nethereum.Generators.Core.SpaceUtils().OneTab, this._parameterABIEventDTOTemplate.GenerateAllProperties(this._eventDTOModel.get_EventABI().get_InputParameters()), 
                    Nethereum.Generators.Core.SpaceUtils().OneTab]);
        }
        return null;
    };
    $p.Nethereum$Generators$Core$IClassTemplate$GenerateClass = $p.GenerateClass;
    $p.Nethereum$Generators$Core$IClassTemplate$GenerateFullClass = $p.GenerateFullClass;
});
$d.define(Nethereum.Generators.DTOs.FunctionOutputDTOGenerator, Nethereum.Generators.Core.ClassGeneratorBase$2(Nethereum.Generators.DTOs.FunctionOutputDTOTemplate, 
    Nethereum.Generators.DTOs.FunctionOutputDTOModel, 49029), function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IFileGenerator, Nethereum.Generators.Core.IGenerator];
    $t.ctor = function FunctionOutputDTOGenerator(functionABI, namespace) {
        $t.$baseType.ctor.call(this);
        this.set_ClassModel(new Nethereum.Generators.DTOs.FunctionOutputDTOModel.ctor(functionABI, namespace));
        this.set_ClassTemplate(new Nethereum.Generators.DTOs.FunctionOutputDTOTemplate.ctor(this.get_ClassModel()));
    };
    $p.GenerateClass = function FunctionOutputDTOGenerator_GenerateClass() {
        return this.get_ClassModel().CanGenerateOutputDTO() ? this.get_ClassTemplate().GenerateClass() : null;
    };
    $p.GenerateFileContent = function FunctionOutputDTOGenerator_GenerateFileContent() {
        return this.get_ClassModel().CanGenerateOutputDTO() ? this.get_ClassTemplate().GenerateFullClass() : null;
    };
    $p.Nethereum$Generators$Core$IFileGenerator$GenerateFileContent = $p.GenerateFileContent;
    $p.Nethereum$Generators$Core$IGenerator$GenerateClass = $p.GenerateClass;
});
$d.define(Nethereum.Generators.DTOs.FunctionOutputDTOModel, Nethereum.Generators.Core.TypeMessageModel, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassModel];
    $t.cctor = function() {
        $t.SUFFIX_NAME = "OutputDTO";
    };
    $t.$ator = function() {
        this.FunctionABI = null;
    };
    $p.get_FunctionABI = function FunctionOutputDTOModel_get_FunctionABI() { return this.FunctionABI; };
    $t.ctor = function FunctionOutputDTOModel(functionABI, namespace) {
        $t.$baseType.ctor.call(this, namespace);
        this.FunctionABI = functionABI;
    };
    $p.CanGenerateOutputDTO = function FunctionOutputDTOModel_CanGenerateOutputDTO() {
        return this.get_FunctionABI().get_OutputParameters() != null && this.get_FunctionABI().get_OutputParameters().length > 0 && this.get_FunctionABI().get_Constant();
    };
    $p.GetClassNameSuffix = function FunctionOutputDTOModel_GetClassNameSuffix() {
        return $t.SUFFIX_NAME;
    };
    $p.GetBaseName = function FunctionOutputDTOModel_GetBaseName() {
        return this.get_FunctionABI().get_Name();
    };
});
$d.define(Nethereum.Generators.DTOs.FunctionOutputDTOTemplate, null, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassTemplate];
    $t.$ator = function() {
        this._parameterABIFunctionDTOTemplate = null;
        this._model = null;
    };
    $t.ctor = function FunctionOutputDTOTemplate(model) {
        $t.$baseType.ctor.call(this);
        this._parameterABIFunctionDTOTemplate = new Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate.ctor();
        this._model = model;
    };
    $p.GenerateFullClass = function FunctionOutputDTOTemplate_GenerateFullClass() {
        return String.Format("{0}using System;\r\n{1}using System.Threading.Tasks;\r\n{2}using System.Numerics;\r\n{3}using Nethereum.Hex.HexTypes;\r\n{4}using Nethereum.ABI.FunctionEncoding.Attributes;\r\n{5}namespace {6}\r\n{7}{{\r\n{8}\r\n{9}}}\r\n", 
            [Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                this._model.get_Namespace(), Nethereum.Generators.Core.SpaceUtils().NoTabs, this.GenerateClass(), 
                Nethereum.Generators.Core.SpaceUtils().NoTabs]);
    };
    $p.GenerateClass = function FunctionOutputDTOTemplate_GenerateClass() {
        if (this._model.CanGenerateOutputDTO()) {
            return String.Format("{0}[FunctionOutput]\r\n{1}public class {2}\r\n{3}{{\r\n{4}\r\n{5}}}", 
                [Nethereum.Generators.Core.SpaceUtils().OneTab, Nethereum.Generators.Core.SpaceUtils().OneTab, 
                    this._model.GetTypeName(), Nethereum.Generators.Core.SpaceUtils().OneTab, this._parameterABIFunctionDTOTemplate.GenerateAllProperties(this._model.get_FunctionABI().get_OutputParameters()), 
                    Nethereum.Generators.Core.SpaceUtils().OneTab]);
        }
        return null;
    };
    $p.Nethereum$Generators$Core$IClassTemplate$GenerateClass = $p.GenerateClass;
    $p.Nethereum$Generators$Core$IClassTemplate$GenerateFullClass = $p.GenerateFullClass;
});
$d.define(Nethereum.Generators.DTOs.ParameterABIEventDTOTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this.parameterModel = null;
        this.utils = null;
    };
    $t.ctor = function ParameterABIEventDTOTemplate() {
        $t.$baseType.ctor.call(this);
        this.parameterModel = new Nethereum.Generators.Core.ParameterABIModel.ctor();
        this.utils = new Nethereum.Generators.Core.Utils.ctor();
    };
    $p.GenerateAllProperties = function ParameterABIEventDTOTemplate_GenerateAllProperties(parameters) {
        return String.Join$1(String, System.Environment().NewLine, System.Linq.Enumerable.Select(Nethereum.Generators.Model.Parameter, 
            String, parameters, $d.delegate(this.GenerateProperty, this)));
    };
    $p.GenerateProperty = function ParameterABIEventDTOTemplate_GenerateProperty(parameter) {
        return String.Format("{0}[Parameter(\"{1}\", \"{2}\", {3}, {4} )]\r\n{5}public {6} {7} {{get; set;}}", 
            [Nethereum.Generators.Core.SpaceUtils().TwoTabs, parameter.get_Type(), parameter.get_Name(), 
                parameter.get_Order(), this.utils.GetBooleanAsString(parameter.get_Indexed()), Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                this.parameterModel.GetParameterCSharpOutputMapType(parameter), this.parameterModel.GetParameterPropertyName(parameter)]);
    };
});
$d.define(Nethereum.Generators.DTOs.ParameterABIFunctionDTOTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this.parameterModel = null;
    };
    $t.ctor = function ParameterABIFunctionDTOTemplate() {
        $t.$baseType.ctor.call(this);
        this.parameterModel = new Nethereum.Generators.Core.ParameterABIModel.ctor();
    };
    $p.GenerateAllProperties = function ParameterABIFunctionDTOTemplate_GenerateAllProperties(parameters) {
        return String.Join$1(String, System.Environment().NewLine, System.Linq.Enumerable.Select(Nethereum.Generators.Model.Parameter, 
            String, parameters, $d.delegate(this.GenerateProperty, this)));
    };
    $p.GenerateProperty = function ParameterABIFunctionDTOTemplate_GenerateProperty(parameter) {
        return String.Format("{0}[Parameter(\"{1}\", \"{2}\", {3})]\r\n{4}public {5} {6} {{get; set;}}", 
            [Nethereum.Generators.Core.SpaceUtils().TwoTabs, parameter.get_Type(), parameter.get_Name(), 
                parameter.get_Order(), Nethereum.Generators.Core.SpaceUtils().TwoTabs, this.parameterModel.GetParameterCSharpOutputMapType(parameter), 
                this.parameterModel.GetParameterPropertyName(parameter)]);
    };
});
$d.define(Nethereum.Generators.Model.ConstructorABI, null, function($t, $p) {
    $t.$ator = function() {
        this.InputParameters = null;
    };
    $t.ctor = function ConstructorABI() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_InputParameters = function ConstructorABI_get_InputParameters() { return this.InputParameters; };
    $p.set_InputParameters = function ConstructorABI_set_InputParameters(value) { this.InputParameters = value;return value; };
});
$d.define(Nethereum.Generators.Model.ContractABI, null, function($t, $p) {
    $t.$ator = function() {
        this.Functions = null;
        this.Constructor = null;
        this.Events = null;
    };
    $t.ctor = function ContractABI() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_Functions = function ContractABI_get_Functions() { return this.Functions; };
    $p.set_Functions = function ContractABI_set_Functions(value) { this.Functions = value;return value; };
    $p.get_Constructor = function ContractABI_get_Constructor() { return this.Constructor; };
    $p.set_Constructor = function ContractABI_set_Constructor(value) { this.Constructor = value;return value; };
    $p.get_Events = function ContractABI_get_Events() { return this.Events; };
    $p.set_Events = function ContractABI_set_Events(value) { this.Events = value;return value; };
});
$d.define(Nethereum.Generators.Model.EventABI, null, function($t, $p) {
    $t.$ator = function() {
        this.Name = null;
        this.InputParameters = null;
    };
    $t.ctor = function EventABI(name) {
        $t.$baseType.ctor.call(this);
        this.Name = name;
    };
    $p.get_Name = function EventABI_get_Name() { return this.Name; };
    $p.get_InputParameters = function EventABI_get_InputParameters() { return this.InputParameters; };
    $p.set_InputParameters = function EventABI_set_InputParameters(value) { this.InputParameters = value;return value; };
});
$d.define(Nethereum.Generators.Model.FunctionABI, null, function($t, $p) {
    $t.$ator = function() {
        this.Serpent = false;
        this.Constant = false;
        this.Name = null;
        this.InputParameters = null;
        this.OutputParameters = null;
    };
    $t.ctor = function FunctionABI(name, constant, serpent) {
        $t.$baseType.ctor.call(this);
        this.Name = name;
        this.set_Serpent(serpent);
        this.set_Constant(constant);
    };
    $p.get_Serpent = function FunctionABI_get_Serpent() { return this.Serpent; };
    $p.set_Serpent = function FunctionABI_set_Serpent(value) { this.Serpent = value;return value; };
    $p.get_Constant = function FunctionABI_get_Constant() { return this.Constant; };
    $p.set_Constant = function FunctionABI_set_Constant(value) { this.Constant = value;return value; };
    $p.get_Name = function FunctionABI_get_Name() { return this.Name; };
    $p.get_InputParameters = function FunctionABI_get_InputParameters() { return this.InputParameters; };
    $p.set_InputParameters = function FunctionABI_set_InputParameters(value) { this.InputParameters = value;return value; };
    $p.get_OutputParameters = function FunctionABI_get_OutputParameters() { return this.OutputParameters; };
    $p.set_OutputParameters = function FunctionABI_set_OutputParameters(value) { this.OutputParameters = value;return value; };
});
$d.define(Nethereum.Generators.Model.Parameter, null, function($t, $p) {
    $t.$ator = function() {
        this.Name = null;
        this.Type = null;
        this.Order = 0;
        this.Indexed = false;
        this.SerpentSignature = null;
    };
    $t.ctor$1 = function Parameter(type, name, order, serpentSignature) {
        $t.$baseType.ctor.call(this);
        this.set_Name(name);
        this.set_Type(type);
        this.set_Order(order);
        this.set_SerpentSignature(serpentSignature);
    };
    $t.ctor = function Parameter(type, order) {
        $t.ctor$1.call(this, type, null, order, null);
    };
    $p.get_Name = function Parameter_get_Name() { return this.Name; };
    $p.set_Name = function Parameter_set_Name(value) { this.Name = value;return value; };
    $p.get_Type = function Parameter_get_Type() { return this.Type; };
    $p.set_Type = function Parameter_set_Type(value) { this.Type = value;return value; };
    $p.get_Order = function Parameter_get_Order() { return this.Order; };
    $p.set_Order = function Parameter_set_Order(value) { this.Order = value;return value; };
    $p.get_Indexed = function Parameter_get_Indexed() { return this.Indexed; };
    $p.set_Indexed = function Parameter_set_Indexed(value) { this.Indexed = value;return value; };
    $p.get_SerpentSignature = function Parameter_get_SerpentSignature() { return this.SerpentSignature; };
    $p.set_SerpentSignature = function Parameter_set_SerpentSignature(value) { this.SerpentSignature = value;return value; };
});
$d.define(Nethereum.Generators.Service.ContractDeploymentServiceMethodsTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this._contractDeploymentCQSMessageModel = null;
        this._serviceModel = null;
    };
    $t.ctor = function ContractDeploymentServiceMethodsTemplate(model) {
        $t.$baseType.ctor.call(this);
        this._contractDeploymentCQSMessageModel = model.get_ContractDeploymentCQSMessageModel();
        this._serviceModel = model;
    };
    $p.GenerateMethods = function ContractDeploymentServiceMethodsTemplate_GenerateMethods() {
        var messageType = this._contractDeploymentCQSMessageModel.GetTypeName();
        var messageVariableName = this._contractDeploymentCQSMessageModel.GetVariableName();

        var sendRequestReceipt = String.Format("{0}public Task<TransactionReceipt> DeployContractAndWaitForReceiptAsync(Web3 web3, {1} {2}, CancellationTokenSource cancellationTokenSource = null)\r\n{3}{{\r\n{4}return web3.Eth.GetContractDeploymentHandler<{5}>().SendRequestAndWaitForReceiptAsync({6}, cancellationTokenSource);\r\n{7}}}", 
            [Nethereum.Generators.Core.SpaceUtils().TwoTabs, messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().ThreeTabs, messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);

        var sendRequest = String.Format("{0}public Task<string> DeployContractAsync(Web3 web3, {1} {2})\r\n{3}{{\r\n{4}return web3.Eth.GetContractDeploymentHandler<{5}>().SendRequestAsync({6});\r\n{7}}}", 
            [Nethereum.Generators.Core.SpaceUtils().TwoTabs, messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().ThreeTabs, messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);

        var sendRequestContract = String.Format("{0}public async Task<{1}> DeployContractAndGetServiceAsync(Web3 web3, {2} {3}, CancellationTokenSource cancellationTokenSource = null)\r\n{4}{{\r\n{5}var receipt = await DeployContractAndWaitForReceiptAsync(web3, {6}, cancellationTokenSource);\r\n{7}return new {8}(web3, receipt.ContractAddress);\r\n{9}}}", 
            [Nethereum.Generators.Core.SpaceUtils().TwoTabs, this._serviceModel.GetTypeName(), messageType, 
                messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().ThreeTabs, 
                messageVariableName, Nethereum.Generators.Core.SpaceUtils().ThreeTabs, this._serviceModel.GetTypeName(), 
                Nethereum.Generators.Core.SpaceUtils().TwoTabs]);

        return String.Join(System.Environment().NewLine, $d.array(String, [sendRequestReceipt, sendRequest, 
            sendRequestContract]));
    };
});
$d.define(Nethereum.Generators.Service.FunctionServiceMethodTemplate, null, function($t, $p) {
    $t.$ator = function() {
        this._model = null;
        this._commonGenerators = null;
    };
    $t.ctor = function FunctionServiceMethodTemplate(model) {
        $t.$baseType.ctor.call(this);
        this._model = model;
        this._commonGenerators = new Nethereum.Generators.Core.CommonGenerators.ctor();
    };
    $p.GenerateMethods = function FunctionServiceMethodTemplate_GenerateMethods() {
        var functions = this._model.get_ContractABI().get_Functions();
        return String.Join$1(String, System.Environment().NewLine, System.Linq.Enumerable.Select(Nethereum.Generators.Model.FunctionABI, 
            String, functions, $d.delegate(this.GenerateMethod, this)));
    };
    $p.GenerateMethod = function FunctionServiceMethodTemplate_GenerateMethod(functionABI) {

        var functionCQSMessageModel = new Nethereum.Generators.CQS.FunctionCQSMessageModel.ctor(functionABI, 
            this._model.get_CQSNamespace());
        var functionOutputDTOModel = new Nethereum.Generators.DTOs.FunctionOutputDTOModel.ctor(functionABI, 
            this._model.get_FunctionOutputNamespace());
        var functionABIModel = new Nethereum.Generators.Core.FunctionABIModel.ctor(functionABI);

        var messageType = functionCQSMessageModel.GetTypeName();
        var messageVariableName = functionCQSMessageModel.GetVariableName();
        var functionNameUpper = this._commonGenerators.GenerateClassName(functionABI.get_Name());

        if (functionABIModel.IsMultipleOutput() && !functionABIModel.IsTransaction()) {

            var functionOutputDTOType = functionOutputDTOModel.GetTypeName();
            return String.Format("{0}public Task<{1}> {2}QueryAsync({3} {4}, BlockParameter blockParameter = null)\r\n{5}{{\r\n{6}return ContractHandler.QueryDeserializingToObjectAsync<{7}, {8}>({9}, blockParameter);\r\n{10}}}", 
                [Nethereum.Generators.Core.SpaceUtils().TwoTabs, functionOutputDTOType, functionNameUpper, 
                    messageType, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                    Nethereum.Generators.Core.SpaceUtils().ThreeTabs, messageType, functionOutputDTOType, 
                    messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);
        }

        if (functionABIModel.IsSingleOutput() && !functionABIModel.IsTransaction())
            if (functionABI.get_OutputParameters() != null && functionABI.get_OutputParameters().length == 1 && functionABI.get_Constant()) {
                var type = functionABIModel.GetSingleOutputReturnType();

                return String.Format("{0}public Task<{1}> {2}QueryAsync({3} {4}, BlockParameter blockParameter = null)\r\n{5}{{\r\n{6}return ContractHandler.QueryAsync<{7}, {8}>({9}, blockParameter);\r\n{10}}}", 
                    [Nethereum.Generators.Core.SpaceUtils().TwoTabs, type, functionNameUpper, messageType, 
                        messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().ThreeTabs, 
                        messageType, type, messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);
            }

        if (functionABIModel.IsTransaction()) {
            var transactionRequest = String.Format("{0}public Task<string> {1}RequestAsync({2} {3})\r\n{4}{{\r\n{5} return ContractHandler.SendRequestAsync({6});\r\n{7}}}", 
                [Nethereum.Generators.Core.SpaceUtils().TwoTabs, functionNameUpper, messageType, messageVariableName, 
                    Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().ThreeTabs, 
                    messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);

            var transactionRequestAndReceipt = String.Format("{0}public Task<TransactionReceipt> {1}RequestAndWaitForReceiptAsync({2} {3}, CancellationTokenSource cancellationToken = null)\r\n{4}{{\r\n{5} return ContractHandler.SendRequestAndWaitForReceiptAsync({6}, cancellationToken);\r\n{7}}}", 
                [Nethereum.Generators.Core.SpaceUtils().TwoTabs, functionNameUpper, messageType, messageVariableName, 
                    Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().ThreeTabs, 
                    messageVariableName, Nethereum.Generators.Core.SpaceUtils().TwoTabs]);

            return transactionRequest + System.Environment().NewLine + transactionRequestAndReceipt;
        }

        return null;
    };
});
$d.define(Nethereum.Generators.Service.ServiceGenerator, Nethereum.Generators.Core.ClassGeneratorBase$2(Nethereum.Generators.Service.ServiceTemplate, 
    Nethereum.Generators.Service.ServiceModel, 18592), function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IFileGenerator, Nethereum.Generators.Core.IGenerator];
    $t.$ator = function() {
        this.ContractABI = null;
    };
    $p.get_ContractABI = function ServiceGenerator_get_ContractABI() { return this.ContractABI; };
    $t.ctor = function ServiceGenerator(contractABI, contractName, byteCode, namespace, cqsNamespace, functionOutputNamespace) {
        $t.$baseType.ctor.call(this);
        this.ContractABI = contractABI;
        this.set_ClassModel(new Nethereum.Generators.Service.ServiceModel.ctor(contractABI, contractName, 
            byteCode, namespace, cqsNamespace, functionOutputNamespace));
        this.set_ClassTemplate(new Nethereum.Generators.Service.ServiceTemplate.ctor(this.get_ClassModel()));
    };
});
$d.define(Nethereum.Generators.Service.ServiceModel, Nethereum.Generators.Core.TypeMessageModel, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassModel];
    $t.$ator = function() {
        this.CLASSNAME_SUFFIX = "Service";
        this.ContractABI = null;
        this.ContractName = null;
        this.CQSNamespace = null;
        this.FunctionOutputNamespace = null;
        this.ContractDeploymentCQSMessageModel = null;
    };
    $p.get_ContractABI = function ServiceModel_get_ContractABI() { return this.ContractABI; };
    $p.get_ContractName = function ServiceModel_get_ContractName() { return this.ContractName; };
    $p.get_CQSNamespace = function ServiceModel_get_CQSNamespace() { return this.CQSNamespace; };
    $p.get_FunctionOutputNamespace = function ServiceModel_get_FunctionOutputNamespace() { return this.FunctionOutputNamespace; };
    $p.get_ContractDeploymentCQSMessageModel = function ServiceModel_get_ContractDeploymentCQSMessageModel() { return this.ContractDeploymentCQSMessageModel; };
    $t.ctor = function ServiceModel(contractABI, contractName, byteCode, namespace, cqsNamespace, functionOutputNamespace) {
        $t.$baseType.ctor.call(this, namespace);
        this.ContractABI = contractABI;
        this.ContractName = contractName;
        this.CQSNamespace = cqsNamespace;
        this.FunctionOutputNamespace = functionOutputNamespace;
        this.ContractDeploymentCQSMessageModel = new Nethereum.Generators.CQS.ContractDeploymentCQSMessageModel.ctor(contractABI.get_Constructor(), 
            cqsNamespace, byteCode, contractName);
    };
    $p.GetClassNameSuffix = function ServiceModel_GetClassNameSuffix() {
        return this.CLASSNAME_SUFFIX;
    };
    $p.GetBaseName = function ServiceModel_GetBaseName() {
        return this.get_ContractName();
    };
});
$d.define(Nethereum.Generators.Service.ServiceTemplate, null, function($t, $p) {
    $t.$intfs = [Nethereum.Generators.Core.IClassTemplate];
    $t.$ator = function() {
        this._model = null;
        this._functionServiceMethodTemplate = null;
        this._deploymentServiceMethodsTemplate = null;
    };
    $t.ctor = function ServiceTemplate(model) {
        $t.$baseType.ctor.call(this);
        this._functionServiceMethodTemplate = new Nethereum.Generators.Service.FunctionServiceMethodTemplate.ctor(model);
        this._deploymentServiceMethodsTemplate = new Nethereum.Generators.Service.ContractDeploymentServiceMethodsTemplate.ctor(model);
        this._model = model;
    };
    $p.GenerateFullClass = function ServiceTemplate_GenerateFullClass() {
        return String.Format("{0}using System;\r\n{1}using System.Threading.Tasks;\r\n{2}using System.Numerics;\r\n{3}using Nethereum.Hex.HexTypes;\r\n{4}using Nethereum.ABI.FunctionEncoding.Attributes;\r\n{5}using Nethereum.Web3;\r\n{6}using Nethereum.RPC.Eth.DTOs;\r\n{7}using Nethereum.Contracts.CQS;\r\n{8}using System.Threading;\r\n{9}using {10};\r\n{11}using {12};\r\n{13}namespace {14}\r\n{15}{{\r\n{16}\r\n{17}}}\r\n", 
            [Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                this._model.get_CQSNamespace(), Nethereum.Generators.Core.SpaceUtils().NoTabs, this._model.get_FunctionOutputNamespace(), 
                Nethereum.Generators.Core.SpaceUtils().NoTabs, this._model.get_Namespace(), Nethereum.Generators.Core.SpaceUtils().NoTabs, 
                this.GenerateClass(), Nethereum.Generators.Core.SpaceUtils().NoTabs]);
    };
    $p.GenerateClass = function ServiceTemplate_GenerateClass() {
        return String.Format("\r\n{0}public class {1}\r\n{2}{{\r\n{3}\r\n{4}\r\n{5}\r\n{6}protected Web3 Web3{{ get; }}\r\n{7}\r\n{8}protected ContractHandler ContractHandler {{ get; }}\r\n{9}\r\n{10}public {11}(Web3 web3, string contractAddress)\r\n{12}{{\r\n{13}Web3 = web3;\r\n{14}ContractHandler = web3.Eth.GetContractHandler(contractAddress);\r\n{15}}}\r\n{16}\r\n{17}\r\n{18}}}", 
            [Nethereum.Generators.Core.SpaceUtils().OneTab, this._model.GetTypeName(), Nethereum.Generators.Core.SpaceUtils().OneTab, 
                Nethereum.Generators.Core.SpaceUtils().OneTab, this._deploymentServiceMethodsTemplate.GenerateMethods(), 
                Nethereum.Generators.Core.SpaceUtils().OneTab, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                this._model.GetTypeName(), Nethereum.Generators.Core.SpaceUtils().TwoTabs, Nethereum.Generators.Core.SpaceUtils().ThreeTabs, 
                Nethereum.Generators.Core.SpaceUtils().ThreeTabs, Nethereum.Generators.Core.SpaceUtils().TwoTabs, 
                Nethereum.Generators.Core.SpaceUtils().OneTab, this._functionServiceMethodTemplate.GenerateMethods(), 
                Nethereum.Generators.Core.SpaceUtils().OneTab]);

    };
    $p.Nethereum$Generators$Core$IClassTemplate$GenerateClass = $p.GenerateClass;
    $p.Nethereum$Generators$Core$IClassTemplate$GenerateFullClass = $p.GenerateFullClass;
});
return $asm;
})();
//# sourceMappingURL=Nethereum.Generators.DuoCode.js.map
