using static Nethereum.Explorer.Services.Localization.ExplorerKeys;

namespace Nethereum.Explorer.Services.Localization;

public static class ExplorerStrings_en
{
    public static Dictionary<string, string> All => new()
    {
        // Search
        [Search.Placeholder] = "Search by Address / Tx Hash / Block",
        [Search.GoToBlock] = "Go to Block #{0}",
        [Search.GoToAddress] = "Go to Address",
        [Search.TxOrBlockHash] = "Transaction or Block Hash",
        [Search.HexValue] = "Hex value ({0} chars)",
        [Search.SearchLabel] = "Search",
        [Search.RecentSearches] = "Recent Searches",

        // Shared
        [Shared.Page] = "Page",
        [Shared.PageOf] = "of",
        [Shared.NoData] = "No data",
        [Shared.Loading] = "Loading...",
        [Shared.CopiedToClipboard] = "Copied to clipboard",
        [Shared.CopyToClipboard] = "Copy to clipboard",
        [Shared.FirstPage] = "First page",
        [Shared.LastPage] = "Last page",
        [Shared.ViewAll] = "View All",
        [Shared.Retry] = "Retry",
        [Shared.Total] = "total",
        [Shared.Updated] = "Updated",

        // Table columns
        [Table.TxHash] = "Tx Hash",
        [Table.Method] = "Method",
        [Table.Block] = "Block",
        [Table.Age] = "Age",
        [Table.From] = "From",
        [Table.To] = "To",
        [Table.Value] = "Value",
        [Table.TxFee] = "Tx Fee",
        [Table.Depth] = "Depth",
        [Table.Type] = "Type",
        [Table.GasUsed] = "Gas Used",
        [Table.ContractCreation] = "Contract Creation",
        [Table.Revert] = "Revert:",
        [Table.CallData] = "Call Data:",
        [Table.Input] = "Input:",
        [Table.Output] = "Output:",
        [Table.Name] = "Name",
        [Table.Indexed] = "indexed",
        [Table.Number] = "#",
        [Table.Contract] = "Contract",
        [Table.Balance] = "Balance",
        [Table.Amount] = "Amount",
        [Table.TokenId] = "Token ID",
        [Table.AmountOrTokenId] = "Amount / Token ID",
        [Table.LastUpdated] = "Last Updated",
        [Table.Token] = "Token",
        [Table.Txns] = "Txns",
        [Table.GasLimit] = "Gas Limit",
        [Table.Validator] = "Validator",
        [Table.Gas] = "Gas",
        [Table.Status] = "Status",
        [Table.Collection] = "Collection",

        // Home
        [Home.Title] = "Nethereum Explorer",
        [Home.Dashboard] = "Dashboard",
        [Home.LatestBlock] = "Latest Block",
        [Home.TotalTransactions] = "Total Transactions",
        [Home.ChainId] = "Chain ID",
        [Home.AddToWallet] = "Add to Wallet",
        [Home.LatestBlocks] = "Latest Blocks",
        [Home.LatestTransactions] = "Latest Transactions",
        [Home.NoBlocksYet] = "No blocks yet",
        [Home.WaitingForBlocks] = "Waiting for indexed blocks.",
        [Home.NoTransactionsYet] = "No transactions yet",
        [Home.WaitingForTransactions] = "Waiting for indexed transactions.",

        // Blocks
        [Blocks.Title] = "Blocks",
        [Blocks.NoBlocksIndexed] = "No blocks indexed yet",
        [Blocks.BlocksWillAppear] = "Blocks will appear here as they are processed by the indexer.",

        // Block Detail
        [BlockDetail.Title] = "Block",
        [BlockDetail.LoadingBlock] = "Loading block...",
        [BlockDetail.FailedToLoad] = "Failed to load block",
        [BlockDetail.NotFound] = "Block {0} not found",
        [BlockDetail.NotIndexedYet] = "The block may not have been indexed yet.",
        [BlockDetail.Overview] = "Overview",
        [BlockDetail.BlockNumber] = "Block Number",
        [BlockDetail.Timestamp] = "Timestamp",
        [BlockDetail.Transactions] = "Transactions",
        [BlockDetail.TransactionsInBlock] = "{0} transactions",
        [BlockDetail.ValidatedBy] = "Validated By",
        [BlockDetail.GasAndSize] = "Gas & Size",
        [BlockDetail.Size] = "Size",
        [BlockDetail.BaseFeePerGas] = "Base Fee Per Gas",
        [BlockDetail.BurnedFees] = "Burned Fees",
        [BlockDetail.BlockReward] = "Block Reward",
        [BlockDetail.PoADevChain] = "PoA / Dev Chain",
        [BlockDetail.StaticReward] = "Static reward (mining)",
        [BlockDetail.Difficulty] = "Difficulty",
        [BlockDetail.HashesAndExtra] = "Hashes & Extra",
        [BlockDetail.Hash] = "Hash",
        [BlockDetail.ParentHash] = "Parent Hash",
        [BlockDetail.Nonce] = "Nonce",
        [BlockDetail.ExtraData] = "Extra Data",
        [BlockDetail.StateAndReceipts] = "State & Receipts",
        [BlockDetail.StateRoot] = "State Root",
        [BlockDetail.ReceiptsRoot] = "Receipts Root",
        [BlockDetail.WithdrawalsRoot] = "Withdrawals Root",
        [BlockDetail.LogsBloom] = "Logs Bloom",
        [BlockDetail.NoTransactionsInBlock] = "No transactions in this block",
        [BlockDetail.RawBlockData] = "Raw Block Data",
        [BlockDetail.Details] = "Details",
        [BlockDetail.Prev] = "Prev",
        [BlockDetail.Next] = "Next",
        [BlockDetail.Bytes] = "bytes",

        // Transactions
        [Transactions.Title] = "Transactions",
        [Transactions.NoTransactionsIndexed] = "No transactions indexed yet",
        [Transactions.TransactionsWillAppear] = "Transactions will appear here as they are processed by the indexer.",

        // Transaction Detail
        [TransactionDetail.Title] = "Transaction",
        [TransactionDetail.LoadingTransaction] = "Loading transaction...",
        [TransactionDetail.FailedToLoad] = "Failed to load transaction",
        [TransactionDetail.NotFound] = "Transaction not found",
        [TransactionDetail.TransactionDetails] = "Transaction Details",
        [TransactionDetail.Success] = "Success",
        [TransactionDetail.Failed] = "Failed",
        [TransactionDetail.TransactionReverted] = "Transaction reverted",
        [TransactionDetail.RevertReason] = "Revert reason:",
        [TransactionDetail.Error] = "Error:",
        [TransactionDetail.RawTransactionData] = "Raw Transaction Data",
        [TransactionDetail.Overview] = "Overview",
        [TransactionDetail.TransactionHash] = "Transaction Hash",
        [TransactionDetail.Timestamp] = "Timestamp",
        [TransactionDetail.TransactionFee] = "Transaction Fee",
        [TransactionDetail.GasAndFees] = "Gas & Fees",
        [TransactionDetail.CumulativeGas] = "Cumulative Gas",
        [TransactionDetail.GasPrice] = "Gas Price",
        [TransactionDetail.MaxFeePerGas] = "Max Fee Per Gas",
        [TransactionDetail.MaxPriorityFee] = "Max Priority Fee",
        [TransactionDetail.OtherAttributes] = "Other Attributes",
        [TransactionDetail.TransactionType] = "Transaction Type",
        [TransactionDetail.PositionInBlock] = "Position In Block",
        [TransactionDetail.BlockHash] = "Block Hash",
        [TransactionDetail.ReceiptHash] = "Receipt Hash",
        [TransactionDetail.TokenTransfers] = "Token Transfers",
        [TransactionDetail.InternalTransactions] = "Internal Transactions",
        [TransactionDetail.BlobData] = "Blob Data (EIP-4844)",
        [TransactionDetail.MaxFeePerBlobGas] = "Max Fee Per Blob Gas",
        [TransactionDetail.BlobCount] = "Blob Count",
        [TransactionDetail.BlobVersionedHashes] = "Blob Versioned Hashes",
        [TransactionDetail.AuthorizationList] = "Authorization List (EIP-7702)",
        [TransactionDetail.AuthorizedAddress] = "Authorized Address",
        [TransactionDetail.Signature] = "Signature",
        [TransactionDetail.StateChanges] = "State Changes",
        [TransactionDetail.Accounts] = "{0} accounts",
        [TransactionDetail.ViaPrestateTracer] = "(via prestateTracer simulation)",
        [TransactionDetail.CodeChanged] = "Code Changed",
        [TransactionDetail.StorageSlots] = "Storage ({0} slots):",
        [TransactionDetail.New] = "(new)",
        [TransactionDetail.Deleted] = "(deleted)",
        [TransactionDetail.AndMore] = "... and {0} more",
        [TransactionDetail.LoadingStateDiff] = "Loading state diff...",
        [TransactionDetail.StateDiffUnavailable] = "State diff unavailable: {0}",
        [TransactionDetail.LoadStateChanges] = "Load State Changes",
        [TransactionDetail.SimulatesTransaction] = "Simulates the transaction using prestateTracer. Requires a historical/archive node.",
        [TransactionDetail.InputData] = "Input Data",
        [TransactionDetail.DecodedParameters] = "Decoded Parameters",
        [TransactionDetail.RawInput] = "Raw Input",
        [TransactionDetail.EventLogs] = "Event Logs",

        // Account
        [Account.Title] = "Account",
        [Account.ContractTitle] = "Contract",
        [Account.Overview] = "Overview",
        [Account.Address] = "Address",
        [Account.Nonce] = "Nonce",
        [Account.Actions] = "Actions",
        [Account.InteractWithContract] = "Interact with Contract",
        [Account.ViewAsContract] = "View as Contract",
        [Account.TokenBalances] = "Token Balances",
        [Account.TokenHoldings] = "Token Holdings",
        [Account.LoadingTokens] = "Loading tokens...",
        [Account.NftInventory] = "NFT Inventory",
        [Account.NftHoldings] = "NFT Holdings (ERC-721)",
        [Account.LoadingNfts] = "Loading NFTs...",
        [Account.NoTransactionsFound] = "No transactions found",
        [Account.NoFilteredTx] = "No {0} transactions found.",
        [Account.NoAddressTx] = "No transactions found for this address.",
        [Account.NoInternalTransactions] = "No internal transactions",
        [Account.NoFilteredItx] = "No {0} internal transactions found.",
        [Account.NoAddressItx] = "No internal transactions found for this address.",
        [Account.LoadingTransactions] = "Loading transactions...",
        [Account.LoadingInternalTx] = "Loading internal transactions...",
        [Account.Unknown] = "Unknown",

        // Account Tokens
        [AccountTokens.Title] = "Tokens for",
        [AccountTokens.Balances] = "Balances",
        [AccountTokens.Nfts] = "NFTs",
        [AccountTokens.Transfers] = "Transfers",
        [AccountTokens.TokenIndexingNotAvailable] = "Token indexing not available",
        [AccountTokens.TokenIndexingSubtitle] = "Token repository services are not configured. The host must register ITokenBalanceRepository, INFTInventoryRepository, ITokenTransferLogRepository, and ITokenMetadataRepository.",
        [AccountTokens.LoadingBalances] = "Loading balances...",
        [AccountTokens.NoTokenBalances] = "No token balances",
        [AccountTokens.NoTokenBalancesSubtitle] = "No indexed token balances found for this address.",
        [AccountTokens.LoadingNfts] = "Loading NFTs...",
        [AccountTokens.NoNfts] = "No NFTs",
        [AccountTokens.NoNftsSubtitle] = "No indexed NFT inventory found for this address.",
        [AccountTokens.LoadingTransfers] = "Loading transfers...",
        [AccountTokens.NoTransfers] = "No transfers",
        [AccountTokens.NoTransfersSubtitle] = "No indexed token transfers found for this address.",
        [AccountTokens.BlockPrefix] = "Block",

        // Contract
        [Contract.Title] = "Contract",
        [Contract.AbiStatus] = "ABI Status",
        [Contract.AbiAvailable] = "ABI Available",
        [Contract.FunctionsEvents] = "{0} functions, {1} events",
        [Contract.NoAbi] = "No ABI",
        [Contract.ProxyContract] = "Proxy Contract",
        [Contract.Implementation] = "Implementation:",
        [Contract.NotConnected] = "Not connected",
        [Contract.ConnectWallet] = "Connect a wallet to interact with this contract",
        [Contract.AbiJson] = "ABI JSON",
        [Contract.Bytecode] = "Bytecode",
        [Contract.BytesLabel] = "{0} bytes",
        [Contract.Collapse] = "Collapse",
        [Contract.Expand] = "Expand",
        [Contract.PasteAbiJson] = "Paste ABI JSON",
        [Contract.StoreAbi] = "Store ABI",
        [Contract.InvalidAbiJson] = "Invalid ABI JSON",
        [Contract.FailedToParseAbi] = "Failed to parse ABI: {0}",
        [Contract.Query] = "Query",
        [Contract.Transact] = "Transact",
        [Contract.Events] = "Events",
        [Contract.SourceCode] = "Source Code",
        [Contract.EventSignatures] = "Event Signatures",
        [Contract.RecentEventLogs] = "Recent Event Logs",
        [Contract.LoadEvents] = "Load Events",
        [Contract.ClickLoadEvents] = "Click \"Load Events\" to query recent event logs for this contract.",
        [Contract.NoEventsFound] = "No events found",
        [Contract.NoEventsSubtitle] = "No event logs found for this contract.",
        [Contract.ContractTransactions] = "Contract Transactions",
        [Contract.NoTransactionsFound] = "No transactions found",
        [Contract.NoContractTxSubtitle] = "No transactions found for this contract.",
        [Contract.ConnectAWallet] = "Connect a Wallet",
        [Contract.ConnectWalletMessage] = "Use the wallet button in the navbar to connect a wallet for sending transactions.",
        [Contract.ChainAddedSwitched] = "Chain added/switched in wallet",
        [Contract.FailedAddChain] = "Failed to add chain: {0}",
        [Contract.Log] = "Log",
        [Contract.Index] = "Index:",
        [Contract.Topic] = "Topic:",

        // MUD Worlds
        [MudWorlds.Title] = "MUD Worlds",
        [MudWorlds.LoadingWorlds] = "Loading MUD Worlds...",
        [MudWorlds.NoWorldsFound] = "No MUD Worlds Found",
        [MudWorlds.NoWorldsSubtitle] = "No MUD World contracts have been indexed yet. Deploy a World and ensure the indexer is running.",
        [MudWorlds.WorldContract] = "World Contract",
        [MudWorlds.Tables] = "Tables",
        [MudWorlds.Records] = "Records",
        [MudWorlds.BrowseTables] = "Browse Tables",

        // MUD Tables
        [MudTables.Title] = "MUD Tables",
        [MudTables.World] = "World:",
        [MudTables.SelectWorldAddress] = "Select World Address",
        [MudTables.SelectAWorld] = "Select a World...",
        [MudTables.LoadingTables] = "Loading tables...",
        [MudTables.NoTablesFound] = "No Tables Found",
        [MudTables.NoTablesSubtitle] = "No MUD tables have been indexed for this World contract.",
        [MudTables.KeyFields] = "Key Fields",
        [MudTables.ValueFields] = "Value Fields",
        [MudTables.BrowseRecords] = "Browse Records",
        [MudTables.Unnamed] = "unnamed",

        // MUD Records
        [MudRecords.Title] = "MUD Records",
        [MudRecords.WorldAddress] = "World Address",
        [MudRecords.TableLabel] = "Table",
        [MudRecords.AllTables] = "All Tables",
        [MudRecords.RecordsCount] = "{0} records",
        [MudRecords.LoadingRecords] = "Loading records...",
        [MudRecords.QueryFilters] = "Query Filters",
        [MudRecords.Clear] = "Clear",
        [MudRecords.AddFilter] = "Add Filter",
        [MudRecords.FieldPlaceholder] = "Field...",
        [MudRecords.ValuePlaceholder] = "Value...",
        [MudRecords.OrderBy] = "Order by...",
        [MudRecords.QueryButton] = "Query",
        [MudRecords.NoResults] = "No Results",
        [MudRecords.NoResultsSubtitle] = "No records match your query filters. Try adjusting or clearing the filters.",
        [MudRecords.StaticData] = "Static Data",
        [MudRecords.DynamicData] = "Dynamic Data",
        [MudRecords.Key] = "Key",
        [MudRecords.Active] = "Active",
        [MudRecords.NoRecords] = "No Records",
        [MudRecords.NoRecordsSubtitle] = "No records found for this selection.",
        [MudRecords.SelectAWorld] = "Select a World",
        [MudRecords.SelectAWorldSubtitle] = "Choose a World address to browse MUD store records.",
        [MudRecords.FailedToLoadRecords] = "Failed to load records. Please try again.",
        [MudRecords.QueryFailed] = "Query failed. Please try again.",
        [MudRecords.KeyField] = "Key field",

        // Errors
        [Errors.PageNotFound] = "Page Not Found",
        [Errors.PageNotFoundMessage] = "The page you're looking for doesn't exist or has been moved.",
        [Errors.BackToDashboard] = "Back to Dashboard",
        [Errors.SomethingWentWrong] = "Something went wrong",
        [Errors.UnexpectedError] = "An unexpected error occurred. Please try refreshing the page or navigating back to the dashboard.",
        [Errors.ErrorDetails] = "Error Details",
        [Errors.UnhandledError] = "An unhandled error has occurred.",
        [Errors.Reload] = "Reload",

        // Contract List
        [ContractList.Title] = "Contracts",
        [ContractList.NoContractsIndexed] = "No contracts indexed yet",
        [ContractList.ContractsWillAppear] = "Contracts will appear here as they are deployed and processed by the indexer.",
        [ContractList.Creator] = "Creator",
        [ContractList.CreationTx] = "Creation Tx",
        [ContractList.IndexedAt] = "Indexed At",

        // Account List
        [AccountList.Title] = "Accounts",
        [AccountList.NoAccountsIndexed] = "No accounts indexed yet",
        [AccountList.AccountsWillAppear] = "Accounts will appear here as transactions are processed by the indexer.",
        [AccountList.EOA] = "EOA",

        // Nav
        [Nav.Dashboard] = "Dashboard",
        [Nav.Blocks] = "Blocks",
        [Nav.Txns] = "Txns",
        [Nav.Contracts] = "Contracts",
        [Nav.AccountsNav] = "Accounts",
        [Nav.Worlds] = "Worlds",
        [Nav.Tables] = "Tables",
        [Nav.Records] = "Records",
        [Nav.English] = "English",
        [Nav.Spanish] = "Spanish",
        [Nav.ExplorerTitle] = "Nethereum Explorer",
        [Nav.PoweredBy] = "Powered by Nethereum",

        // Event Log
        [EventLog.LogNumber] = "Log #{0}",
        [EventLog.DecodedParameters] = "Decoded Parameters",

        // Decoded Params
        [DecodedParams.Unknown] = "unknown",

        // Debugger
        [Debugger.Title] = "EVM Transaction Debugger",
        [Debugger.Debug] = "Debug",
        [Debugger.ReplayingTransaction] = "Replaying transaction...",
        [Debugger.ReplayingSubtitle] = "Fetching state and executing bytecode via EVM simulator.",
        [Debugger.ReplayFailed] = "Transaction Replay Failed",
        [Debugger.BackToTransaction] = "Back to Transaction",
        [Debugger.Reverted] = "This transaction reverted during execution.",

        // Pending Transactions
        [PendingTx.Title] = "Pending Transactions",
        [PendingTx.PendingTab] = "Pending",
        [PendingTx.QueuedTab] = "Queued",
        [PendingTx.NoPending] = "No Pending Transactions",
        [PendingTx.NoPendingSubtitle] = "The transaction pool is currently empty.",
        [PendingTx.NoQueued] = "No Queued Transactions",
        [PendingTx.NotSupported] = "Transaction Pool Not Available",
        [PendingTx.NotSupportedSubtitle] = "The connected node does not support txpool_content.",
        [PendingTx.LoadingPending] = "Loading pending transactions...",
        [PendingTx.Refresh] = "Refresh",

        [Shared.ExportCsv] = "Export to CSV",
        [Shared.ErrorLoadingData] = "An error occurred while loading data. Please try again.",
        [Shared.All] = "All",
        [Shared.Incoming] = "IN",
        [Shared.Outgoing] = "OUT",
        [Shared.Self] = "SELF",
        [Contract.ContractName] = "Name",
        [Contract.Proxy] = "Proxy",
        [Contract.AddToWallet] = "Add to Wallet",
        [Contract.Wallet] = "Wallet",
        [Contract.LoadingContract] = "Loading...",
        [Contract.LoadingTransactions] = "Loading transactions...",
        [Debugger.RenderingError] = "Debugger rendering error",
        [BlockDetail.ErrorOccurred] = "An error occurred while loading block details. Please try again.",
        [BlockDetail.Create] = "CREATE",
        [TransactionDetail.ErrorOccurred] = "An error occurred while loading transaction details. Please try again.",
    };
}
