using static Nethereum.Explorer.Services.Localization.ExplorerKeys;

namespace Nethereum.Explorer.Services.Localization;

public static class ExplorerStrings_es
{
    public static Dictionary<string, string> All => new()
    {
        // Search
        [Search.Placeholder] = "Buscar por Direcci\u00f3n / Hash Tx / Bloque",
        [Search.GoToBlock] = "Ir al Bloque #{0}",
        [Search.GoToAddress] = "Ir a Direcci\u00f3n",
        [Search.TxOrBlockHash] = "Hash de Transacci\u00f3n o Bloque",
        [Search.HexValue] = "Valor hex ({0} car\u00e1cteres)",
        [Search.SearchLabel] = "Buscar",
        [Search.RecentSearches] = "B\u00fasquedas Recientes",

        // Shared
        [Shared.Page] = "P\u00e1gina",
        [Shared.PageOf] = "de",
        [Shared.NoData] = "Sin datos",
        [Shared.Loading] = "Cargando...",
        [Shared.CopiedToClipboard] = "Copiado al portapapeles",
        [Shared.CopyToClipboard] = "Copiar al portapapeles",
        [Shared.FirstPage] = "Primera p\u00e1gina",
        [Shared.LastPage] = "\u00daltima p\u00e1gina",
        [Shared.ViewAll] = "Ver Todo",
        [Shared.Retry] = "Reintentar",
        [Shared.Total] = "total",
        [Shared.Updated] = "Actualizado",

        // Table columns
        [Table.TxHash] = "Hash Tx",
        [Table.Method] = "M\u00e9todo",
        [Table.Block] = "Bloque",
        [Table.Age] = "Edad",
        [Table.From] = "De",
        [Table.To] = "A",
        [Table.Value] = "Valor",
        [Table.TxFee] = "Comisi\u00f3n Tx",
        [Table.Depth] = "Prof.",
        [Table.Type] = "Tipo",
        [Table.GasUsed] = "Gas Usado",
        [Table.ContractCreation] = "Creaci\u00f3n de Contrato",
        [Table.Revert] = "Revertir:",
        [Table.CallData] = "Datos de Llamada:",
        [Table.Input] = "Entrada:",
        [Table.Output] = "Salida:",
        [Table.Name] = "Nombre",
        [Table.Indexed] = "indexado",
        [Table.Number] = "#",
        [Table.Contract] = "Contrato",
        [Table.Balance] = "Saldo",
        [Table.Amount] = "Cantidad",
        [Table.TokenId] = "ID Token",
        [Table.AmountOrTokenId] = "Cantidad / ID Token",
        [Table.LastUpdated] = "\u00daltima Actualizaci\u00f3n",
        [Table.Token] = "Token",
        [Table.Txns] = "Txns",
        [Table.GasLimit] = "L\u00edmite Gas",
        [Table.Validator] = "Validador",
        [Table.Gas] = "Gas",
        [Table.Status] = "Estado",
        [Table.Collection] = "Colecci\u00f3n",

        // Home
        [Home.Title] = "Explorador Nethereum",
        [Home.Dashboard] = "Panel de Control",
        [Home.LatestBlock] = "\u00daltimo Bloque",
        [Home.TotalTransactions] = "Total de Transacciones",
        [Home.ChainId] = "ID de Cadena",
        [Home.AddToWallet] = "Agregar a Billetera",
        [Home.LatestBlocks] = "\u00daltimos Bloques",
        [Home.LatestTransactions] = "\u00daltimas Transacciones",
        [Home.NoBlocksYet] = "Sin bloques a\u00fan",
        [Home.WaitingForBlocks] = "Esperando bloques indexados.",
        [Home.NoTransactionsYet] = "Sin transacciones a\u00fan",
        [Home.WaitingForTransactions] = "Esperando transacciones indexadas.",

        // Blocks
        [Blocks.Title] = "Bloques",
        [Blocks.NoBlocksIndexed] = "Sin bloques indexados a\u00fan",
        [Blocks.BlocksWillAppear] = "Los bloques aparecer\u00e1n aqu\u00ed a medida que el indexador los procese.",

        // Block Detail
        [BlockDetail.Title] = "Bloque",
        [BlockDetail.LoadingBlock] = "Cargando bloque...",
        [BlockDetail.FailedToLoad] = "Error al cargar bloque",
        [BlockDetail.NotFound] = "Bloque {0} no encontrado",
        [BlockDetail.NotIndexedYet] = "El bloque puede no haber sido indexado a\u00fan.",
        [BlockDetail.Overview] = "Resumen",
        [BlockDetail.BlockNumber] = "N\u00famero de Bloque",
        [BlockDetail.Timestamp] = "Marca de Tiempo",
        [BlockDetail.Transactions] = "Transacciones",
        [BlockDetail.TransactionsInBlock] = "{0} transacciones",
        [BlockDetail.ValidatedBy] = "Validado Por",
        [BlockDetail.GasAndSize] = "Gas y Tama\u00f1o",
        [BlockDetail.Size] = "Tama\u00f1o",
        [BlockDetail.BaseFeePerGas] = "Tarifa Base por Gas",
        [BlockDetail.BurnedFees] = "Tarifas Quemadas",
        [BlockDetail.BlockReward] = "Recompensa de Bloque",
        [BlockDetail.PoADevChain] = "PoA / Cadena Dev",
        [BlockDetail.StaticReward] = "Recompensa est\u00e1tica (miner\u00eda)",
        [BlockDetail.Difficulty] = "Dificultad",
        [BlockDetail.HashesAndExtra] = "Hashes y Extra",
        [BlockDetail.Hash] = "Hash",
        [BlockDetail.ParentHash] = "Hash Padre",
        [BlockDetail.Nonce] = "Nonce",
        [BlockDetail.ExtraData] = "Datos Extra",
        [BlockDetail.StateAndReceipts] = "Estado y Recibos",
        [BlockDetail.StateRoot] = "Ra\u00edz de Estado",
        [BlockDetail.ReceiptsRoot] = "Ra\u00edz de Recibos",
        [BlockDetail.WithdrawalsRoot] = "Ra\u00edz de Retiros",
        [BlockDetail.LogsBloom] = "Bloom de Logs",
        [BlockDetail.NoTransactionsInBlock] = "Sin transacciones en este bloque",
        [BlockDetail.RawBlockData] = "Datos Brutos del Bloque",
        [BlockDetail.Details] = "Detalles",
        [BlockDetail.Prev] = "Ant",
        [BlockDetail.Next] = "Sig",
        [BlockDetail.Bytes] = "bytes",

        // Transactions
        [Transactions.Title] = "Transacciones",
        [Transactions.NoTransactionsIndexed] = "Sin transacciones indexadas a\u00fan",
        [Transactions.TransactionsWillAppear] = "Las transacciones aparecer\u00e1n aqu\u00ed a medida que el indexador las procese.",

        // Transaction Detail
        [TransactionDetail.Title] = "Transacci\u00f3n",
        [TransactionDetail.LoadingTransaction] = "Cargando transacci\u00f3n...",
        [TransactionDetail.FailedToLoad] = "Error al cargar transacci\u00f3n",
        [TransactionDetail.NotFound] = "Transacci\u00f3n no encontrada",
        [TransactionDetail.TransactionDetails] = "Detalles de Transacci\u00f3n",
        [TransactionDetail.Success] = "\u00c9xito",
        [TransactionDetail.Failed] = "Fallida",
        [TransactionDetail.TransactionReverted] = "Transacci\u00f3n revertida",
        [TransactionDetail.RevertReason] = "Raz\u00f3n de reversi\u00f3n:",
        [TransactionDetail.Error] = "Error:",
        [TransactionDetail.RawTransactionData] = "Datos Brutos de Transacci\u00f3n",
        [TransactionDetail.Overview] = "Resumen",
        [TransactionDetail.TransactionHash] = "Hash de Transacci\u00f3n",
        [TransactionDetail.Timestamp] = "Marca de Tiempo",
        [TransactionDetail.TransactionFee] = "Comisi\u00f3n de Transacci\u00f3n",
        [TransactionDetail.GasAndFees] = "Gas y Comisiones",
        [TransactionDetail.CumulativeGas] = "Gas Acumulado",
        [TransactionDetail.GasPrice] = "Precio de Gas",
        [TransactionDetail.MaxFeePerGas] = "Comisi\u00f3n M\u00e1x. por Gas",
        [TransactionDetail.MaxPriorityFee] = "Comisi\u00f3n Prioritaria M\u00e1x.",
        [TransactionDetail.OtherAttributes] = "Otros Atributos",
        [TransactionDetail.TransactionType] = "Tipo de Transacci\u00f3n",
        [TransactionDetail.PositionInBlock] = "Posici\u00f3n en Bloque",
        [TransactionDetail.BlockHash] = "Hash del Bloque",
        [TransactionDetail.ReceiptHash] = "Hash del Recibo",
        [TransactionDetail.TokenTransfers] = "Transferencias de Tokens",
        [TransactionDetail.InternalTransactions] = "Transacciones Internas",
        [TransactionDetail.BlobData] = "Datos Blob (EIP-4844)",
        [TransactionDetail.MaxFeePerBlobGas] = "Comisi\u00f3n M\u00e1x. por Gas Blob",
        [TransactionDetail.BlobCount] = "Cantidad de Blobs",
        [TransactionDetail.BlobVersionedHashes] = "Hashes Versionados de Blob",
        [TransactionDetail.AuthorizationList] = "Lista de Autorizaciones (EIP-7702)",
        [TransactionDetail.AuthorizedAddress] = "Direcci\u00f3n Autorizada",
        [TransactionDetail.Signature] = "Firma",
        [TransactionDetail.StateChanges] = "Cambios de Estado",
        [TransactionDetail.Accounts] = "{0} cuentas",
        [TransactionDetail.ViaPrestateTracer] = "(v\u00eda simulaci\u00f3n prestateTracer)",
        [TransactionDetail.CodeChanged] = "C\u00f3digo Modificado",
        [TransactionDetail.StorageSlots] = "Almacenamiento ({0} slots):",
        [TransactionDetail.New] = "(nuevo)",
        [TransactionDetail.Deleted] = "(eliminado)",
        [TransactionDetail.AndMore] = "... y {0} m\u00e1s",
        [TransactionDetail.LoadingStateDiff] = "Cargando diferencia de estado...",
        [TransactionDetail.StateDiffUnavailable] = "Diferencia de estado no disponible: {0}",
        [TransactionDetail.LoadStateChanges] = "Cargar Cambios de Estado",
        [TransactionDetail.SimulatesTransaction] = "Simula la transacci\u00f3n usando prestateTracer. Requiere un nodo hist\u00f3rico/archivo.",
        [TransactionDetail.InputData] = "Datos de Entrada",
        [TransactionDetail.DecodedParameters] = "Par\u00e1metros Decodificados",
        [TransactionDetail.RawInput] = "Entrada Bruta",
        [TransactionDetail.EventLogs] = "Logs de Eventos",

        // Account
        [Account.Title] = "Cuenta",
        [Account.ContractTitle] = "Contrato",
        [Account.Overview] = "Resumen",
        [Account.Address] = "Direcci\u00f3n",
        [Account.Nonce] = "Nonce",
        [Account.Actions] = "Acciones",
        [Account.InteractWithContract] = "Interactuar con Contrato",
        [Account.ViewAsContract] = "Ver como Contrato",
        [Account.TokenBalances] = "Saldos de Tokens",
        [Account.TokenHoldings] = "Tenencias de Tokens",
        [Account.LoadingTokens] = "Cargando tokens...",
        [Account.NftInventory] = "Inventario NFT",
        [Account.NftHoldings] = "Tenencias NFT (ERC-721)",
        [Account.LoadingNfts] = "Cargando NFTs...",
        [Account.NoTransactionsFound] = "Sin transacciones encontradas",
        [Account.NoFilteredTx] = "Sin transacciones {0} encontradas.",
        [Account.NoAddressTx] = "Sin transacciones encontradas para esta direcci\u00f3n.",
        [Account.NoInternalTransactions] = "Sin transacciones internas",
        [Account.NoFilteredItx] = "Sin transacciones internas {0} encontradas.",
        [Account.NoAddressItx] = "Sin transacciones internas encontradas para esta direcci\u00f3n.",
        [Account.LoadingTransactions] = "Cargando transacciones...",
        [Account.LoadingInternalTx] = "Cargando transacciones internas...",
        [Account.Unknown] = "Desconocido",

        // Account Tokens
        [AccountTokens.Title] = "Tokens para",
        [AccountTokens.Balances] = "Saldos",
        [AccountTokens.Nfts] = "NFTs",
        [AccountTokens.Transfers] = "Transferencias",
        [AccountTokens.TokenIndexingNotAvailable] = "Indexaci\u00f3n de tokens no disponible",
        [AccountTokens.TokenIndexingSubtitle] = "Los servicios de repositorio de tokens no est\u00e1n configurados. El host debe registrar ITokenBalanceRepository, INFTInventoryRepository, ITokenTransferLogRepository e ITokenMetadataRepository.",
        [AccountTokens.LoadingBalances] = "Cargando saldos...",
        [AccountTokens.NoTokenBalances] = "Sin saldos de tokens",
        [AccountTokens.NoTokenBalancesSubtitle] = "No se encontraron saldos de tokens indexados para esta direcci\u00f3n.",
        [AccountTokens.LoadingNfts] = "Cargando NFTs...",
        [AccountTokens.NoNfts] = "Sin NFTs",
        [AccountTokens.NoNftsSubtitle] = "No se encontr\u00f3 inventario NFT indexado para esta direcci\u00f3n.",
        [AccountTokens.LoadingTransfers] = "Cargando transferencias...",
        [AccountTokens.NoTransfers] = "Sin transferencias",
        [AccountTokens.NoTransfersSubtitle] = "No se encontraron transferencias de tokens indexadas para esta direcci\u00f3n.",
        [AccountTokens.BlockPrefix] = "Bloque",

        // Contract
        [Contract.Title] = "Contrato",
        [Contract.AbiStatus] = "Estado ABI",
        [Contract.AbiAvailable] = "ABI Disponible",
        [Contract.FunctionsEvents] = "{0} funciones, {1} eventos",
        [Contract.NoAbi] = "Sin ABI",
        [Contract.ProxyContract] = "Contrato Proxy",
        [Contract.Implementation] = "Implementaci\u00f3n:",
        [Contract.NotConnected] = "No conectada",
        [Contract.ConnectWallet] = "Conecte una billetera para interactuar con este contrato",
        [Contract.AbiJson] = "ABI JSON",
        [Contract.Bytecode] = "Bytecode",
        [Contract.BytesLabel] = "{0} bytes",
        [Contract.Collapse] = "Colapsar",
        [Contract.Expand] = "Expandir",
        [Contract.PasteAbiJson] = "Pegar ABI JSON",
        [Contract.StoreAbi] = "Guardar ABI",
        [Contract.InvalidAbiJson] = "JSON ABI inv\u00e1lido",
        [Contract.FailedToParseAbi] = "Error al analizar ABI: {0}",
        [Contract.Query] = "Consulta",
        [Contract.Transact] = "Transacci\u00f3n",
        [Contract.Events] = "Eventos",
        [Contract.SourceCode] = "C\u00f3digo Fuente",
        [Contract.EventSignatures] = "Firmas de Eventos",
        [Contract.RecentEventLogs] = "Logs de Eventos Recientes",
        [Contract.LoadEvents] = "Cargar Eventos",
        [Contract.ClickLoadEvents] = "Haga clic en \"Cargar Eventos\" para consultar los logs de eventos recientes de este contrato.",
        [Contract.NoEventsFound] = "Sin eventos encontrados",
        [Contract.NoEventsSubtitle] = "No se encontraron logs de eventos para este contrato.",
        [Contract.ContractTransactions] = "Transacciones del Contrato",
        [Contract.NoTransactionsFound] = "Sin transacciones encontradas",
        [Contract.NoContractTxSubtitle] = "No se encontraron transacciones para este contrato.",
        [Contract.ConnectAWallet] = "Conectar Billetera",
        [Contract.ConnectWalletMessage] = "Use el bot\u00f3n de billetera en la barra de navegaci\u00f3n para conectar una billetera y enviar transacciones.",
        [Contract.ChainAddedSwitched] = "Cadena agregada/cambiada en billetera",
        [Contract.FailedAddChain] = "Error al agregar cadena: {0}",
        [Contract.Log] = "Log",
        [Contract.Index] = "\u00cdndice:",
        [Contract.Topic] = "T\u00f3pico:",

        // MUD Worlds
        [MudWorlds.Title] = "Mundos MUD",
        [MudWorlds.LoadingWorlds] = "Cargando Mundos MUD...",
        [MudWorlds.NoWorldsFound] = "Sin Mundos MUD Encontrados",
        [MudWorlds.NoWorldsSubtitle] = "No se han indexado contratos de Mundo MUD a\u00fan. Despliegue un Mundo y aseg\u00farese de que el indexador est\u00e9 ejecut\u00e1ndose.",
        [MudWorlds.WorldContract] = "Contrato Mundo",
        [MudWorlds.Tables] = "Tablas",
        [MudWorlds.Records] = "Registros",
        [MudWorlds.BrowseTables] = "Explorar Tablas",

        // MUD Tables
        [MudTables.Title] = "Tablas MUD",
        [MudTables.World] = "Mundo:",
        [MudTables.SelectWorldAddress] = "Seleccionar Direcci\u00f3n del Mundo",
        [MudTables.SelectAWorld] = "Seleccione un Mundo...",
        [MudTables.LoadingTables] = "Cargando tablas...",
        [MudTables.NoTablesFound] = "Sin Tablas Encontradas",
        [MudTables.NoTablesSubtitle] = "No se han indexado tablas MUD para este contrato Mundo.",
        [MudTables.KeyFields] = "Campos Clave",
        [MudTables.ValueFields] = "Campos de Valor",
        [MudTables.BrowseRecords] = "Explorar Registros",
        [MudTables.Unnamed] = "sin nombre",

        // MUD Records
        [MudRecords.Title] = "Registros MUD",
        [MudRecords.WorldAddress] = "Direcci\u00f3n del Mundo",
        [MudRecords.TableLabel] = "Tabla",
        [MudRecords.AllTables] = "Todas las Tablas",
        [MudRecords.RecordsCount] = "{0} registros",
        [MudRecords.LoadingRecords] = "Cargando registros...",
        [MudRecords.QueryFilters] = "Filtros de Consulta",
        [MudRecords.Clear] = "Limpiar",
        [MudRecords.AddFilter] = "Agregar Filtro",
        [MudRecords.FieldPlaceholder] = "Campo...",
        [MudRecords.ValuePlaceholder] = "Valor...",
        [MudRecords.OrderBy] = "Ordenar por...",
        [MudRecords.QueryButton] = "Consultar",
        [MudRecords.NoResults] = "Sin Resultados",
        [MudRecords.NoResultsSubtitle] = "No hay registros que coincidan con sus filtros. Intente ajustar o limpiar los filtros.",
        [MudRecords.StaticData] = "Datos Est\u00e1ticos",
        [MudRecords.DynamicData] = "Datos Din\u00e1micos",
        [MudRecords.Key] = "Clave",
        [MudRecords.Active] = "Activo",
        [MudRecords.NoRecords] = "Sin Registros",
        [MudRecords.NoRecordsSubtitle] = "No se encontraron registros para esta selecci\u00f3n.",
        [MudRecords.SelectAWorld] = "Seleccione un Mundo",
        [MudRecords.SelectAWorldSubtitle] = "Elija una direcci\u00f3n de Mundo para explorar los registros del almac\u00e9n MUD.",
        [MudRecords.FailedToLoadRecords] = "Error al cargar registros. Inténtelo de nuevo.",
        [MudRecords.QueryFailed] = "Consulta fallida. Inténtelo de nuevo.",
        [MudRecords.KeyField] = "Campo clave",

        // Errors
        [Errors.PageNotFound] = "P\u00e1gina No Encontrada",
        [Errors.PageNotFoundMessage] = "La p\u00e1gina que busca no existe o ha sido movida.",
        [Errors.BackToDashboard] = "Volver al Panel",
        [Errors.SomethingWentWrong] = "Algo sali\u00f3 mal",
        [Errors.UnexpectedError] = "Ocurri\u00f3 un error inesperado. Por favor intente actualizar la p\u00e1gina o volver al panel de control.",
        [Errors.ErrorDetails] = "Detalles del Error",
        [Errors.UnhandledError] = "Ha ocurrido un error no controlado.",
        [Errors.Reload] = "Recargar",

        // Contract List
        [ContractList.Title] = "Contratos",
        [ContractList.NoContractsIndexed] = "Sin contratos indexados a\u00fan",
        [ContractList.ContractsWillAppear] = "Los contratos aparecer\u00e1n aqu\u00ed a medida que se desplieguen y el indexador los procese.",
        [ContractList.Creator] = "Creador",
        [ContractList.CreationTx] = "Tx de Creaci\u00f3n",
        [ContractList.IndexedAt] = "Indexado En",

        // Account List
        [AccountList.Title] = "Cuentas",
        [AccountList.NoAccountsIndexed] = "Sin cuentas indexadas a\u00fan",
        [AccountList.AccountsWillAppear] = "Las cuentas aparecer\u00e1n aqu\u00ed a medida que el indexador procese las transacciones.",
        [AccountList.EOA] = "EOA",

        // Nav
        [Nav.Dashboard] = "Panel",
        [Nav.Blocks] = "Bloques",
        [Nav.Txns] = "Txns",
        [Nav.Contracts] = "Contratos",
        [Nav.AccountsNav] = "Cuentas",
        [Nav.Worlds] = "Mundos",
        [Nav.Tables] = "Tablas",
        [Nav.Records] = "Registros",
        [Nav.English] = "Inglés",
        [Nav.Spanish] = "Español",
        [Nav.ExplorerTitle] = "Explorador Nethereum",
        [Nav.PoweredBy] = "Desarrollado con Nethereum",

        // Event Log
        [EventLog.LogNumber] = "Log #{0}",
        [EventLog.DecodedParameters] = "Par\u00e1metros Decodificados",

        // Decoded Params
        [DecodedParams.Unknown] = "desconocido",

        // Debugger
        [Debugger.Title] = "Depurador de Transacciones EVM",
        [Debugger.Debug] = "Depurar",
        [Debugger.ReplayingTransaction] = "Reproduciendo transacci\u00f3n...",
        [Debugger.ReplayingSubtitle] = "Obteniendo estado y ejecutando bytecode via simulador EVM.",
        [Debugger.ReplayFailed] = "Fall\u00f3 la Reproducci\u00f3n de la Transacci\u00f3n",
        [Debugger.BackToTransaction] = "Volver a la Transacci\u00f3n",
        [Debugger.Reverted] = "Esta transacci\u00f3n se revert\u00ed durante la ejecuci\u00f3n.",

        // Pending Transactions
        [PendingTx.Title] = "Transacciones Pendientes",
        [PendingTx.PendingTab] = "Pendientes",
        [PendingTx.QueuedTab] = "En Cola",
        [PendingTx.NoPending] = "Sin Transacciones Pendientes",
        [PendingTx.NoPendingSubtitle] = "El pool de transacciones est\u00e1 vac\u00edo.",
        [PendingTx.NoQueued] = "Sin Transacciones en Cola",
        [PendingTx.NotSupported] = "Pool de Transacciones No Disponible",
        [PendingTx.NotSupportedSubtitle] = "El nodo conectado no soporta txpool_content.",
        [PendingTx.LoadingPending] = "Cargando transacciones pendientes...",
        [PendingTx.Refresh] = "Actualizar",

        [Shared.ExportCsv] = "Exportar a CSV",
        [Shared.ErrorLoadingData] = "Ocurri\u00f3 un error al cargar los datos. Int\u00e9ntelo de nuevo.",
        [Shared.All] = "Todos",
        [Shared.Incoming] = "ENT",
        [Shared.Outgoing] = "SAL",
        [Shared.Self] = "PROPIO",
        [Contract.ContractName] = "Nombre",
        [Contract.Proxy] = "Proxy",
        [Contract.AddToWallet] = "A\u00f1adir a Wallet",
        [Contract.Wallet] = "Wallet",
        [Contract.LoadingContract] = "Cargando...",
        [Contract.LoadingTransactions] = "Cargando transacciones...",
        [Debugger.RenderingError] = "Error de renderizado del depurador",
        [BlockDetail.ErrorOccurred] = "Ocurri\u00f3 un error al cargar los detalles del bloque. Int\u00e9ntelo de nuevo.",
        [BlockDetail.Create] = "CREATE",
        [TransactionDetail.ErrorOccurred] = "Ocurri\u00f3 un error al cargar los detalles de la transacci\u00f3n. Int\u00e9ntelo de nuevo.",
    };
}
