CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AccountStates" (
    "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
    "Address" character varying(43) NOT NULL,
    "Balance" character varying(100),
    "Nonce" character varying(100),
    "IsContract" boolean NOT NULL,
    "LastUpdatedBlock" character varying(100),
    "RowCreated" timestamp with time zone,
    "RowUpdated" timestamp with time zone,
    CONSTRAINT "PK_AccountStates" PRIMARY KEY ("RowIndex")
);

CREATE TABLE "AddressTransactions" (
    "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
    "BlockNumber" character varying(100) NOT NULL,
    "Hash" character varying(67) NOT NULL,
    "Address" character varying(43) NOT NULL,
    "RowCreated" timestamp with time zone,
    "RowUpdated" timestamp with time zone,
    CONSTRAINT "PK_AddressTransactions" PRIMARY KEY ("RowIndex")
);

CREATE TABLE "BlockProgress" (
    "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
    "LastBlockProcessed" character varying(100) NOT NULL,
    "RowCreated" timestamp with time zone,
    "RowUpdated" timestamp with time zone,
    CONSTRAINT "PK_BlockProgress" PRIMARY KEY ("RowIndex")
);

CREATE TABLE "Blocks" (
    "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
    "BlockNumber" character varying(100) NOT NULL,
    "Hash" character varying(67) NOT NULL,
    "ParentHash" character varying(67) NOT NULL,
    "Nonce" character varying(100),
    "ExtraData" text,
    "Difficulty" character varying(100),
    "TotalDifficulty" character varying(100),
    "Size" character varying(100),
    "Miner" character varying(43),
    "GasLimit" character varying(100),
    "GasUsed" character varying(100),
    "Timestamp" character varying(100),
    "IsCanonical" boolean NOT NULL,
    "IsFinalized" boolean NOT NULL,
    "ChainId" integer,
    "TransactionCount" bigint NOT NULL,
    "BaseFeePerGas" character varying(100),
    "RowCreated" timestamp with time zone,
    "RowUpdated" timestamp with time zone,
    CONSTRAINT "PK_Blocks" PRIMARY KEY ("RowIndex")
);

CREATE TABLE "ChainStates" (
    "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
    "LastCanonicalBlockNumber" character varying(100),
    "LastCanonicalBlockHash" character varying(67),
    "FinalizedBlockNumber" character varying(100),
    "ChainId" integer,
    "RowCreated" timestamp with time zone,
    "RowUpdated" timestamp with time zone,
    CONSTRAINT "PK_ChainStates" PRIMARY KEY ("RowIndex")
);

CREATE TABLE "Contracts" (
    "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
    "Address" character varying(43),
    "Name" character varying(255),
    "ABI" text,
    "Code" text,
    "Creator" character varying(43),
    "TransactionHash" character varying(67),
    "RowCreated" timestamp with time zone,
    "RowUpdated" timestamp with time zone,
    CONSTRAINT "PK_Contracts" PRIMARY KEY ("RowIndex")
);

CREATE TABLE "TransactionLogs" (
    "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
    "TransactionHash" character varying(67) NOT NULL,
    "LogIndex" character varying(100),
    "Address" character varying(43),
    "EventHash" character varying(67),
    "IndexVal1" character varying(67),
    "IndexVal2" character varying(67),
    "IndexVal3" character varying(67),
    "Data" text,
    "RowCreated" timestamp with time zone,
    "RowUpdated" timestamp with time zone,
    CONSTRAINT "PK_TransactionLogs" PRIMARY KEY ("RowIndex")
);

CREATE TABLE "TransactionLogVmStacks" (
    "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
    "Address" character varying(43),
    "TransactionHash" character varying(67),
    "StructLogs" text,
    "RowCreated" timestamp with time zone,
    "RowUpdated" timestamp with time zone,
    CONSTRAINT "PK_TransactionLogVmStacks" PRIMARY KEY ("RowIndex")
);

CREATE TABLE "Transactions" (
    "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
    "RowCreated" timestamp with time zone,
    "RowUpdated" timestamp with time zone,
    "BlockHash" character varying(67),
    "BlockNumber" character varying(100) NOT NULL,
    "Hash" character varying(67) NOT NULL,
    "AddressFrom" character varying(43),
    "TimeStamp" character varying(100),
    "TransactionIndex" character varying(100),
    "Value" character varying(100),
    "AddressTo" character varying(43),
    "Gas" character varying(100),
    "GasPrice" character varying(100),
    "Input" text,
    "Nonce" character varying(100),
    "Failed" boolean NOT NULL,
    "ReceiptHash" character varying(67),
    "GasUsed" character varying(100),
    "CumulativeGasUsed" character varying(100),
    "EffectiveGasPrice" character varying(100),
    "HasLog" boolean NOT NULL,
    "Error" text,
    "HasVmStack" boolean NOT NULL,
    "NewContractAddress" character varying(43),
    "FailedCreateContract" boolean NOT NULL,
    "MaxFeePerGas" character varying(100),
    "MaxPriorityFeePerGas" character varying(100),
    "IsCanonical" boolean NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("RowIndex")
);

CREATE UNIQUE INDEX "IX_AccountStates_Address" ON "AccountStates" ("Address");

CREATE INDEX "IX_AccountStates_LastUpdatedBlock" ON "AccountStates" ("LastUpdatedBlock");

CREATE INDEX "IX_AddressTransactions_Address" ON "AddressTransactions" ("Address");

CREATE INDEX "IX_AddressTransactions_Address_BlockNumber" ON "AddressTransactions" ("Address", "BlockNumber");

CREATE UNIQUE INDEX "IX_AddressTransactions_BlockNumber_Hash_Address" ON "AddressTransactions" ("BlockNumber", "Hash", "Address");

CREATE INDEX "IX_AddressTransactions_Hash" ON "AddressTransactions" ("Hash");

CREATE INDEX "IX_BlockProgress_LastBlockProcessed" ON "BlockProgress" ("LastBlockProcessed");

CREATE INDEX "IX_Blocks_BlockNumber" ON "Blocks" ("BlockNumber");

CREATE UNIQUE INDEX "IX_Blocks_BlockNumber_Hash" ON "Blocks" ("BlockNumber", "Hash");

CREATE INDEX "IX_Blocks_Hash" ON "Blocks" ("Hash");

CREATE INDEX "IX_Blocks_IsCanonical_BlockNumber" ON "Blocks" ("IsCanonical", "BlockNumber");

CREATE INDEX "IX_Blocks_ParentHash" ON "Blocks" ("ParentHash");

CREATE INDEX "IX_ChainStates_LastCanonicalBlockNumber" ON "ChainStates" ("LastCanonicalBlockNumber");

CREATE INDEX "IX_Contracts_Address" ON "Contracts" ("Address");

CREATE UNIQUE INDEX "IX_Contracts_Name" ON "Contracts" ("Name");

CREATE INDEX "IX_TransactionLogs_Address" ON "TransactionLogs" ("Address");

CREATE INDEX "IX_TransactionLogs_EventHash" ON "TransactionLogs" ("EventHash");

CREATE INDEX "IX_TransactionLogs_IndexVal1" ON "TransactionLogs" ("IndexVal1");

CREATE INDEX "IX_TransactionLogs_IndexVal2" ON "TransactionLogs" ("IndexVal2");

CREATE INDEX "IX_TransactionLogs_IndexVal3" ON "TransactionLogs" ("IndexVal3");

CREATE UNIQUE INDEX "IX_TransactionLogs_TransactionHash_LogIndex" ON "TransactionLogs" ("TransactionHash", "LogIndex");

CREATE INDEX "IX_TransactionLogVmStacks_Address" ON "TransactionLogVmStacks" ("Address");

CREATE INDEX "IX_TransactionLogVmStacks_TransactionHash" ON "TransactionLogVmStacks" ("TransactionHash");

CREATE INDEX "IX_Transactions_AddressFrom" ON "Transactions" ("AddressFrom");

CREATE INDEX "IX_Transactions_AddressTo" ON "Transactions" ("AddressTo");

CREATE UNIQUE INDEX "IX_Transactions_BlockNumber_Hash" ON "Transactions" ("BlockNumber", "Hash");

CREATE INDEX "IX_Transactions_Hash" ON "Transactions" ("Hash");

CREATE INDEX "IX_Transactions_IsCanonical_BlockNumber" ON "Transactions" ("IsCanonical", "BlockNumber");

CREATE INDEX "IX_Transactions_NewContractAddress" ON "Transactions" ("NewContractAddress");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260208085824_InitialCreate', '8.0.10');

COMMIT;

