CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migrationid character varying(150) NOT NULL,
    productversion character varying(32) NOT NULL,
    CONSTRAINT pk___efmigrationshistory PRIMARY KEY (migrationid)
);

START TRANSACTION;
CREATE TABLE "AccountStates" (
    rowindex integer GENERATED BY DEFAULT AS IDENTITY,
    address character varying(43) NOT NULL,
    balance character varying(100),
    nonce character varying(100),
    iscontract boolean NOT NULL,
    lastupdatedblock character varying(100),
    rowcreated timestamp with time zone,
    rowupdated timestamp with time zone,
    CONSTRAINT pk_accountstates PRIMARY KEY (rowindex)
);

CREATE TABLE "AddressTransactions" (
    rowindex integer GENERATED BY DEFAULT AS IDENTITY,
    blocknumber character varying(100) NOT NULL,
    hash character varying(67) NOT NULL,
    address character varying(43) NOT NULL,
    rowcreated timestamp with time zone,
    rowupdated timestamp with time zone,
    CONSTRAINT pk_addresstransactions PRIMARY KEY (rowindex)
);

CREATE TABLE "BlockProgress" (
    rowindex integer GENERATED BY DEFAULT AS IDENTITY,
    lastblockprocessed character varying(100) NOT NULL,
    rowcreated timestamp with time zone,
    rowupdated timestamp with time zone,
    CONSTRAINT pk_blockprogress PRIMARY KEY (rowindex)
);

CREATE TABLE "Blocks" (
    rowindex integer GENERATED BY DEFAULT AS IDENTITY,
    blocknumber character varying(100) NOT NULL,
    hash character varying(67) NOT NULL,
    parenthash character varying(67) NOT NULL,
    nonce character varying(100),
    extradata text,
    difficulty character varying(100),
    totaldifficulty character varying(100),
    size character varying(100),
    miner character varying(43),
    gaslimit character varying(100),
    gasused character varying(100),
    timestamp character varying(100),
    iscanonical boolean NOT NULL,
    isfinalized boolean NOT NULL,
    chainid integer,
    transactioncount bigint NOT NULL,
    basefeepergas character varying(100),
    rowcreated timestamp with time zone,
    rowupdated timestamp with time zone,
    CONSTRAINT pk_blocks PRIMARY KEY (rowindex)
);

CREATE TABLE "ChainStates" (
    rowindex integer GENERATED BY DEFAULT AS IDENTITY,
    lastcanonicalblocknumber character varying(100),
    lastcanonicalblockhash character varying(67),
    finalizedblocknumber character varying(100),
    chainid integer,
    rowcreated timestamp with time zone,
    rowupdated timestamp with time zone,
    CONSTRAINT pk_chainstates PRIMARY KEY (rowindex)
);

CREATE TABLE "Contracts" (
    rowindex integer GENERATED BY DEFAULT AS IDENTITY,
    address character varying(43),
    name character varying(255),
    abi text,
    code text,
    creator character varying(43),
    transactionhash character varying(67),
    rowcreated timestamp with time zone,
    rowupdated timestamp with time zone,
    CONSTRAINT pk_contracts PRIMARY KEY (rowindex)
);

CREATE TABLE "TransactionLogs" (
    rowindex integer GENERATED BY DEFAULT AS IDENTITY,
    transactionhash character varying(67) NOT NULL,
    logindex character varying(100),
    address character varying(43),
    eventhash character varying(67),
    indexval1 character varying(67),
    indexval2 character varying(67),
    indexval3 character varying(67),
    data text,
    rowcreated timestamp with time zone,
    rowupdated timestamp with time zone,
    CONSTRAINT pk_transactionlogs PRIMARY KEY (rowindex)
);

CREATE TABLE "TransactionLogVmStacks" (
    rowindex integer GENERATED BY DEFAULT AS IDENTITY,
    address character varying(43),
    transactionhash character varying(67),
    structlogs text,
    rowcreated timestamp with time zone,
    rowupdated timestamp with time zone,
    CONSTRAINT pk_transactionlogvmstacks PRIMARY KEY (rowindex)
);

CREATE TABLE "Transactions" (
    rowindex integer GENERATED BY DEFAULT AS IDENTITY,
    rowcreated timestamp with time zone,
    rowupdated timestamp with time zone,
    blockhash character varying(67),
    blocknumber character varying(100) NOT NULL,
    hash character varying(67) NOT NULL,
    addressfrom character varying(43),
    timestamp character varying(100),
    transactionindex character varying(100),
    value character varying(100),
    addressto character varying(43),
    gas character varying(100),
    gasprice character varying(100),
    input text,
    nonce character varying(100),
    failed boolean NOT NULL,
    receipthash character varying(67),
    gasused character varying(100),
    cumulativegasused character varying(100),
    effectivegasprice character varying(100),
    haslog boolean NOT NULL,
    error text,
    hasvmstack boolean NOT NULL,
    newcontractaddress character varying(43),
    failedcreatecontract boolean NOT NULL,
    maxfeepergas character varying(100),
    maxpriorityfeepergas character varying(100),
    iscanonical boolean NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (rowindex)
);

CREATE UNIQUE INDEX ix_accountstates_address ON "AccountStates" (address);

CREATE INDEX ix_accountstates_lastupdatedblock ON "AccountStates" (lastupdatedblock);

CREATE INDEX ix_addresstransactions_address ON "AddressTransactions" (address);

CREATE INDEX ix_addresstransactions_address_blocknumber ON "AddressTransactions" (address, blocknumber);

CREATE UNIQUE INDEX ix_addresstransactions_blocknumber_hash_address ON "AddressTransactions" (blocknumber, hash, address);

CREATE INDEX ix_addresstransactions_hash ON "AddressTransactions" (hash);

CREATE INDEX ix_blockprogress_lastblockprocessed ON "BlockProgress" (lastblockprocessed);

CREATE INDEX ix_blocks_blocknumber ON "Blocks" (blocknumber);

CREATE UNIQUE INDEX ix_blocks_blocknumber_hash ON "Blocks" (blocknumber, hash);

CREATE INDEX ix_blocks_hash ON "Blocks" (hash);

CREATE INDEX ix_blocks_iscanonical_blocknumber ON "Blocks" (iscanonical, blocknumber);

CREATE INDEX ix_blocks_parenthash ON "Blocks" (parenthash);

CREATE INDEX ix_chainstates_lastcanonicalblocknumber ON "ChainStates" (lastcanonicalblocknumber);

CREATE INDEX ix_contracts_address ON "Contracts" (address);

CREATE UNIQUE INDEX ix_contracts_name ON "Contracts" (name);

CREATE INDEX ix_transactionlogs_address ON "TransactionLogs" (address);

CREATE INDEX ix_transactionlogs_eventhash ON "TransactionLogs" (eventhash);

CREATE INDEX ix_transactionlogs_indexval1 ON "TransactionLogs" (indexval1);

CREATE INDEX ix_transactionlogs_indexval2 ON "TransactionLogs" (indexval2);

CREATE INDEX ix_transactionlogs_indexval3 ON "TransactionLogs" (indexval3);

CREATE UNIQUE INDEX ix_transactionlogs_transactionhash_logindex ON "TransactionLogs" (transactionhash, logindex);

CREATE INDEX ix_transactionlogvmstacks_address ON "TransactionLogVmStacks" (address);

CREATE INDEX ix_transactionlogvmstacks_transactionhash ON "TransactionLogVmStacks" (transactionhash);

CREATE INDEX ix_transactions_addressfrom ON "Transactions" (addressfrom);

CREATE INDEX ix_transactions_addressto ON "Transactions" (addressto);

CREATE UNIQUE INDEX ix_transactions_blocknumber_hash ON "Transactions" (blocknumber, hash);

CREATE INDEX ix_transactions_hash ON "Transactions" (hash);

CREATE INDEX ix_transactions_iscanonical_blocknumber ON "Transactions" (iscanonical, blocknumber);

CREATE INDEX ix_transactions_newcontractaddress ON "Transactions" (newcontractaddress);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20260208101046_InitialCreate', '10.0.1');

COMMIT;

