<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Nethereum.Freezer Unit + Conformance Tests</Description>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Nethereum.Freezer.UnitTests</AssemblyName>
    <PackageId>Nethereum.Freezer.UnitTests</PackageId>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\NethereumKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nethereum.Freezer\Nethereum.Freezer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.4" />
  </ItemGroup>

</Project>
