// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: messages-crypto.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hw.trezor.messages.crypto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CipherKeyValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"key", IsRequired = true)]
        public string Key { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"value", IsRequired = true)]
        public byte[] Value { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"encrypt")]
        public bool Encrypt
        {
            get => __pbn__Encrypt.GetValueOrDefault();
            set => __pbn__Encrypt = value;
        }
        public bool ShouldSerializeEncrypt() => __pbn__Encrypt != null;
        public void ResetEncrypt() => __pbn__Encrypt = null;
        private bool? __pbn__Encrypt;

        [global::ProtoBuf.ProtoMember(5, Name = @"ask_on_encrypt")]
        public bool AskOnEncrypt
        {
            get => __pbn__AskOnEncrypt.GetValueOrDefault();
            set => __pbn__AskOnEncrypt = value;
        }
        public bool ShouldSerializeAskOnEncrypt() => __pbn__AskOnEncrypt != null;
        public void ResetAskOnEncrypt() => __pbn__AskOnEncrypt = null;
        private bool? __pbn__AskOnEncrypt;

        [global::ProtoBuf.ProtoMember(6, Name = @"ask_on_decrypt")]
        public bool AskOnDecrypt
        {
            get => __pbn__AskOnDecrypt.GetValueOrDefault();
            set => __pbn__AskOnDecrypt = value;
        }
        public bool ShouldSerializeAskOnDecrypt() => __pbn__AskOnDecrypt != null;
        public void ResetAskOnDecrypt() => __pbn__AskOnDecrypt = null;
        private bool? __pbn__AskOnDecrypt;

        [global::ProtoBuf.ProtoMember(7, Name = @"iv")]
        public byte[] Iv
        {
            get => __pbn__Iv;
            set => __pbn__Iv = value;
        }
        public bool ShouldSerializeIv() => __pbn__Iv != null;
        public void ResetIv() => __pbn__Iv = null;
        private byte[] __pbn__Iv;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CipheredKeyValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value", IsRequired = true)]
        public byte[] Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IdentityType : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"proto")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Proto
        {
            get => __pbn__Proto ?? "";
            set => __pbn__Proto = value;
        }
        public bool ShouldSerializeProto() => __pbn__Proto != null;
        public void ResetProto() => __pbn__Proto = null;
        private string __pbn__Proto;

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        [global::System.ComponentModel.DefaultValue("")]
        public string User
        {
            get => __pbn__User ?? "";
            set => __pbn__User = value;
        }
        public bool ShouldSerializeUser() => __pbn__User != null;
        public void ResetUser() => __pbn__User = null;
        private string __pbn__User;

        [global::ProtoBuf.ProtoMember(3, Name = @"host")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Host
        {
            get => __pbn__Host ?? "";
            set => __pbn__Host = value;
        }
        public bool ShouldSerializeHost() => __pbn__Host != null;
        public void ResetHost() => __pbn__Host = null;
        private string __pbn__Host;

        [global::ProtoBuf.ProtoMember(4, Name = @"port")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Port
        {
            get => __pbn__Port ?? "";
            set => __pbn__Port = value;
        }
        public bool ShouldSerializePort() => __pbn__Port != null;
        public void ResetPort() => __pbn__Port = null;
        private string __pbn__Port;

        [global::ProtoBuf.ProtoMember(5, Name = @"path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Path
        {
            get => __pbn__Path ?? "";
            set => __pbn__Path = value;
        }
        public bool ShouldSerializePath() => __pbn__Path != null;
        public void ResetPath() => __pbn__Path = null;
        private string __pbn__Path;

        [global::ProtoBuf.ProtoMember(6, Name = @"index")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint Index
        {
            get => __pbn__Index ?? 0u;
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private uint? __pbn__Index;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SignIdentity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity", IsRequired = true)]
        public IdentityType Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"challenge_hidden")]
        public byte[] ChallengeHidden
        {
            get => __pbn__ChallengeHidden;
            set => __pbn__ChallengeHidden = value;
        }
        public bool ShouldSerializeChallengeHidden() => __pbn__ChallengeHidden != null;
        public void ResetChallengeHidden() => __pbn__ChallengeHidden = null;
        private byte[] __pbn__ChallengeHidden;

        [global::ProtoBuf.ProtoMember(3, Name = @"challenge_visual")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChallengeVisual
        {
            get => __pbn__ChallengeVisual ?? "";
            set => __pbn__ChallengeVisual = value;
        }
        public bool ShouldSerializeChallengeVisual() => __pbn__ChallengeVisual != null;
        public void ResetChallengeVisual() => __pbn__ChallengeVisual = null;
        private string __pbn__ChallengeVisual;

        [global::ProtoBuf.ProtoMember(4, Name = @"ecdsa_curve_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EcdsaCurveName
        {
            get => __pbn__EcdsaCurveName ?? "";
            set => __pbn__EcdsaCurveName = value;
        }
        public bool ShouldSerializeEcdsaCurveName() => __pbn__EcdsaCurveName != null;
        public void ResetEcdsaCurveName() => __pbn__EcdsaCurveName = null;
        private string __pbn__EcdsaCurveName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SignedIdentity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address
        {
            get => __pbn__Address ?? "";
            set => __pbn__Address = value;
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private string __pbn__Address;

        [global::ProtoBuf.ProtoMember(2, Name = @"public_key", IsRequired = true)]
        public byte[] PublicKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"signature", IsRequired = true)]
        public byte[] Signature { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetECDHSessionKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identity", IsRequired = true)]
        public IdentityType Identity { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"peer_public_key", IsRequired = true)]
        public byte[] PeerPublicKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ecdsa_curve_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EcdsaCurveName
        {
            get => __pbn__EcdsaCurveName ?? "";
            set => __pbn__EcdsaCurveName = value;
        }
        public bool ShouldSerializeEcdsaCurveName() => __pbn__EcdsaCurveName != null;
        public void ResetEcdsaCurveName() => __pbn__EcdsaCurveName = null;
        private string __pbn__EcdsaCurveName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ECDHSessionKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_key", IsRequired = true)]
        public byte[] SessionKey { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"public_key")]
        public byte[] PublicKey
        {
            get => __pbn__PublicKey;
            set => __pbn__PublicKey = value;
        }
        public bool ShouldSerializePublicKey() => __pbn__PublicKey != null;
        public void ResetPublicKey() => __pbn__PublicKey = null;
        private byte[] __pbn__PublicKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PaymentNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"payment_req")]
        public global::hw.trezor.messages.common.PaymentRequest PaymentReq { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
