// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: messages-common.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hw.trezor.messages.common
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Success : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get => __pbn__Message ?? "";
            set => __pbn__Message = value;
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Failure : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code")]
        [global::System.ComponentModel.DefaultValue(FailureType.FailureUnexpectedMessage)]
        public FailureType Code
        {
            get => __pbn__Code ?? FailureType.FailureUnexpectedMessage;
            set => __pbn__Code = value;
        }
        public bool ShouldSerializeCode() => __pbn__Code != null;
        public void ResetCode() => __pbn__Code = null;
        private FailureType? __pbn__Code;

        [global::ProtoBuf.ProtoMember(2, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get => __pbn__Message ?? "";
            set => __pbn__Message = value;
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

        [global::ProtoBuf.ProtoContract()]
        public enum FailureType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_UnexpectedMessage")]
            FailureUnexpectedMessage = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_ButtonExpected")]
            FailureButtonExpected = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_DataError")]
            FailureDataError = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_ActionCancelled")]
            FailureActionCancelled = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_PinExpected")]
            FailurePinExpected = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_PinCancelled")]
            FailurePinCancelled = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_PinInvalid")]
            FailurePinInvalid = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_InvalidSignature")]
            FailureInvalidSignature = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_ProcessError")]
            FailureProcessError = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_NotEnoughFunds")]
            FailureNotEnoughFunds = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_NotInitialized")]
            FailureNotInitialized = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_PinMismatch")]
            FailurePinMismatch = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_WipeCodeMismatch")]
            FailureWipeCodeMismatch = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_InvalidSession")]
            FailureInvalidSession = 14,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_Busy")]
            FailureBusy = 15,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_ThpUnallocatedSession")]
            FailureThpUnallocatedSession = 16,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_InvalidProtocol")]
            FailureInvalidProtocol = 17,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_BufferError")]
            FailureBufferError = 18,
            [global::ProtoBuf.ProtoEnum(Name = @"Failure_FirmwareError")]
            FailureFirmwareError = 99,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ButtonRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code")]
        [global::System.ComponentModel.DefaultValue(ButtonRequestType.ButtonRequestOther)]
        public ButtonRequestType Code
        {
            get => __pbn__Code ?? ButtonRequestType.ButtonRequestOther;
            set => __pbn__Code = value;
        }
        public bool ShouldSerializeCode() => __pbn__Code != null;
        public void ResetCode() => __pbn__Code = null;
        private ButtonRequestType? __pbn__Code;

        [global::ProtoBuf.ProtoMember(2, Name = @"pages")]
        public uint Pages
        {
            get => __pbn__Pages.GetValueOrDefault();
            set => __pbn__Pages = value;
        }
        public bool ShouldSerializePages() => __pbn__Pages != null;
        public void ResetPages() => __pbn__Pages = null;
        private uint? __pbn__Pages;

        [global::ProtoBuf.ProtoMember(4, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoContract()]
        public enum ButtonRequestType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_Other")]
            ButtonRequestOther = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_FeeOverThreshold")]
            ButtonRequestFeeOverThreshold = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_ConfirmOutput")]
            ButtonRequestConfirmOutput = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_ResetDevice")]
            ButtonRequestResetDevice = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_ConfirmWord")]
            ButtonRequestConfirmWord = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_WipeDevice")]
            ButtonRequestWipeDevice = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_ProtectCall")]
            ButtonRequestProtectCall = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_SignTx")]
            ButtonRequestSignTx = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_FirmwareCheck")]
            ButtonRequestFirmwareCheck = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_Address")]
            ButtonRequestAddress = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_PublicKey")]
            ButtonRequestPublicKey = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_MnemonicWordCount")]
            ButtonRequestMnemonicWordCount = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_MnemonicInput")]
            ButtonRequestMnemonicInput = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"_Deprecated_ButtonRequest_PassphraseType")]
            [global::System.Obsolete]
            DeprecatedButtonRequestPassphraseType = 14,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_UnknownDerivationPath")]
            ButtonRequestUnknownDerivationPath = 15,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_RecoveryHomepage")]
            ButtonRequestRecoveryHomepage = 16,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_Success")]
            ButtonRequestSuccess = 17,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_Warning")]
            ButtonRequestWarning = 18,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_PassphraseEntry")]
            ButtonRequestPassphraseEntry = 19,
            [global::ProtoBuf.ProtoEnum(Name = @"ButtonRequest_PinEntry")]
            ButtonRequestPinEntry = 20,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ButtonAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PinMatrixRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(PinMatrixRequestType.PinMatrixRequestTypeCurrent)]
        public PinMatrixRequestType Type
        {
            get => __pbn__Type ?? PinMatrixRequestType.PinMatrixRequestTypeCurrent;
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private PinMatrixRequestType? __pbn__Type;

        [global::ProtoBuf.ProtoContract()]
        public enum PinMatrixRequestType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PinMatrixRequestType_Current")]
            PinMatrixRequestTypeCurrent = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"PinMatrixRequestType_NewFirst")]
            PinMatrixRequestTypeNewFirst = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"PinMatrixRequestType_NewSecond")]
            PinMatrixRequestTypeNewSecond = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"PinMatrixRequestType_WipeCodeFirst")]
            PinMatrixRequestTypeWipeCodeFirst = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"PinMatrixRequestType_WipeCodeSecond")]
            PinMatrixRequestTypeWipeCodeSecond = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PinMatrixAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pin", IsRequired = true)]
        public string Pin { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PassphraseRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"_on_device")]
        [global::System.Obsolete]
        public bool OnDevice
        {
            get => __pbn__OnDevice.GetValueOrDefault();
            set => __pbn__OnDevice = value;
        }
        public bool ShouldSerializeOnDevice() => __pbn__OnDevice != null;
        public void ResetOnDevice() => __pbn__OnDevice = null;
        private bool? __pbn__OnDevice;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PassphraseAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"passphrase")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Passphrase
        {
            get => __pbn__Passphrase ?? "";
            set => __pbn__Passphrase = value;
        }
        public bool ShouldSerializePassphrase() => __pbn__Passphrase != null;
        public void ResetPassphrase() => __pbn__Passphrase = null;
        private string __pbn__Passphrase;

        [global::ProtoBuf.ProtoMember(2, Name = @"_state")]
        [global::System.Obsolete]
        public byte[] State
        {
            get => __pbn__State;
            set => __pbn__State = value;
        }
        public bool ShouldSerializeState() => __pbn__State != null;
        public void ResetState() => __pbn__State = null;
        private byte[] __pbn__State;

        [global::ProtoBuf.ProtoMember(3, Name = @"on_device")]
        public bool OnDevice
        {
            get => __pbn__OnDevice.GetValueOrDefault();
            set => __pbn__OnDevice = value;
        }
        public bool ShouldSerializeOnDevice() => __pbn__OnDevice != null;
        public void ResetOnDevice() => __pbn__OnDevice = null;
        private bool? __pbn__OnDevice;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PassphraseStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        public byte[] State
        {
            get => __pbn__State;
            set => __pbn__State = value;
        }
        public bool ShouldSerializeState() => __pbn__State != null;
        public void ResetState() => __pbn__State = null;
        private byte[] __pbn__State;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PassphraseStateAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"Deprecated_PassphraseStateRequest")]
    [global::System.Obsolete]
    public partial class DeprecatedPassphraseStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        public byte[] State
        {
            get => __pbn__State;
            set => __pbn__State = value;
        }
        public bool ShouldSerializeState() => __pbn__State != null;
        public void ResetState() => __pbn__State = null;
        private byte[] __pbn__State;

    }

    [global::ProtoBuf.ProtoContract(Name = @"Deprecated_PassphraseStateAck")]
    [global::System.Obsolete]
    public partial class DeprecatedPassphraseStateAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HDNodeType : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"depth", IsRequired = true)]
        public uint Depth { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"fingerprint", IsRequired = true)]
        public uint Fingerprint { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"child_num", IsRequired = true)]
        public uint ChildNum { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"chain_code", IsRequired = true)]
        public byte[] ChainCode { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"private_key")]
        public byte[] PrivateKey
        {
            get => __pbn__PrivateKey;
            set => __pbn__PrivateKey = value;
        }
        public bool ShouldSerializePrivateKey() => __pbn__PrivateKey != null;
        public void ResetPrivateKey() => __pbn__PrivateKey = null;
        private byte[] __pbn__PrivateKey;

        [global::ProtoBuf.ProtoMember(6, Name = @"public_key", IsRequired = true)]
        public byte[] PublicKey { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PaymentRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nonce")]
        public byte[] Nonce
        {
            get => __pbn__Nonce;
            set => __pbn__Nonce = value;
        }
        public bool ShouldSerializeNonce() => __pbn__Nonce != null;
        public void ResetNonce() => __pbn__Nonce = null;
        private byte[] __pbn__Nonce;

        [global::ProtoBuf.ProtoMember(2, Name = @"recipient_name", IsRequired = true)]
        public string RecipientName { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"memos")]
        public global::System.Collections.Generic.List<PaymentRequestMemo> Memos { get; } = new global::System.Collections.Generic.List<PaymentRequestMemo>();

        [global::ProtoBuf.ProtoMember(6, Name = @"amount")]
        public byte[] Amount
        {
            get => __pbn__Amount;
            set => __pbn__Amount = value;
        }
        public bool ShouldSerializeAmount() => __pbn__Amount != null;
        public void ResetAmount() => __pbn__Amount = null;
        private byte[] __pbn__Amount;

        [global::ProtoBuf.ProtoMember(5, Name = @"signature", IsRequired = true)]
        public byte[] Signature { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class PaymentRequestMemo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"text_memo")]
            public PaymentRequest.TextMemo TextMemo { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"refund_memo")]
            public PaymentRequest.RefundMemo RefundMemo { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"coin_purchase_memo")]
            public PaymentRequest.CoinPurchaseMemo CoinPurchaseMemo { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"text_details_memo")]
            public PaymentRequest.TextDetailsMemo TextDetailsMemo { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class TextMemo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"text", IsRequired = true)]
            public string Text { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class TextDetailsMemo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"title", IsRequired = true)]
            public string Title { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"text", IsRequired = true)]
            public string Text { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RefundMemo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"address", IsRequired = true)]
            public string Address { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"address_n")]
            public uint[] AddressNs { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"mac", IsRequired = true)]
            public byte[] Mac { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class CoinPurchaseMemo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"coin_type", IsRequired = true)]
            public uint CoinType { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"amount", IsRequired = true)]
            public string Amount { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"address", IsRequired = true)]
            public string Address { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"address_n")]
            public uint[] AddressNs { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"mac", IsRequired = true)]
            public byte[] Mac { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
