// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: messages-debug.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hw.trezor.messages.debug
{

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkDecision : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"button")]
        [global::System.ComponentModel.DefaultValue(DebugButton.No)]
        public DebugButton Button
        {
            get => __pbn__Button ?? DebugButton.No;
            set => __pbn__Button = value;
        }
        public bool ShouldSerializeButton() => __pbn__Button != null;
        public void ResetButton() => __pbn__Button = null;
        private DebugButton? __pbn__Button;

        [global::ProtoBuf.ProtoMember(2, Name = @"swipe")]
        [global::System.ComponentModel.DefaultValue(DebugSwipeDirection.Up)]
        public DebugSwipeDirection Swipe
        {
            get => __pbn__Swipe ?? DebugSwipeDirection.Up;
            set => __pbn__Swipe = value;
        }
        public bool ShouldSerializeSwipe() => __pbn__Swipe != null;
        public void ResetSwipe() => __pbn__Swipe = null;
        private DebugSwipeDirection? __pbn__Swipe;

        [global::ProtoBuf.ProtoMember(3, Name = @"input")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Input
        {
            get => __pbn__Input ?? "";
            set => __pbn__Input = value;
        }
        public bool ShouldSerializeInput() => __pbn__Input != null;
        public void ResetInput() => __pbn__Input = null;
        private string __pbn__Input;

        [global::ProtoBuf.ProtoMember(4, Name = @"x")]
        public uint X
        {
            get => __pbn__X.GetValueOrDefault();
            set => __pbn__X = value;
        }
        public bool ShouldSerializeX() => __pbn__X != null;
        public void ResetX() => __pbn__X = null;
        private uint? __pbn__X;

        [global::ProtoBuf.ProtoMember(5, Name = @"y")]
        public uint Y
        {
            get => __pbn__Y.GetValueOrDefault();
            set => __pbn__Y = value;
        }
        public bool ShouldSerializeY() => __pbn__Y != null;
        public void ResetY() => __pbn__Y = null;
        private uint? __pbn__Y;

        [global::ProtoBuf.ProtoMember(6, Name = @"wait")]
        [global::System.Obsolete]
        public bool Wait
        {
            get => __pbn__Wait.GetValueOrDefault();
            set => __pbn__Wait = value;
        }
        public bool ShouldSerializeWait() => __pbn__Wait != null;
        public void ResetWait() => __pbn__Wait = null;
        private bool? __pbn__Wait;

        [global::ProtoBuf.ProtoMember(7, Name = @"hold_ms")]
        public uint HoldMs
        {
            get => __pbn__HoldMs.GetValueOrDefault();
            set => __pbn__HoldMs = value;
        }
        public bool ShouldSerializeHoldMs() => __pbn__HoldMs != null;
        public void ResetHoldMs() => __pbn__HoldMs = null;
        private uint? __pbn__HoldMs;

        [global::ProtoBuf.ProtoMember(8, Name = @"physical_button")]
        [global::System.ComponentModel.DefaultValue(DebugPhysicalButton.LeftBtn)]
        public DebugPhysicalButton PhysicalButton
        {
            get => __pbn__PhysicalButton ?? DebugPhysicalButton.LeftBtn;
            set => __pbn__PhysicalButton = value;
        }
        public bool ShouldSerializePhysicalButton() => __pbn__PhysicalButton != null;
        public void ResetPhysicalButton() => __pbn__PhysicalButton = null;
        private DebugPhysicalButton? __pbn__PhysicalButton;

        [global::ProtoBuf.ProtoMember(9, Name = @"touch_event_type")]
        [global::System.ComponentModel.DefaultValue(DebugTouchEventType.TouchFullClick)]
        public DebugTouchEventType TouchEventType
        {
            get => __pbn__TouchEventType ?? DebugTouchEventType.TouchFullClick;
            set => __pbn__TouchEventType = value;
        }
        public bool ShouldSerializeTouchEventType() => __pbn__TouchEventType != null;
        public void ResetTouchEventType() => __pbn__TouchEventType = null;
        private DebugTouchEventType? __pbn__TouchEventType;

        [global::ProtoBuf.ProtoContract()]
        public enum DebugSwipeDirection
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UP")]
            Up = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"DOWN")]
            Down = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"LEFT")]
            Left = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"RIGHT")]
            Right = 3,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum DebugButton
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NO")]
            No = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"YES")]
            Yes = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"INFO")]
            Info = 2,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum DebugPhysicalButton
        {
            [global::ProtoBuf.ProtoEnum(Name = @"LEFT_BTN")]
            LeftBtn = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MIDDLE_BTN")]
            MiddleBtn = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"RIGHT_BTN")]
            RightBtn = 2,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum DebugTouchEventType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TOUCH_FULL_CLICK")]
            TouchFullClick = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TOUCH_START")]
            TouchStart = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TOUCH_END")]
            TouchEnd = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    [global::System.Obsolete]
    public partial class DebugLinkLayout : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tokens")]
        public global::System.Collections.Generic.List<string> Tokens { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkReseedRandom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value")]
        public uint Value
        {
            get => __pbn__Value.GetValueOrDefault();
            set => __pbn__Value = value;
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private uint? __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkRecordScreen : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target_directory")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TargetDirectory
        {
            get => __pbn__TargetDirectory ?? "";
            set => __pbn__TargetDirectory = value;
        }
        public bool ShouldSerializeTargetDirectory() => __pbn__TargetDirectory != null;
        public void ResetTargetDirectory() => __pbn__TargetDirectory = null;
        private string __pbn__TargetDirectory;

        [global::ProtoBuf.ProtoMember(2, Name = @"refresh_index")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint RefreshIndex
        {
            get => __pbn__RefreshIndex ?? 0u;
            set => __pbn__RefreshIndex = value;
        }
        public bool ShouldSerializeRefreshIndex() => __pbn__RefreshIndex != null;
        public void ResetRefreshIndex() => __pbn__RefreshIndex = null;
        private uint? __pbn__RefreshIndex;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkGetState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"wait_word_list")]
        [global::System.Obsolete]
        public bool WaitWordList
        {
            get => __pbn__WaitWordList.GetValueOrDefault();
            set => __pbn__WaitWordList = value;
        }
        public bool ShouldSerializeWaitWordList() => __pbn__WaitWordList != null;
        public void ResetWaitWordList() => __pbn__WaitWordList = null;
        private bool? __pbn__WaitWordList;

        [global::ProtoBuf.ProtoMember(2, Name = @"wait_word_pos")]
        [global::System.Obsolete]
        public bool WaitWordPos
        {
            get => __pbn__WaitWordPos.GetValueOrDefault();
            set => __pbn__WaitWordPos = value;
        }
        public bool ShouldSerializeWaitWordPos() => __pbn__WaitWordPos != null;
        public void ResetWaitWordPos() => __pbn__WaitWordPos = null;
        private bool? __pbn__WaitWordPos;

        [global::ProtoBuf.ProtoMember(3, Name = @"wait_layout")]
        [global::System.ComponentModel.DefaultValue(DebugWaitType.Immediate)]
        public DebugWaitType WaitLayout
        {
            get => __pbn__WaitLayout ?? DebugWaitType.Immediate;
            set => __pbn__WaitLayout = value;
        }
        public bool ShouldSerializeWaitLayout() => __pbn__WaitLayout != null;
        public void ResetWaitLayout() => __pbn__WaitLayout = null;
        private DebugWaitType? __pbn__WaitLayout;

        [global::ProtoBuf.ProtoMember(4, Name = @"return_empty_state")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool ReturnEmptyState
        {
            get => __pbn__ReturnEmptyState ?? false;
            set => __pbn__ReturnEmptyState = value;
        }
        public bool ShouldSerializeReturnEmptyState() => __pbn__ReturnEmptyState != null;
        public void ResetReturnEmptyState() => __pbn__ReturnEmptyState = null;
        private bool? __pbn__ReturnEmptyState;

        [global::ProtoBuf.ProtoContract()]
        public enum DebugWaitType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"IMMEDIATE")]
            Immediate = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"NEXT_LAYOUT")]
            NextLayout = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CURRENT_LAYOUT")]
            CurrentLayout = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"layout")]
        public byte[] Layout
        {
            get => __pbn__Layout;
            set => __pbn__Layout = value;
        }
        public bool ShouldSerializeLayout() => __pbn__Layout != null;
        public void ResetLayout() => __pbn__Layout = null;
        private byte[] __pbn__Layout;

        [global::ProtoBuf.ProtoMember(2, Name = @"pin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Pin
        {
            get => __pbn__Pin ?? "";
            set => __pbn__Pin = value;
        }
        public bool ShouldSerializePin() => __pbn__Pin != null;
        public void ResetPin() => __pbn__Pin = null;
        private string __pbn__Pin;

        [global::ProtoBuf.ProtoMember(3, Name = @"matrix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Matrix
        {
            get => __pbn__Matrix ?? "";
            set => __pbn__Matrix = value;
        }
        public bool ShouldSerializeMatrix() => __pbn__Matrix != null;
        public void ResetMatrix() => __pbn__Matrix = null;
        private string __pbn__Matrix;

        [global::ProtoBuf.ProtoMember(4, Name = @"mnemonic_secret")]
        public byte[] MnemonicSecret
        {
            get => __pbn__MnemonicSecret;
            set => __pbn__MnemonicSecret = value;
        }
        public bool ShouldSerializeMnemonicSecret() => __pbn__MnemonicSecret != null;
        public void ResetMnemonicSecret() => __pbn__MnemonicSecret = null;
        private byte[] __pbn__MnemonicSecret;

        [global::ProtoBuf.ProtoMember(5, Name = @"node")]
        public global::hw.trezor.messages.common.HDNodeType Node { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"passphrase_protection")]
        public bool PassphraseProtection
        {
            get => __pbn__PassphraseProtection.GetValueOrDefault();
            set => __pbn__PassphraseProtection = value;
        }
        public bool ShouldSerializePassphraseProtection() => __pbn__PassphraseProtection != null;
        public void ResetPassphraseProtection() => __pbn__PassphraseProtection = null;
        private bool? __pbn__PassphraseProtection;

        [global::ProtoBuf.ProtoMember(7, Name = @"reset_word")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResetWord
        {
            get => __pbn__ResetWord ?? "";
            set => __pbn__ResetWord = value;
        }
        public bool ShouldSerializeResetWord() => __pbn__ResetWord != null;
        public void ResetResetWord() => __pbn__ResetWord = null;
        private string __pbn__ResetWord;

        [global::ProtoBuf.ProtoMember(8, Name = @"reset_entropy")]
        public byte[] ResetEntropy
        {
            get => __pbn__ResetEntropy;
            set => __pbn__ResetEntropy = value;
        }
        public bool ShouldSerializeResetEntropy() => __pbn__ResetEntropy != null;
        public void ResetResetEntropy() => __pbn__ResetEntropy = null;
        private byte[] __pbn__ResetEntropy;

        [global::ProtoBuf.ProtoMember(9, Name = @"recovery_fake_word")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RecoveryFakeWord
        {
            get => __pbn__RecoveryFakeWord ?? "";
            set => __pbn__RecoveryFakeWord = value;
        }
        public bool ShouldSerializeRecoveryFakeWord() => __pbn__RecoveryFakeWord != null;
        public void ResetRecoveryFakeWord() => __pbn__RecoveryFakeWord = null;
        private string __pbn__RecoveryFakeWord;

        [global::ProtoBuf.ProtoMember(10, Name = @"recovery_word_pos")]
        public uint RecoveryWordPos
        {
            get => __pbn__RecoveryWordPos.GetValueOrDefault();
            set => __pbn__RecoveryWordPos = value;
        }
        public bool ShouldSerializeRecoveryWordPos() => __pbn__RecoveryWordPos != null;
        public void ResetRecoveryWordPos() => __pbn__RecoveryWordPos = null;
        private uint? __pbn__RecoveryWordPos;

        [global::ProtoBuf.ProtoMember(11, Name = @"reset_word_pos")]
        public uint ResetWordPos
        {
            get => __pbn__ResetWordPos.GetValueOrDefault();
            set => __pbn__ResetWordPos = value;
        }
        public bool ShouldSerializeResetWordPos() => __pbn__ResetWordPos != null;
        public void ResetResetWordPos() => __pbn__ResetWordPos = null;
        private uint? __pbn__ResetWordPos;

        [global::ProtoBuf.ProtoMember(12, Name = @"mnemonic_type")]
        [global::System.ComponentModel.DefaultValue(global::hw.trezor.messages.management.BackupType.Bip39)]
        public global::hw.trezor.messages.management.BackupType MnemonicType
        {
            get => __pbn__MnemonicType ?? global::hw.trezor.messages.management.BackupType.Bip39;
            set => __pbn__MnemonicType = value;
        }
        public bool ShouldSerializeMnemonicType() => __pbn__MnemonicType != null;
        public void ResetMnemonicType() => __pbn__MnemonicType = null;
        private global::hw.trezor.messages.management.BackupType? __pbn__MnemonicType;

        [global::ProtoBuf.ProtoMember(13, Name = @"tokens")]
        public global::System.Collections.Generic.List<string> Tokens { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkGetPairingInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel_id")]
        public byte[] ChannelId
        {
            get => __pbn__ChannelId;
            set => __pbn__ChannelId = value;
        }
        public bool ShouldSerializeChannelId() => __pbn__ChannelId != null;
        public void ResetChannelId() => __pbn__ChannelId = null;
        private byte[] __pbn__ChannelId;

        [global::ProtoBuf.ProtoMember(2, Name = @"handshake_hash")]
        public byte[] HandshakeHash
        {
            get => __pbn__HandshakeHash;
            set => __pbn__HandshakeHash = value;
        }
        public bool ShouldSerializeHandshakeHash() => __pbn__HandshakeHash != null;
        public void ResetHandshakeHash() => __pbn__HandshakeHash = null;
        private byte[] __pbn__HandshakeHash;

        [global::ProtoBuf.ProtoMember(3, Name = @"nfc_secret_host")]
        public byte[] NfcSecretHost
        {
            get => __pbn__NfcSecretHost;
            set => __pbn__NfcSecretHost = value;
        }
        public bool ShouldSerializeNfcSecretHost() => __pbn__NfcSecretHost != null;
        public void ResetNfcSecretHost() => __pbn__NfcSecretHost = null;
        private byte[] __pbn__NfcSecretHost;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkPairingInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel_id")]
        public byte[] ChannelId
        {
            get => __pbn__ChannelId;
            set => __pbn__ChannelId = value;
        }
        public bool ShouldSerializeChannelId() => __pbn__ChannelId != null;
        public void ResetChannelId() => __pbn__ChannelId = null;
        private byte[] __pbn__ChannelId;

        [global::ProtoBuf.ProtoMember(2, Name = @"handshake_hash")]
        public byte[] HandshakeHash
        {
            get => __pbn__HandshakeHash;
            set => __pbn__HandshakeHash = value;
        }
        public bool ShouldSerializeHandshakeHash() => __pbn__HandshakeHash != null;
        public void ResetHandshakeHash() => __pbn__HandshakeHash = null;
        private byte[] __pbn__HandshakeHash;

        [global::ProtoBuf.ProtoMember(3, Name = @"code_entry_code")]
        public uint CodeEntryCode
        {
            get => __pbn__CodeEntryCode.GetValueOrDefault();
            set => __pbn__CodeEntryCode = value;
        }
        public bool ShouldSerializeCodeEntryCode() => __pbn__CodeEntryCode != null;
        public void ResetCodeEntryCode() => __pbn__CodeEntryCode = null;
        private uint? __pbn__CodeEntryCode;

        [global::ProtoBuf.ProtoMember(4, Name = @"code_qr_code")]
        public byte[] CodeQrCode
        {
            get => __pbn__CodeQrCode;
            set => __pbn__CodeQrCode = value;
        }
        public bool ShouldSerializeCodeQrCode() => __pbn__CodeQrCode != null;
        public void ResetCodeQrCode() => __pbn__CodeQrCode = null;
        private byte[] __pbn__CodeQrCode;

        [global::ProtoBuf.ProtoMember(5, Name = @"nfc_secret_trezor")]
        public byte[] NfcSecretTrezor
        {
            get => __pbn__NfcSecretTrezor;
            set => __pbn__NfcSecretTrezor = value;
        }
        public bool ShouldSerializeNfcSecretTrezor() => __pbn__NfcSecretTrezor != null;
        public void ResetNfcSecretTrezor() => __pbn__NfcSecretTrezor = null;
        private byte[] __pbn__NfcSecretTrezor;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkStop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkLog : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(2, Name = @"bucket")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Bucket
        {
            get => __pbn__Bucket ?? "";
            set => __pbn__Bucket = value;
        }
        public bool ShouldSerializeBucket() => __pbn__Bucket != null;
        public void ResetBucket() => __pbn__Bucket = null;
        private string __pbn__Bucket;

        [global::ProtoBuf.ProtoMember(3, Name = @"text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Text
        {
            get => __pbn__Text ?? "";
            set => __pbn__Text = value;
        }
        public bool ShouldSerializeText() => __pbn__Text != null;
        public void ResetText() => __pbn__Text = null;
        private string __pbn__Text;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkMemoryRead : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        public uint Address
        {
            get => __pbn__Address.GetValueOrDefault();
            set => __pbn__Address = value;
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private uint? __pbn__Address;

        [global::ProtoBuf.ProtoMember(2, Name = @"length")]
        public uint Length
        {
            get => __pbn__Length.GetValueOrDefault();
            set => __pbn__Length = value;
        }
        public bool ShouldSerializeLength() => __pbn__Length != null;
        public void ResetLength() => __pbn__Length = null;
        private uint? __pbn__Length;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkMemory : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"memory")]
        public byte[] Memory
        {
            get => __pbn__Memory;
            set => __pbn__Memory = value;
        }
        public bool ShouldSerializeMemory() => __pbn__Memory != null;
        public void ResetMemory() => __pbn__Memory = null;
        private byte[] __pbn__Memory;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkMemoryWrite : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        public uint Address
        {
            get => __pbn__Address.GetValueOrDefault();
            set => __pbn__Address = value;
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private uint? __pbn__Address;

        [global::ProtoBuf.ProtoMember(2, Name = @"memory")]
        public byte[] Memory
        {
            get => __pbn__Memory;
            set => __pbn__Memory = value;
        }
        public bool ShouldSerializeMemory() => __pbn__Memory != null;
        public void ResetMemory() => __pbn__Memory = null;
        private byte[] __pbn__Memory;

        [global::ProtoBuf.ProtoMember(3, Name = @"flash")]
        public bool Flash
        {
            get => __pbn__Flash.GetValueOrDefault();
            set => __pbn__Flash = value;
        }
        public bool ShouldSerializeFlash() => __pbn__Flash != null;
        public void ResetFlash() => __pbn__Flash = null;
        private bool? __pbn__Flash;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkFlashErase : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sector")]
        public uint Sector
        {
            get => __pbn__Sector.GetValueOrDefault();
            set => __pbn__Sector = value;
        }
        public bool ShouldSerializeSector() => __pbn__Sector != null;
        public void ResetSector() => __pbn__Sector = null;
        private uint? __pbn__Sector;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkEraseSdCard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"format")]
        public bool Format
        {
            get => __pbn__Format.GetValueOrDefault();
            set => __pbn__Format = value;
        }
        public bool ShouldSerializeFormat() => __pbn__Format != null;
        public void ResetFormat() => __pbn__Format = null;
        private bool? __pbn__Format;

    }

    [global::ProtoBuf.ProtoContract()]
    [global::System.Obsolete]
    public partial class DebugLinkWatchLayout : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"watch")]
        public bool Watch
        {
            get => __pbn__Watch.GetValueOrDefault();
            set => __pbn__Watch = value;
        }
        public bool ShouldSerializeWatch() => __pbn__Watch != null;
        public void ResetWatch() => __pbn__Watch = null;
        private bool? __pbn__Watch;

    }

    [global::ProtoBuf.ProtoContract()]
    [global::System.Obsolete]
    public partial class DebugLinkResetDebugEvents : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkOptigaSetSecMax : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkGetGcInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkGcInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"items")]
        public global::System.Collections.Generic.List<DebugLinkGcInfoItem> Items { get; } = new global::System.Collections.Generic.List<DebugLinkGcInfoItem>();

        [global::ProtoBuf.ProtoContract()]
        public partial class DebugLinkGcInfoItem : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
            public string Name { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
            public ulong Value { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
