// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: messages-ethereum.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hw.trezor.messages.ethereum
{

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumGetPublicKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"show_display")]
        public bool ShowDisplay
        {
            get => __pbn__ShowDisplay.GetValueOrDefault();
            set => __pbn__ShowDisplay = value;
        }
        public bool ShouldSerializeShowDisplay() => __pbn__ShowDisplay != null;
        public void ResetShowDisplay() => __pbn__ShowDisplay = null;
        private bool? __pbn__ShowDisplay;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumPublicKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node", IsRequired = true)]
        public global::hw.trezor.messages.common.HDNodeType Node { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"xpub", IsRequired = true)]
        public string Xpub { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumGetAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"show_display")]
        public bool ShowDisplay
        {
            get => __pbn__ShowDisplay.GetValueOrDefault();
            set => __pbn__ShowDisplay = value;
        }
        public bool ShouldSerializeShowDisplay() => __pbn__ShowDisplay != null;
        public void ResetShowDisplay() => __pbn__ShowDisplay = null;
        private bool? __pbn__ShowDisplay;

        [global::ProtoBuf.ProtoMember(3, Name = @"encoded_network")]
        public byte[] EncodedNetwork
        {
            get => __pbn__EncodedNetwork;
            set => __pbn__EncodedNetwork = value;
        }
        public bool ShouldSerializeEncodedNetwork() => __pbn__EncodedNetwork != null;
        public void ResetEncodedNetwork() => __pbn__EncodedNetwork = null;
        private byte[] __pbn__EncodedNetwork;

        [global::ProtoBuf.ProtoMember(4, Name = @"chunkify")]
        public bool Chunkify
        {
            get => __pbn__Chunkify.GetValueOrDefault();
            set => __pbn__Chunkify = value;
        }
        public bool ShouldSerializeChunkify() => __pbn__Chunkify != null;
        public void ResetChunkify() => __pbn__Chunkify = null;
        private bool? __pbn__Chunkify;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"_old_address")]
        [global::System.Obsolete]
        public byte[] OldAddress
        {
            get => __pbn__OldAddress;
            set => __pbn__OldAddress = value;
        }
        public bool ShouldSerializeOldAddress() => __pbn__OldAddress != null;
        public void ResetOldAddress() => __pbn__OldAddress = null;
        private byte[] __pbn__OldAddress;

        [global::ProtoBuf.ProtoMember(2, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address
        {
            get => __pbn__Address ?? "";
            set => __pbn__Address = value;
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private string __pbn__Address;

        [global::ProtoBuf.ProtoMember(3, Name = @"mac")]
        public byte[] Mac
        {
            get => __pbn__Mac;
            set => __pbn__Mac = value;
        }
        public bool ShouldSerializeMac() => __pbn__Mac != null;
        public void ResetMac() => __pbn__Mac = null;
        private byte[] __pbn__Mac;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumSignTx : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nonce")]
        public byte[] Nonce
        {
            get => __pbn__Nonce;
            set => __pbn__Nonce = value;
        }
        public bool ShouldSerializeNonce() => __pbn__Nonce != null;
        public void ResetNonce() => __pbn__Nonce = null;
        private byte[] __pbn__Nonce;

        [global::ProtoBuf.ProtoMember(3, Name = @"gas_price", IsRequired = true)]
        public byte[] GasPrice { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"gas_limit", IsRequired = true)]
        public byte[] GasLimit { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"to")]
        [global::System.ComponentModel.DefaultValue("")]
        public string To
        {
            get => __pbn__To ?? "";
            set => __pbn__To = value;
        }
        public bool ShouldSerializeTo() => __pbn__To != null;
        public void ResetTo() => __pbn__To = null;
        private string __pbn__To;

        [global::ProtoBuf.ProtoMember(6, Name = @"value")]
        public byte[] Value
        {
            get => __pbn__Value;
            set => __pbn__Value = value;
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private byte[] __pbn__Value;

        [global::ProtoBuf.ProtoMember(7, Name = @"data_initial_chunk")]
        public byte[] DataInitialChunk
        {
            get => __pbn__DataInitialChunk;
            set => __pbn__DataInitialChunk = value;
        }
        public bool ShouldSerializeDataInitialChunk() => __pbn__DataInitialChunk != null;
        public void ResetDataInitialChunk() => __pbn__DataInitialChunk = null;
        private byte[] __pbn__DataInitialChunk;

        [global::ProtoBuf.ProtoMember(8, Name = @"data_length")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint DataLength
        {
            get => __pbn__DataLength ?? 0u;
            set => __pbn__DataLength = value;
        }
        public bool ShouldSerializeDataLength() => __pbn__DataLength != null;
        public void ResetDataLength() => __pbn__DataLength = null;
        private uint? __pbn__DataLength;

        [global::ProtoBuf.ProtoMember(9, Name = @"chain_id", IsRequired = true)]
        public ulong ChainId { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"tx_type")]
        public uint TxType
        {
            get => __pbn__TxType.GetValueOrDefault();
            set => __pbn__TxType = value;
        }
        public bool ShouldSerializeTxType() => __pbn__TxType != null;
        public void ResetTxType() => __pbn__TxType = null;
        private uint? __pbn__TxType;

        [global::ProtoBuf.ProtoMember(12, Name = @"definitions")]
        public EthereumDefinitions Definitions { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"chunkify")]
        public bool Chunkify
        {
            get => __pbn__Chunkify.GetValueOrDefault();
            set => __pbn__Chunkify = value;
        }
        public bool ShouldSerializeChunkify() => __pbn__Chunkify != null;
        public void ResetChunkify() => __pbn__Chunkify = null;
        private bool? __pbn__Chunkify;

        [global::ProtoBuf.ProtoMember(14, Name = @"payment_req")]
        public global::hw.trezor.messages.common.PaymentRequest PaymentReq { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumSignTxEIP1559 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nonce", IsRequired = true)]
        public byte[] Nonce { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"max_gas_fee", IsRequired = true)]
        public byte[] MaxGasFee { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"max_priority_fee", IsRequired = true)]
        public byte[] MaxPriorityFee { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"gas_limit", IsRequired = true)]
        public byte[] GasLimit { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"to")]
        [global::System.ComponentModel.DefaultValue("")]
        public string To
        {
            get => __pbn__To ?? "";
            set => __pbn__To = value;
        }
        public bool ShouldSerializeTo() => __pbn__To != null;
        public void ResetTo() => __pbn__To = null;
        private string __pbn__To;

        [global::ProtoBuf.ProtoMember(7, Name = @"value", IsRequired = true)]
        public byte[] Value { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"data_initial_chunk")]
        public byte[] DataInitialChunk
        {
            get => __pbn__DataInitialChunk;
            set => __pbn__DataInitialChunk = value;
        }
        public bool ShouldSerializeDataInitialChunk() => __pbn__DataInitialChunk != null;
        public void ResetDataInitialChunk() => __pbn__DataInitialChunk = null;
        private byte[] __pbn__DataInitialChunk;

        [global::ProtoBuf.ProtoMember(9, Name = @"data_length", IsRequired = true)]
        public uint DataLength { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"chain_id", IsRequired = true)]
        public ulong ChainId { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"access_list")]
        public global::System.Collections.Generic.List<EthereumAccessList> AccessLists { get; } = new global::System.Collections.Generic.List<EthereumAccessList>();

        [global::ProtoBuf.ProtoMember(12, Name = @"definitions")]
        public EthereumDefinitions Definitions { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"chunkify")]
        public bool Chunkify
        {
            get => __pbn__Chunkify.GetValueOrDefault();
            set => __pbn__Chunkify = value;
        }
        public bool ShouldSerializeChunkify() => __pbn__Chunkify != null;
        public void ResetChunkify() => __pbn__Chunkify = null;
        private bool? __pbn__Chunkify;

        [global::ProtoBuf.ProtoMember(14, Name = @"payment_req")]
        public global::hw.trezor.messages.common.PaymentRequest PaymentReq { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class EthereumAccessList : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"address", IsRequired = true)]
            public string Address { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"storage_keys")]
            public global::System.Collections.Generic.List<byte[]> StorageKeys { get; } = new global::System.Collections.Generic.List<byte[]>();

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumTxRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data_length")]
        public uint DataLength
        {
            get => __pbn__DataLength.GetValueOrDefault();
            set => __pbn__DataLength = value;
        }
        public bool ShouldSerializeDataLength() => __pbn__DataLength != null;
        public void ResetDataLength() => __pbn__DataLength = null;
        private uint? __pbn__DataLength;

        [global::ProtoBuf.ProtoMember(2, Name = @"signature_v")]
        public uint SignatureV
        {
            get => __pbn__SignatureV.GetValueOrDefault();
            set => __pbn__SignatureV = value;
        }
        public bool ShouldSerializeSignatureV() => __pbn__SignatureV != null;
        public void ResetSignatureV() => __pbn__SignatureV = null;
        private uint? __pbn__SignatureV;

        [global::ProtoBuf.ProtoMember(3, Name = @"signature_r")]
        public byte[] SignatureR
        {
            get => __pbn__SignatureR;
            set => __pbn__SignatureR = value;
        }
        public bool ShouldSerializeSignatureR() => __pbn__SignatureR != null;
        public void ResetSignatureR() => __pbn__SignatureR = null;
        private byte[] __pbn__SignatureR;

        [global::ProtoBuf.ProtoMember(4, Name = @"signature_s")]
        public byte[] SignatureS
        {
            get => __pbn__SignatureS;
            set => __pbn__SignatureS = value;
        }
        public bool ShouldSerializeSignatureS() => __pbn__SignatureS != null;
        public void ResetSignatureS() => __pbn__SignatureS = null;
        private byte[] __pbn__SignatureS;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumTxAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data_chunk", IsRequired = true)]
        public byte[] DataChunk { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumSignMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message", IsRequired = true)]
        public byte[] Message { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"encoded_network")]
        public byte[] EncodedNetwork
        {
            get => __pbn__EncodedNetwork;
            set => __pbn__EncodedNetwork = value;
        }
        public bool ShouldSerializeEncodedNetwork() => __pbn__EncodedNetwork != null;
        public void ResetEncodedNetwork() => __pbn__EncodedNetwork = null;
        private byte[] __pbn__EncodedNetwork;

        [global::ProtoBuf.ProtoMember(4, Name = @"chunkify")]
        public bool Chunkify
        {
            get => __pbn__Chunkify.GetValueOrDefault();
            set => __pbn__Chunkify = value;
        }
        public bool ShouldSerializeChunkify() => __pbn__Chunkify != null;
        public void ResetChunkify() => __pbn__Chunkify = null;
        private bool? __pbn__Chunkify;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumMessageSignature : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"signature", IsRequired = true)]
        public byte[] Signature { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"address", IsRequired = true)]
        public string Address { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumVerifyMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"signature", IsRequired = true)]
        public byte[] Signature { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"message", IsRequired = true)]
        public byte[] Message { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"address", IsRequired = true)]
        public string Address { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"chunkify")]
        public bool Chunkify
        {
            get => __pbn__Chunkify.GetValueOrDefault();
            set => __pbn__Chunkify = value;
        }
        public bool ShouldSerializeChunkify() => __pbn__Chunkify != null;
        public void ResetChunkify() => __pbn__Chunkify = null;
        private bool? __pbn__Chunkify;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumSignTypedHash : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"domain_separator_hash", IsRequired = true)]
        public byte[] DomainSeparatorHash { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"message_hash")]
        public byte[] MessageHash
        {
            get => __pbn__MessageHash;
            set => __pbn__MessageHash = value;
        }
        public bool ShouldSerializeMessageHash() => __pbn__MessageHash != null;
        public void ResetMessageHash() => __pbn__MessageHash = null;
        private byte[] __pbn__MessageHash;

        [global::ProtoBuf.ProtoMember(4, Name = @"encoded_network")]
        public byte[] EncodedNetwork
        {
            get => __pbn__EncodedNetwork;
            set => __pbn__EncodedNetwork = value;
        }
        public bool ShouldSerializeEncodedNetwork() => __pbn__EncodedNetwork != null;
        public void ResetEncodedNetwork() => __pbn__EncodedNetwork = null;
        private byte[] __pbn__EncodedNetwork;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumTypedDataSignature : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"signature", IsRequired = true)]
        public byte[] Signature { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"address", IsRequired = true)]
        public string Address { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumDefinitions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"encoded_network")]
        public byte[] EncodedNetwork
        {
            get => __pbn__EncodedNetwork;
            set => __pbn__EncodedNetwork = value;
        }
        public bool ShouldSerializeEncodedNetwork() => __pbn__EncodedNetwork != null;
        public void ResetEncodedNetwork() => __pbn__EncodedNetwork = null;
        private byte[] __pbn__EncodedNetwork;

        [global::ProtoBuf.ProtoMember(2, Name = @"encoded_token")]
        public byte[] EncodedToken
        {
            get => __pbn__EncodedToken;
            set => __pbn__EncodedToken = value;
        }
        public bool ShouldSerializeEncodedToken() => __pbn__EncodedToken != null;
        public void ResetEncodedToken() => __pbn__EncodedToken = null;
        private byte[] __pbn__EncodedToken;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
