// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: messages-ethereum-eip712.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hw.trezor.messages.ethereumeip712
{

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumSignTypedData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"primary_type", IsRequired = true)]
        public string PrimaryType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"metamask_v4_compat")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool MetamaskV4Compat
        {
            get => __pbn__MetamaskV4Compat ?? true;
            set => __pbn__MetamaskV4Compat = value;
        }
        public bool ShouldSerializeMetamaskV4Compat() => __pbn__MetamaskV4Compat != null;
        public void ResetMetamaskV4Compat() => __pbn__MetamaskV4Compat = null;
        private bool? __pbn__MetamaskV4Compat;

        [global::ProtoBuf.ProtoMember(4, Name = @"definitions")]
        public global::hw.trezor.messages.ethereum.EthereumDefinitions Definitions { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"show_message_hash")]
        public byte[] ShowMessageHash
        {
            get => __pbn__ShowMessageHash;
            set => __pbn__ShowMessageHash = value;
        }
        public bool ShouldSerializeShowMessageHash() => __pbn__ShowMessageHash != null;
        public void ResetShowMessageHash() => __pbn__ShowMessageHash = null;
        private byte[] __pbn__ShowMessageHash;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumTypedDataStructRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumTypedDataStructAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"members")]
        public global::System.Collections.Generic.List<EthereumStructMember> Members { get; } = new global::System.Collections.Generic.List<EthereumStructMember>();

        [global::ProtoBuf.ProtoContract()]
        public partial class EthereumStructMember : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
            public EthereumTypedDataStructAck.EthereumFieldType Type { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
            public string Name { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EthereumFieldType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"data_type", IsRequired = true)]
            public EthereumTypedDataStructAck.EthereumDataType DataType { get; set; } = EthereumTypedDataStructAck.EthereumDataType.Uint;

            [global::ProtoBuf.ProtoMember(2, Name = @"size")]
            public uint Size
            {
                get => __pbn__Size.GetValueOrDefault();
                set => __pbn__Size = value;
            }
            public bool ShouldSerializeSize() => __pbn__Size != null;
            public void ResetSize() => __pbn__Size = null;
            private uint? __pbn__Size;

            [global::ProtoBuf.ProtoMember(3, Name = @"entry_type")]
            public EthereumFieldType EntryType { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"struct_name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string StructName
            {
                get => __pbn__StructName ?? "";
                set => __pbn__StructName = value;
            }
            public bool ShouldSerializeStructName() => __pbn__StructName != null;
            public void ResetStructName() => __pbn__StructName = null;
            private string __pbn__StructName;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum EthereumDataType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UINT")]
            Uint = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"INT")]
            Int = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"BYTES")]
            Bytes = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"STRING")]
            String = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"BOOL")]
            Bool = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"ADDRESS")]
            Address = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"ARRAY")]
            Array = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"STRUCT")]
            Struct = 8,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumTypedDataValueRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"member_path")]
        public uint[] MemberPaths { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumTypedDataValueAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value", IsRequired = true)]
        public byte[] Value { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
