// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: options.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hw.trezor.messages
{

    public static partial class Extensions
    {
        public static bool GetWireIn(this global::Google.Protobuf.Reflection.EnumValueOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 50002);

        public static void SetWireIn(this global::Google.Protobuf.Reflection.EnumValueOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 50002, value);

        public static bool GetWireOut(this global::Google.Protobuf.Reflection.EnumValueOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 50003);

        public static void SetWireOut(this global::Google.Protobuf.Reflection.EnumValueOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 50003, value);

        public static bool GetWireDebugIn(this global::Google.Protobuf.Reflection.EnumValueOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 50004);

        public static void SetWireDebugIn(this global::Google.Protobuf.Reflection.EnumValueOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 50004, value);

        public static bool GetWireDebugOut(this global::Google.Protobuf.Reflection.EnumValueOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 50005);

        public static void SetWireDebugOut(this global::Google.Protobuf.Reflection.EnumValueOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 50005, value);

        public static bool GetWireTiny(this global::Google.Protobuf.Reflection.EnumValueOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 50006);

        public static void SetWireTiny(this global::Google.Protobuf.Reflection.EnumValueOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 50006, value);

        public static bool GetWireBootloader(this global::Google.Protobuf.Reflection.EnumValueOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 50007);

        public static void SetWireBootloader(this global::Google.Protobuf.Reflection.EnumValueOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 50007, value);

        public static bool GetWireNoFsm(this global::Google.Protobuf.Reflection.EnumValueOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 50008);

        public static void SetWireNoFsm(this global::Google.Protobuf.Reflection.EnumValueOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 50008, value);

        public static bool GetBitcoinOnly(this global::Google.Protobuf.Reflection.EnumValueOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 60000);

        public static void SetBitcoinOnly(this global::Google.Protobuf.Reflection.EnumValueOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 60000, value);

        public static bool GetHasBitcoinOnlyValues(this global::Google.Protobuf.Reflection.EnumOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 51001);

        public static void SetHasBitcoinOnlyValues(this global::Google.Protobuf.Reflection.EnumOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 51001, value);

        public static bool GetWireEnum(this global::Google.Protobuf.Reflection.EnumOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 51002);

        public static void SetWireEnum(this global::Google.Protobuf.Reflection.EnumOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 51002, value);

        public static bool GetExperimentalMessage(this global::Google.Protobuf.Reflection.MessageOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 52001);

        public static void SetExperimentalMessage(this global::Google.Protobuf.Reflection.MessageOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 52001, value);

        public static uint GetWireType(this global::Google.Protobuf.Reflection.MessageOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<uint>(obj, 52002);

        public static void SetWireType(this global::Google.Protobuf.Reflection.MessageOptions obj, uint value)
            => global::ProtoBuf.Extensible.AppendValue<uint>(obj, 52002, value);

        public static bool GetInternalOnly(this global::Google.Protobuf.Reflection.MessageOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 52003);

        public static void SetInternalOnly(this global::Google.Protobuf.Reflection.MessageOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 52003, value);

        public static bool GetExperimentalField(this global::Google.Protobuf.Reflection.FieldOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 53001);

        public static void SetExperimentalField(this global::Google.Protobuf.Reflection.FieldOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 53001, value);

        public static bool GetIncludeInBitcoinOnly(this global::Google.Protobuf.Reflection.FileOptions obj)
            => obj == null ? default : global::ProtoBuf.Extensible.GetValue<bool>(obj, 60000);

        public static void SetIncludeInBitcoinOnly(this global::Google.Protobuf.Reflection.FileOptions obj, bool value)
            => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 60000, value);

    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
